### ISSUE TITLE
DateTime field format not reflected in datepicker.

### ISSUE THREAD

**Issue by koenhendriks** [laravel/nova-issues#1069]
- Laravel Version: 5.7.15
- Nova Version: 1.2.0
- PHP Version: 7.2.11

### Description:
When creating a DateTime field the given format is being ignored in the form. Also, the 24 hour notation is not being used by the datepicker in the form.

Using the following field in the resource:
```php
DateTime::make('planned_on')
    ->format('H:mm DD-MM-YYYY')
```

![screenshot from 2018-12-01 15-19-37](https://user-images.githubusercontent.com/4124579/49329341-66403080-f57d-11e8-8e5b-833db8b62a4c.png)

### Steps To Reproduce:
1. Set timezone to desired format ( my case Europe/Amsterdam )
```php
Nova::userTimezone(function () {
    return 'Europe/Amsterdam';
});
```
2. Create Nova resource
3. Set format on resource
```php
DateTime::make('planned_on')
    ->format('H:mm DD-MM-YYYY')
```
4. Create or edit resource in Nova frontend.
5. Format is not being used 
6. Datepicker shows AM/PM time.

**Comment by koenhendriks** [comment]
Just noticing that `i` in format is not displaying correctly in index and view.

__Index__:
![screenshot from 2018-12-01 15-35-45](https://user-images.githubusercontent.com/4124579/49329412-cf747380-f57e-11e8-9a90-f1dfb19370c3.png)

__View__:
![screenshot from 2018-12-01 15-35-51](https://user-images.githubusercontent.com/4124579/49329413-d3a09100-f57e-11e8-80e6-6db8f0980dcc.png)

**Comment by Senexis** [comment]
Still applicable in Nova 1.3.0 with Laravel 5.7.20.

The issue (for the placeholder at least) seems to be at `\resources\js\components\Form\DateTimeField.vue` line 40 due to a hardcoded `moment().format()`, whereas the same component in `\Detail\` seems to use `this.localizeDateTimeField`. Would love for the hardcoded `moment().format()`s to be solved. There seems to be a few floating around, while the `DateTime::make()->format()` value should instead be used.

Thank you very much. :-)

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
