### ISSUE TITLE
Too many records in BelongsToMany breaks PHP

### ISSUE THREAD

**Issue by beerbuddha** [laravel/nova-issues#1109]
- Laravel Version: 5.7.14
- Nova Version: 1.2.0
- PHP Version: 7.2.12

### Description:
Given BelongsToMany Field on a resource - if the relation is over 20k records - it breaks php memory

### Steps To Reproduce:

Given a BelgonsToMany relationship between Thread and Users.
Create over 20k users attach to the single thread

As a Thread resource, on index resource, I can see how many users 
```
            Number::make('Users', function () {
                return $this->userCount();
            })
                ->hideWhenCreating()
                ->hideWhenUpdating(),   
            BelongsToMany::make('Users', 'users', Users::class)->fields(function () {
                return [
                    Text::make('weight', 'value'),
                ];
            }),
```

On the given detail of the resource - it breaks due to memory cap.
I have seen in the dock:
https://nova.laravel.com/docs/1.0/resources/relationships.html#morphtomany

that we can use `searchable()` to prevent a BelongsToMany however typically this is applied during CREATE/UPDATE this is on detail.
Also I expected as a behavior that due to pagination of this relation (that works for records under 20k) - I thought the pagination would prevent this from happening?

ALSO:
I tried adding `    public static $with = ['users'];` inside the Thread Nova Resource. That actually breaks the index resource page instead.

**Comment by webhealer** [comment]
I think memory issue problem may be related if you use "laravel-debugbar".  try to disable it. But the main problem is possibly related with return $this->userCount(); 

What is the details of userCount function? It seems like you call same data in each field load. If the per page record is 25,  then this function calling 25 times, which is not good.

also you can use "exceptOnForms"  instead of defining "  ->hideWhenCreating()              ->hideWhenUpdating(),  ,   but this is not related with the problem.

**Comment by webhealer** [comment]
Thanks for the information @beerbuddha . Then it's may be the issue of the  BelongsToMany field .

i had a problem  with BelongsTo Field , "eager loading", which is defined here: https://github.com/laravel/nova-issues/issues/112 And i solved it editing nova core code. But BelongsToMany field have different structure. I guess similar "eager loading" problem exists for this field type too. Hopefully it's will be fixed soon, good luck!

**Comment by webhealer** [comment]
also additional information:  it's better to check , when you click one of the "thread" detail page, from firebug / chrome dev tools, search for url  "users?search="    from xhr panel, you can view the request details , to see the actual  loaded data / fields , in order to debug.  that will show you the relation data details and load time. and you can see if it's responsible for the memory issue.  you can open the request in new window to test it.

**Comment by beerbuddha** [comment]
@webhealer 
thanks for the link of the tip - ill try to explore the venue - editing the core code means that if you update you will squash the edit or at least have to be aware to do a trim.... aint that a bit on the dangerous side? Wouldn't it have been best to extend the core or create a nova-component?

**Comment by webhealer** [comment]
yes i was trying to say to extend the core code. it would be better.

**Comment by bomshteyn** [comment]
I have extended it for myself into a separate BelongsTo field here: (https://novapackages.com/packages/treestoneit/belongs-to-field) 
maybe you can do the same for BelongsToMany

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
