### ISSUE TITLE
Filters' default value ins't being count on load

### ISSUE THREAD

**Issue by itainathaniel** [laravel/nova-issues#1138]
- Laravel Version: 5.7.16
- Nova Version: 1.0
- PHP Version: 7.2.5

### Description:
When setting default value for a `Filter` or a `DateFilter`, the filter counter on the resource's page doesn't indicate there is an active filter.

![screen shot 2018-12-18 at 0 07 49](https://user-images.githubusercontent.com/971236/50118973-08d50080-025a-11e9-8b44-fc232f38296b.png)
In the attached image, this filter has this code:
```
<?php

namespace App\Nova\Filters;

use Illuminate\Http\Request;
use Laravel\Nova\Filters\Filter;

class GeneralCourse extends Filter
{
    public $name = 'Course';

    public $component = 'select-filter';

    public function apply(Request $request, $query, $value)
    {
        ...
    }

    public function options(Request $request)
    {
        return [
            'French Cooking' => 1,
            'Bread Baking' => 2,
        ];
    }

    public function default()
    {
        return 1;
    }
}
```

### Steps To Reproduce:

1. Add a `Filter` or a `DateFilter` ([select](https://nova.laravel.com/docs/1.0/filters/defining-filters.html#select-filters) or [date](https://nova.laravel.com/docs/1.0/filters/defining-filters.html#date-filters) filters)
2. Make sure the filter has a valid default value function
3. Go to the resource page
4. Verify that the filter counter doesn't show any number
5. If there is a number, open the filters panel and click on **RESET FILTERS** and go back to step 4

### Suggestion of fix

The store variable of `activeFilterCount` is set on `nova/resources/js/store/resources.js`:
```
activeFilterCount: (state, getters) => {
    return _.reduce(
        state.filters,
        (result, f) => {
            const originalFilter = getters.getOriginalFilter(f.class)
            const originalFilterCloneValue = JSON.stringify(originalFilter.currentValue)
            const currentFilterCloneValue = JSON.stringify(f.currentValue)
            return currentFilterCloneValue == originalFilterCloneValue ? result : result + 1
        },
        0
    )
},
```

If the return line `return currentFilterCloneValue == originalFilterCloneValue ? result : result + 1` would be something like `return currentFilterCloneValue == originalFilterCloneValue && currentFilterCloneValue == "" ? result : result + 1` the count will be correct.

**Comment by davidhemphill** [comment]
I don't really consider this a bug. The default value is there as a way to reset the filter "back to zero". Any deviation from the default is counted.

**Comment by mikebronner** [comment]
@davidhemphill  The use-case we have is that we are displaying only records created by the user by default. When there is no indicator on the filter widget, it tells them no filter is applied, even though there is. Because of this we always get confused users asking why they can't find records, and we have to explain to them that this is unfortunately how the filter widget works.

It would be great if there was a way to apply a filter on load, but have the default state be no filter selected, so that the counter would be triggered. Any suggestions how one might go about doing this?

**Comment by christophrumpel** [comment]
Running in the same problem as Mike mentioned. In my case defining a `default` is also like having the filter on and that should be visible to the user. If the `default` method is not meant to be used like that, maybe we could add a  `default filter` we can set on the resource so that on loading this filter is active.
