### ISSUE TITLE
Can't change dateFilter format

### ISSUE THREAD

**Issue by MarouaneSH** [laravel/nova-issues#1170]
- Laravel Version: 5.7.*
- Nova Version: 1.*.*
- PHP Version: PHP 7.2

### Description:
I'm trying to filter resources data by Month only using the DateFilter fitler, but I can't make a custom format for the DateFilter.
I had a look at the DateFilter.vue component, and there isn't any props for changing the dateFromat
<img width="792" alt="screen shot 2018-12-26 at 17 33 36" src="https://user-images.githubusercontent.com/23389104/50451464-13fbf080-092c-11e9-9825-96871c56623c.png">

Here is the options in my custom filter 
<img width="684" alt="screen shot 2018-12-26 at 17 35 03" src="https://user-images.githubusercontent.com/23389104/50451483-355cdc80-092c-11e9-8ff8-e044aac0b4e0.png">

**Comment by mrigo** [comment]
Same here.
Any solutions?

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by renky** [comment]
It still there in 
laravel/nova                            v2.9.4 

Since the File DatePicker.vue wasn't changed and still contains the Line 
`dateFormat` = "Y-m-d"
I think the answer with "unsupported version of Nova" wasn't really constructive.

The question is: is it wished to have a changeable DateFormat for Filters? And I think, since we already have this option for Fields, it's only consistent to do this also for DateFilters.
