### ISSUE TITLE
Create an `static ` action that doesn't require a particular model to be launched

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/nova-issues#1280]
Hi, I have some actions on Model classes that are generic to those models and not bound to a specific instances. 
For example `empty model cache` or `export list as csv`.

I need to force user to select one or more models to enable them, but is a logical unnecessary step.

**Comment by tylernathanreed** [comment]
@alberto-bottarini This is something that I'm wanting too. I'm thinking about making a PR for it.

How do you imagine this will be implemented? Like, where would this appear in the existing UI? Would it be part of the actions dropdown (at all times)? Would it be available as a separate button?

**Comment by alberto-bottarini** [comment]
I'm not a huge fan of the actual action dropdown. I would prefer some button on the top bar (that is always empty).

On php side it could be implemented splitting current `actions` method in `staticActions` and `instanceActions`.

**Comment by tylernathanreed** [comment]
@alberto-bottarini I've thought about adding a "Context Menu" of sorts, which would appear in the application header.

However, since detail pages can have an index for a related resource, you would have the problem of only being able to use the "static" actions on the index landing page, and not within the detail page.

Perhaps that's acceptable, but I imagine wanting the ability to have a "static" action that could appear in both contexts (globally and filtered via relationship).

One of the packages I'm currently working on replaces the resource row actions with an action gearbox. I was thinking about possibly replacing the native action selector with a gearbox as well, which would allow for the ability of "static" actions (since I could make it always be visible), but additionally solve for another issue: [#752](https://github.com/laravel/nova-issues/issues/752), which would allow for action grouping, as well as adding individual actions (like links to other pages or something, since that's also not currently doable).

Just as a proof of concept, here's a screenshot from my current environment:

https://www.dropbox.com/s/6lvv14hqp3rqvmc/Action%20Gearbox.png?dl=0

**Comment by alberto-bottarini** [comment]
Imho, being a "static" action, is not needed on relationship scope view. It's an action that does not require any sort of pre-filters to be executed.

I don't get the point of your screenshot. On that, actions are triggerable on a specific instance.

**Comment by tylernathanreed** [comment]
@alberto-bottarini My screenshot was just an example of what I _currently_ have.

I planned on having a similar gearbox at the top of the index, which could contain static actions like what you're suggesting.

**Comment by MiniCodeMonkey** [comment]
For anyone looking for how to do this now. https://nova.laravel.com/docs/3.0/actions/registering-actions.html#standalone-actions
