### ISSUE TITLE
Make top bar optionally fixed

### ISSUE THREAD

**Issue by Jam0r85** [laravel/nova-issues#1289]
Make the top bar (search, user dropdown) fixed to the top of the screen.

The global search is a must have feature however having to scroll to the top of long pages each time to use it can be frustrating.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

I think this is a decent idea by the way, but am worried about the reduction in vertical space on smaller displays, so going to give it some thought before we do it.

**Comment by Jam0r85** [comment]
No worries, knew it would be closed, could be an idea for the future.
