### ISSUE TITLE
Partition metric not ordered

### ISSUE THREAD

**Issue by parasume** [laravel/nova-issues#130]
Using Nova Version: 1.0.4

When there are multiple labels / group by values for a partition card, the results are not ordered. It would be helpful if the results are ordered in decreasing order of the aggregate value (count/sum/min/max) or if not by default, expose functionality to do the same.

Here's a screenshot:
<img width="364" alt="screen shot 2018-08-24 at 6 13 40 pm" src="https://user-images.githubusercontent.com/41947088/44585455-0c83d980-a7ca-11e8-98e0-e2bd247006cb.png">

As you can see above, it would be useful if the chart shows the top categories using order by

**Comment by parasume** [comment]
Have created a custom gist for this that works but would be great if we could include this in the Nova package: https://gist.github.com/parasume/4f702d93b92c596f1691d17c65084b4a

Here's a screenshot with the gist:
<img width="365" alt="screen shot 2018-08-24 at 6 54 48 pm" src="https://user-images.githubusercontent.com/41947088/44586999-3c81ab80-a7cf-11e8-89ac-5c9774364f92.png">

**Comment by davidhemphill** [comment]
I would prefer to leave ordering up to the user.

**Comment by ppisecky** [comment]
Just in case anyone is looking for a simple solution the result is returned as `Laravel\Nova\Metrics\PartitionResult` which has a `value` property. The `value` is an array of `['label' => $value]`. So you can sort it using `asort` or `arsort` (for reverse order) while maintaining index association. In fact `asort` is the default function by which `Collection` sort method sorts. So if you wanted to sort in ascending order you could technically do: 

```php
     $partitionResult->value = collect($partitionResult->value)->sort()->all();
```

But I think there's no need to do that since all it does is create a collection and then call `asort` on the items in the array. You can just do that yourself. Here's an example with descending order using `arsort` and custom labels:

```php
    /**
     * Calculate the value of the metric.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return mixed
     */
    public function calculate(Request $request)
    {
        $partitionResult = $this->count($request, Task::class, 'task_type_id')
            ->label(function ($value) {
                return TaskType::find($value)->title;
            });
        
        arsort($partitionResult->value);

        return $partitionResult;
    }
```

**Comment by chimit** [comment]
@davidhemphill it still would be nice to have a built-in way of sorting by aggregates.
