### ISSUE TITLE
How to create custom resource views in laravel-nova ? 

### ISSUE THREAD

**Issue by NishantSoni** [laravel/nova-issues#1322]
- I have created an "Resource" (for "Invoice" Model), and i want to customise its "create & update" page instead of nova's default.

- Is there any way to customise it ?

- I have tried custom "nova:tool", but i want to customise only create & update page.

- I have also tried this package - "digitalcloud/nova-custom-views" , but i think its not good solution.

- is there any other way to do this ?

- Or custom "nova:tool" is only the solution ?

Its a blocker for me, please help me to solve this, thanks !

**Comment by karlozadro** [comment]
It looks like there's no way to do it out of the box. Using the [Nova Custom Views](https://github.com/DigitalCloud/nova-custom-views) package seems to be the only way to handle it for the time being. Setup is a _little_ wonky, but it works well once you get it configured. I've been using it for a while now and haven't had any big issues with it. What issues have you had with it?

P.S. It would be really nice to see something like this integrated into core, because if Nova ever decides to update the way they handle routing, all of my custom views would break 😬

**Comment by NishantSoni** [comment]
Hi @karlozadro , 

i used [Custom nova views](https://github.com/DigitalCloud/nova-custom-views) package.  
I am getting following error while compiling assets by ( npm run watch )

```
ERROR in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/views/Create.vue
Module not found: Error: Can't resolve '@nova/views/Create' in '/app/resources/js/views'
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/views/Create.vue 4:0-48
 @ ./resources/js/views/Create.vue
 @ ./resources/js/views ^\.\/.*$
 @ ./resources/js/views.js
 @ multi ./resources/js/views.js ./resources/sass/views.scss
```

### i did in this way: 

```
php artisan nova:views purchases create
cd nova-components/views/purchasees
npm install
npm run dev/watch

```

You have any suggestion for this ?

**Comment by karlozadro** [comment]
@NishantSoni 

So it looks like the problem you're having is that webpack can't find the file being referenced as `'@nova/views/Create`. 

If you look at your webpack configuration file at `nova-components/views/purchases/webpack.min.js` you'll notice that `@nova` is an alias for `__dirname, '../../../vendor/laravel/nova/resources/js/')`.

If you look at your custom `Create.vue` you should see an import statement that looks something like `import ResourceCreate from '@nova/views/Create'`. What's happening is that when webpack tries to compile your custom `Create.vue`, it's replacing the `@nova` alias with it's actual value (listed in your webpack.min.js file).

I'm assuming you have a different file structure than what the Custom Nova Views package is expecting, and that's why you're seeing the "Module not found" error. 

You can fix in two different ways:
1. Fix the `@nova` alias within your `nova-components/views/purchases/webpack.min.js` file to correctly point to the `/nova/resources/js/` (yours might be in the `vendor` directory if you installed nova using composer, or in a top level `nova` directory if you installed it from a zip file).
2. Stop using the `@nova` alias altogether and change the `import ResourceCreate from '@nova/views/Create'` statement in your custom `Create.vue` to directly reference the default nova Create view (it would probably look something like `import ResourceCreate from '../../../../vendor/laravel/nova/resources/js/views/Create'`

**Comment by davidhemphill** [comment]
These views aren't intended to be customized out-of-the-box and we don't really plan on supporting it at this time. If you can list your issues with the current implementation we can take a look and see if there's anything we could improve. 👍

**Comment by Pamposgsk** [comment]
> @NishantSoni
> 
> So it looks like the problem you're having is that webpack can't find the file being referenced as `'@nova/views/Create`.
> 
> If you look at your webpack configuration file at `nova-components/views/purchases/webpack.min.js` you'll notice that `@nova` is an alias for `__dirname, '../../../vendor/laravel/nova/resources/js/'`.
> 
> If you look at your custom `Create.vue` you should see an import statement that looks something like `import ResourceCreate from '@nova/views/Create'`. What's happening is that when webpack tries to compile your custom `Create.vue`, it's replacing the `@nova` alias with its actual value (listed in your webpack.min.js file).
> 
> I'm assuming you have a different file structure than what the Custom Nova Views package is expecting, and that's why you're seeing the "Module not found" error.
> 
> You can fix the error in two different ways:
> 
> 1. Fix the `@nova` alias within your `nova-components/views/purchases/webpack.min.js` file to correctly point to the `/nova/resources/js/` directory (yours might be in the `vendor` directory if you installed nova using composer, or in a top level `nova` directory if you installed it from a zip file).
> 2. Stop using the `@nova` alias altogether and change the `import ResourceCreate from '@nova/views/Create'` statement in your custom `Create.vue` to directly reference the default nova Create view (it would probably look something like `import ResourceCreate from '../../../../vendor/laravel/nova/resources/js/views/Create'`

hi,
i install laravel nove from zip.
What is the correct path to follow?
Currently i disable @nova alias and typed the following:
import ResourceDetail from '../../../../nova/resources/js/views/Detail' for the detail view 
Unfortunately its not working.
Could you please give me instructions?

**Comment by freshway** [comment]
> These views aren't intended to be customized out-of-the-box and we don't really plan on supporting it at this time. If you can list your issues with the current implementation we can take a look and see if there's anything we could improve.

Hi.

I think that it would be really important to allow overwriting labels (header and buttons) and their visibility in the form of each resource.

There are many situations in which the actions and purpose of the forms (and their visibility) must be indicated more user friendly.

For example:
I do not want that in a habitual way it can be allowed to create a second resource from a creation form.

I can explain more situations and if it is necessary to open another issue to request features.

Thanks for your great work

**Comment by DaniloMV** [comment]
> These views aren't intended to be customized out-of-the-box and we don't really plan on supporting it at this time. If you can list your issues with the current implementation we can take a look and see if there's anything we could improve. 👍

They would help us a lot if they could customize the Resource index.

To be able to change the call to a custom view of Creation and Update.

An example would be to create a more dynamic and friendly invoice.

How can we customize?

**Comment by Dontorpedo** [comment]
it would be enough to have the ability to customize the create/update/detail view links, so one could link to a custom tool.. instead of rebuilding everything just to customize index.. or so.. lol
