### ISSUE TITLE
id should not be searchable without setup

### ISSUE THREAD

**Issue by jarda256sparktech** [laravel/nova-issues#1339]
- Laravel Version: 5.7.25
- Nova Version: 1.3.1
- PHP Version: 7.1

### Description:
If you have some nova resource and $search property set to ['reference','name']. Id(primary key) should not be searched even if integer is in search field.

ApplySearch method should contain check if key is in searchableColumns().

```
protected static function applySearch($query, $search)
    {
        return $query->where(function ($query) use ($search) {
            if (is_numeric($search) && in_array($query->getModel()->getKeyType(), ['int', 'integer']) && in_array($query->getModel()->getKeyType(),static::searchableColumns())) {
                $query->orWhere($query->getModel()->getQualifiedKeyName(), $search);
            }

            $model = $query->getModel();

            $connectionType = $query->getModel()->getConnection()->getDriverName();

            $likeOperator = $connectionType == 'pgsql' ? 'ilike' : 'like';

            foreach (static::searchableColumns() as $column) {
                $query->orWhere($model->qualifyColumn($column), $likeOperator, '%'.$search.'%');
            }
        });
    }
```

**Comment by davidhemphill** [comment]
Searching by ID is a feature we want included by default regardless of the other specified columns. Also removing this would be a breaking change, which we're not interested in introducing at this time.

**Comment by shane-smith** [comment]
This is the main thing that has irritated me since I first started using Nova. I updated again today hoping that this was fixed, because it feels so much like a bug. The **official documentation** implies that the ID field can be easily overridden:

> To define which resource fields are searchable, you may assign an array of database columns in the search property of your resource class. **This includes id column by default, but you may override it to your needs:**
https://nova.laravel.com/docs/2.0/search/global-search.html#searchable-columns

This implies that specifying the search property will override the default, which is the ‘id’ field … not append to it. However what it actually does is just append the columns I specify and keep the ID field, as mentioned in the comments above. So it’s not consistent with the documentation.

@davidhemphill - if you feel strongly that the behaviour should remain this way, may I please suggest:

- Documentation should be updated to reflect this (as mentioned above, it’s currently implying otherwise)
- Documentation should include an example of how we can explicitly remove the ID column in our own apps, if possible. Perhaps by overriding `applySearch`? As this is something I’ve wanted to do for a very long time, and I’ve seen others like @jarda256sparktech make similar comments.

**Comment by davi5e** [comment]
Is there a way to indicate that the ID should not be globally searchable?

Is the breaking change related to the global aspect of the global search bar or just related to the model?

I would think this would go a long to alleviate the issue of typing some meaningful number and getting a bunch of unrelated matches...

**Comment by crynobone** [comment]
@davi5e https://github.com/laravel/nova-issues/issues/2102#issuecomment-778767901

**Comment by davi5e** [comment]
The wonders of resuscitating an old thread and finding out the solution was implemented! 

Thank you for the speedy reply @crynobone

**Comment by deffjay** [comment]
Here's my challenge of having the ID forced when searching against a Resource: I am searching for 'Winter 2024' within my resource. It's returning me all of the rows where the table ID has 2024 in it before any of the desired name based searches. 

So:
20241
20242
20243
....

Are matching before anything named Winter 2024. And because there are so many records that match based on ID, I have to go paging to find the content.

Hoping there might be some new thoughts on resurrecting this.

**Comment by crynobone** [comment]
Hey there,

Unfortunately, we don't support this version of the library anymore. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
