### ISSUE TITLE
Can't use scout/algoia indpendent of nova use

### ISSUE THREAD

**Issue by cjf** [laravel/nova-issues#1349]
- Laravel Version: #.#.#
v5.7.25
- Nova Version: #.#.#
v1.3.1
- PHP Version: #.#
7.3

### Description:
Here's the setup, I have a model, call it Page.  I use nova to edit Page objects.  I uses scout + algolia to manage the search-ability of this Page content on an external site.  That is, scout is hooked up in this laravel project and pushes Page data to algolia.  This algolia index is used on another site for search.

Part of this functionality is being able to remove a given Page from the search results.  In past projects, this code in the model class handled that functionality...

```
protected static function boot()
    {
        parent::boot();

        static::saved(function ($model) {
            if ($model->is_draft == true) {
                $model->unsearchable();
            }
        });

        static::updated(function ($model) {
            if ($model->is_draft == true) {
                $model->unsearchable();
            }
        });
    }
```

This still works, but not it also removes it from nova's search capability.  As far as I know, it is impossible to only make a model unsearchable on a specific index.   This seems to be a bug.

**Comment by cjf** [comment]
As a follow up, is it possible to "use Searchable" on models and still have nova just do it's default search using the database tables?

**Comment by WouterFlorijn** [comment]
Yes, this is annoying for me as well. I'm using Scout with Elasticsearch. The data I push to Elasticsearch is very specific and not meant for general searches at all, so there's no reason to have Nova go through Elasticsearch.

From an admin perspective, I don't think it makes much sense either to have the Scout integration as the default. As an admin, generally you want to perform very specific searches with exact matching (except for case). Using Scout should be optional instead of default imo.

**Comment by WouterFlorijn** [comment]
@cjf looking at the `Laravel\Nova\Resource` class, I found that the `usesScout` method determines whether or not Scout should be used for search. So in my Nova resources, I simply override this method:

```
public static function usesScout()
{
    return false;
}
```

Now the resources use regular search.

I still think my point stands though, and at least this possibility should be documented and changed such that you can simply add a `$usesScout` property on the resource instead of overriding a method.

**Comment by cjf** [comment]
Thanks for the tip.  That definitely helps.  I second the comments in your last paragragh.

**Comment by davidhemphill** [comment]
Maybe it shouldn't be default, but changing it at this point would be a breaking change we'd implement in the next Nova series. So probably won't see a change until then. Overloading `usesScout` in your base resource class is the way to go here.
