### ISSUE TITLE
Error saving Resource with a non-integer primary key

### ISSUE THREAD

**Issue by carnevalle** [laravel/nova-issues#141]
Nova version: v1.0.5

I have a ressource which doesn't have an auto-incrementing primary key. When I try to save the ressource in Nova I get the following error

<img width="1348" alt="skaermbillede 2018-08-24 kl 16 32 41" src="https://user-images.githubusercontent.com/54747/44590439-7943a780-a7bb-11e8-83f0-87c2a36d7d84.png">

The Model has the following configuration.
`
    protected $primaryKey = 'barcode';
    public $incrementing = false;
    protected $keyType = 'string';
`

I think I'll solve the issue by adding an auto-incrementing primary key, but I guess it us still a bug?

**Comment by m2de** [comment]
I encountered the same issue when trying to use a primary key of type string.

**Comment by m2de** [comment]
As a temporary work-around I changed `actionable_id`, `target_id` and `model_id` in `action_events` table which now allows me to save the record. I am unsure of what side-effects this may have caused though (if any).

**Comment by geodeveloper** [comment]
Converting those fields to `varchar(255)` goes away the error but it's not an ideal solution, not optimized for queries. Some side effects I've encountered is when using `Actions`, for each action triggered there is some sort of "cleanup" Nova does before inserting a new log into `action_events`.

Sometimes it gives this error: ```SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: 'stringvalue' (SQL: delete from `action_events` where `actionable_id` = 2 and `actionable_type` = App\User and `id` not in (select `id` from (select `id` from `action_events` where `actionable_id` = 2 and `actionable_type` = App\User order by `id` desc limit 25) as `action_events_temp`)```

**Comment by guru4vedi** [comment]
I am having this issue with a non-integer (string) primary key in my `Currency` model. Admin user should be able to enter a code while created new resource. Not sure if this is currently possible.

```
            Text::make('Code', 'code')
                ->sortable()
                ->rules('required', 'max:3'),
```

**Comment by tjmckenzie** [comment]
Just came across this as well. My resource uses a custom `$primaryKey` of a string type, and I am unable to preforms actions on this Resource.

**Comment by webhealer** [comment]
I have same problem when using Mongodb collection. Also have problem with primary key on forms. The only way to fix this, to edit action_events field types. It would be good if there is an option to disable action_events for specific resources.

**Comment by emotality** [comment]
So no answer? 😢

**Comment by stoutZero** [comment]
for me, a working non-solution would be to modify the action source table to include an integer id, then add a unique constraint key for the previous non-integer primary key...

it's not great, but it should work for trivial tables such as settings...

for non-trivials, BIGINT supports up to `1.84467441e19 - 1` unique rows...

**Comment by davidhemphill** [comment]
After a long think, we've decided this isn't going to be natively supported. You should be able to export Nova's migrations and customize them to be `VARCHAR` types if your application needs them.

**Comment by pylebecq** [comment]
For people still trying to figure it out, without having to use migrations and changing column types, I managed to fix it using a model observer.

This is an example for Spark Announcements that I want to manage using Nova. Announcements use UUID as their primary key.

```php
<?php

namespace App\Observers;

use Laravel\Nova\Actions\ActionEvent;
use Laravel\Spark\Announcement;

class ActionEventObserver
{
    public function creating(ActionEvent $actionEvent)
    {
        if ($actionEvent->model_type === Announcement::class) {
            return false;
        }

        return true;
    }
}
```

And somewhere in my `AppServiceProvider`:

```php
\Laravel\Nova\Actions\ActionEvent::observe(\App\Observers\ActionEventObserver::class);
```

This allows me to create an announcement without any issue, and I'm also able to edit it.
The only issue I have is on the deletion. An error is showing up in Nova, but the announcement is still correctly deleted. It's weird but I think I cannot fix it using a model observer because the insert of the  ActionEvent is done differently.

In `ResourceStoreController.php`, used when creating a resource, it's done this way:

```php
ActionEvent::forResourceCreate($request->user(), $model)->save();
```

In `ResourceDestroyController.php`, used when deleting a resource, it's done that way:

```php
DB::table('action_events')->insert(
    ActionEvent::forResourceDelete($request->user(), collect([$model]))
        ->map->getAttributes()->all()
);
```

This does not seem to trigger the model observer.

@davidhemphill Do you think you could rewrite the ActionEvent creation in all controllers as it is written in `ResourceStoreController.php` in order to be able to trigger the model observer? That would fix the issue by giving a way to avoid the creation of the ActionEvent resulting in the original error.

**Comment by bdteo** [comment]
It must be supported. Many projects use UUIDs instead of IDs in order to prevent users guessing about the quantities of given entities. 

People pay to use Laravel Nova. It's not something that you can ignore. Without full UUIDs support Nova is not suitable out of the box for at least 1/3 of the projects.

I am not saying that it is impossible to modify Nova so you can use UUIDs the way you like but IMHO failing to provide full UUIDs support out of the box is the biggest marketing failure of Nova.

**Comment by WasserEsser** [comment]
Using non-integer primary keys are a feature of laravel but are not going to be supported by a paid product for laravel from the creators of laravel?

**Comment by jbrooksuk** [comment]
> Using non-integer primary keys is a feature of laravel but is not going to be supported by a paid product for laravel from the creators of laravel?

As per @davidhemphill's reply above:

> You should be able to export Nova's migrations and customize them to be VARCHAR types if your application needs them.

**Comment by WasserEsser** [comment]
@jbrooksuk I'm fully aware of the ways one can fix this yourself, my comment is geared towards official support.

**Comment by jbrooksuk** [comment]
It's officially in the way that Laravel does, we provide "typical" defaults, but you can change this to your needs.

**Comment by cch504** [comment]
I'm using a uuid with some of my models and I can confirm this issue.

I seemed to have fixed the issue by modifying the prune method in  Laravel\Nova\Actions\ActionEvent.php

```php
   /**
     * Prune the action events for the given types.
     *
     * @param  \Illuminate\Support\Collection  $models
     * @param  int  $limit
     */
    public static function prune($models, $limit = 25)
    {
        $models->each(function ($model) use ($limit) {
            static::where('actionable_id',  (string) $model['actionable_id'])
                ->where('actionable_type', $model['actionable_type'])
                ->whereNotIn('id', function ($query) use ($model, $limit) {
                    $query->select('id')->fromSub(
                        static::select('id')->orderBy('id', 'desc')
                                ->where('actionable_id', (string) $model['actionable_id'])
                                ->where('actionable_type', $model['actionable_type'])
                                ->limit($limit)->toBase(),
                        'action_events_temp'
                    );
                })->delete();
        });
    }
```

I just casted the model actionable_id to a string. I know this is not ideal by any means and only works for standard installations (not with composer).

Hope this helps someone.

**Comment by rasmuscnielsen** [comment]
@cch504 This seems to fix the pruning of old records that happens when creating new ActionEvents.
Unfortunately it's not only place that the issue shows. Also when deleting models the issue may occur when deleting related actions:

**ResourceDestroyController**

```php
public function handle(DeleteResourceRequest $request)
{
    $request->chunks(150, function ($models) use ($request) {
        $models->each(function ($model) use ($request) {
            $this->deleteFields($request, $model);

            if (in_array(Actionable::class, class_uses_recursive($model))) {
                $model->actions()->delete(); // <--- This fails too
            }

            $model->delete();

            tap(Nova::actionEvent(), function ($actionEvent) use ($model, $request) {
                DB::connection($actionEvent->getConnectionName())->table('action_events')->insert(
                    $actionEvent->forResourceDelete($request->user(), collect([$model]))
                        ->map->getAttributes()->all()
                );
            });
        });
    });

    // ...
}
``` 

The more I dig into it, the more it seems like a possible Laravel / MySQL issue when having morph relations including models of different key-types.
I'm unsure how to ensure it doesn't happen, except using same key-type on all models and remove Actionable on the outliers (?) 

____

It would be awesome if Laravel could use the `$casts` property defined on the model to actually cast the key to the specified type, thereby ensuring that the `actionable_id` was always a string even when a integer is given. At this point that does not seem to happen.

Custom ActionEvent implementation
```php
class ActionEvent extends \Laravel\Nova\Actions\ActionEvent
{
    protected $casts = [
        'original' => 'array',
        'changes' => 'array',
        'actionable_id' => 'string',
    ];
}
```

Resulting DB query of  `$video->actions()->delete()`:
![image](https://user-images.githubusercontent.com/8465957/84383018-cfc9e200-abeb-11ea-9192-1fbbb29f89da.png)

The video key is still a integer thus throwing MySQL error: `Truncated incorrect DOUBLE value: '4c22......`

**Comment by raisonon** [comment]
I refactored my code so I now have id as primary instead of uuid. I then generate manually the uuid rather than using the default uuid package trait to manage them.

Previously in my controllers I was using Dependency Injection to automagically provide the specific model and now I just pass the specific UUID and then use the following eloquent query to get the model:

`$project->where('uuid', $uuid)->firstOrFail()`

This works and I'm now going through my code to refactor according to this pattern so it works with Nova.

I don't follow the logic above about why UUIDs are not supported in Nova. Feels a bit clumsy to have to have an ID and UUID just to satisfy the constraints of Nova, but I don't profess to totally understand the complexities of it. Ideally this is better supported in the future, but just posting in case others want insight into how I resolved this.

**Comment by kosmonowt** [comment]
Having this issue here as well...
Which solution shall we follow?
Could there be a good patch anytime soon available for everyone?
I mean, this is around for two years now.

**Comment by AdrianwithaW** [comment]
Ran into this also and even with the ID fields as `VARCHAR` I couldn't suppress the error so my Action wouldn't run. Not particularly interested in the logging feature so used `->withoutActionEvents()` on the action to avoid error as noted in [this pull request](https://github.com/laravel/nova-docs/pull/133).

**Comment by indigoram89** [comment]
I had this problem with deleting the action event.

And I solve the problem when I created a custom ActionResource and ActionEvent like this:

It is nova config file:

<img width="700" alt="Screenshot 2020-09-15 at 17 56 37" src="https://user-images.githubusercontent.com/10687211/93227249-d896fa80-f77c-11ea-86b9-efd7c883ba24.png">

It is my new ActionResource:

<img width="669" alt="Screenshot 2020-09-15 at 17 57 32" src="https://user-images.githubusercontent.com/10687211/93227377-f3696f00-f77c-11ea-87b4-f789c54667e5.png">

And this is my ActionEvent (Model):

<img width="740" alt="Screenshot 2020-09-15 at 17 58 13" src="https://user-images.githubusercontent.com/10687211/93227456-0c722000-f77d-11ea-9271-4d6bbb31dbcb.png">

I hope it helps you, guys.

**Comment by benlumley** [comment]
The above worked for me. 

Here's the two files as text, rather than an image:

```
<?php

namespace App\Nova;

use App\Models\ActionEvent;
use Laravel\Nova\Actions\ActionResource as BaseActionResource;


class ActionResource extends BaseActionResource
{

    public static $model = ActionEvent::class;

}

```

```
<?php

namespace App\Models;

use Laravel\Nova\Actions\ActionEvent as BaseActionEvent;

class ActionEvent extends BaseActionEvent
{

    public static function prune($models, $limit = 25)
    {
        $models = $models->map(function ($model) {
            $model['actionable_id'] = (string)$model['actionable_id'];
            $model['target_id']     = (string)$model['target_id'];
            $model['model_id']      = (string)$model['model_id'];

            return $model;
        });

        return parent::prune($models, $limit);
    }

}
```

**Comment by newms87** [comment]
> After a long think, we've decided this isn't going to be natively supported. You should be able to export Nova's migrations and customize them to be `VARCHAR` types if your application needs them.

That is a very dumb decision. There are very simple ways to support this. It is definitely something you should do if you want to be selling a product. I will not buy Nova.

**Comment by usamamuneerchaudhary** [comment]
Still facing the same error, no above solution worked.
