### ISSUE TITLE
ResourceId isn't available in Custom Card

### ISSUE THREAD

**Issue by thomasdominic** [laravel/nova-issues#1456]
- Laravel Version: 5.8
- Nova Version: 1.3
- PHP Version: 7.2
- Operating System and Version: Ubuntu 18.04

### Description:
On a custom card only show on details, the resourceId isn't available.
I can not understand how something so important is not possible in a custom card.
Without this resourceId, the custom cards lose all their interest, except to make a card that gives the time ....

NO `request()->resourceId` or `request()->route('resourceId')`
```
class CountRelationshipsPerProduct extends Card
{
    /**
     * The width of the card (1/3, 1/2, or full).
     *
     * @var string
     */
    public $width = '1/3';

    /**
     * @return CountRelationshipsPerProduct
     */
    public function withCount()
    {
        $current_product = ????; ///// HERE
        return $this->withMeta([
            'my_count' => MyModel::where('product_id', $current_product)->count(),
        ]);
    }

    /**
     * Get the component name for the element.
     *
     * @return string
     */
    public function component()
    {
        return 'count-relationships-per-product';
    }
}
```

### Steps To Reproduce:
- Create a custom card
- Show only on details
- Don't find the resourceId

**Comment by anderly** [comment]
@thomasdominic try `$request->findResourceOrFail()`. That should return you the model instance for the request if you're on a resource detail screen.

**Comment by anderly** [comment]
If you're wanting to show a count, a simple value metric `php artisan nova:value CountRelationshipsPerProduct ` might be better since it can automatically hand you the model for the detail resource in the `calculate` method. If you don't want date ranges, you can simply return `[]` from the `ranges` method.

For instance, here's a simple Count value metric I have:

```php
class UnitOfMeasureItemUsage extends Value
{

    /**
     * The displayable name of the metric.
     *
     * @var string
     */
    public $name = 'Item Usage';

    public $width = '1/3';

    /**
     * Calculate the value of the metric.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return mixed
     */
    public function calculate(Request $request, UnitOfMeasure $unitOfMeasure)
    {
        $result = $this->result($unitOfMeasure->items()->count());
    }

    /**
     * Get the ranges available for the metric.
     *
     * @return array
     */
    public function ranges()
    {
        return [];
    }

    /**
     * Determine for how many minutes the metric should be cached.
     *
     * @return  \DateTimeInterface|\DateInterval|float|int
     */
    public function cacheFor()
    {
        // return now()->addMinutes(5);
    }

    /**
     * Get the URI key for the metric.
     *
     * @return string
     */
    public function uriKey()
    {
        return 'unit-of-measure-item-usage';
    }
}
```

**Comment by thomasdominic** [comment]
Thanks for your answer.
I can't use Metric, because I wish display several values on my Card and other information about the selected resource (for example created_at of resource and all relationship count)

If I do that (with `findResourceOrFail()`) I have got an error
```
class CountRelationshipsPerProduct extends Card
{
    /**
     * The width of the card (1/3, 1/2, or full).
     *
     * @var string
     */
    public $width = '1/3';

    /**
     * @return CountRelationshipsPerProduct
     */
    public function withCount()
    {
        \Log::debug(request()->findResourceOrFail());
        $current_product = ????; ///// HERE
        return $this->withMeta([
            'my_count' => MyModel::where('product_id', $current_product)->count(),
        ]);
    }

    /**
     * Get the component name for the element.
     *
     * @return string
     */
    public function component()
    {
        return 'count-relationships-per-product';
    }
}

```
Method Illuminate\Http\Request::findResourceOrFail does not exist

It's a function of NovaRequest and I haven't this object

**Comment by anderly** [comment]
@thomasdominic I see. Basic custom cards are just plain components (like the Help component on the dashboard) that are left for you to fill out more advanced functionality.

The Nova metric Vue components are actually what are responsible for calling back to the Nova backend to get the metric values and they pass the resourceId like this code block from `ValueMetric.vue`:

```js
metricEndpoint() {
            const lens = this.lens !== '' ? `/lens/${this.lens}` : ''
            if (this.resourceName && this.resourceId) {
                return `/nova-api/${this.resourceName}${lens}/${this.resourceId}/metrics/${
                    this.card.uriKey
                }`
            } else if (this.resourceName) {
                return `/nova-api/${this.resourceName}${lens}/metrics/${this.card.uriKey}`
            } else {
                return `/nova-api/metrics/${this.card.uriKey}`
            }
        },
```

To accomplish something similar with a custom card, you'd need to define some [custom routes](https://nova.laravel.com/docs/2.0/customization/cards.html#routing) for your card and then have your card Vue component call those routes with the the resourceName/resourceId, etc. so that you could retrieve the resourceId as part of the request. That would allow you to return your multiple values you mentioned, created_at and relationship information scoped to the current resource.

Have a look at the Metric components (ValueMetric.vue, etc.) because they are basically cards that can fetch data. So, you can base most of your code of what they're doing.

**Comment by thomasdominic** [comment]
OH, I find it so complicated.
I really think it could fix that with a dependency injection.
it's a lot of going back and http request

**Comment by anderly** [comment]
When you first visit a resource detail screen, it makes a request to the resources `/nova-api/{resourceName}/cards` endpoint which returns the configured cards (this includes metrics, too).

However, the metric components then make subsequent requests to `/nova-api/{resourceName}/{resourceId}/metrics/{metricName}` for each of your metric cards.

That subsequent step is specific to metric components. Cards don't do it by default because a card could just be plain html, etc. If you need resource-specific data there, then you need a custom set of routes and your custom card Vue component would need to call that route (like the metric components do) to get the data.

Your other option is build some custom metric components where you can take full-control over the display and return values.

For an example, I recently built a package to allow metrics to be linkable. You can see an example implementation here: saintsystems/nova-linkable-metrics

**Comment by davidhemphill** [comment]
https://github.com/laravel/nova/commit/f62c3907eef233650f77f25593eb4ea566b285fe should fix this. We'll pass along the `resourceId` to the `/cards` endpoint on Detail views.

**Comment by thomasdominic** [comment]
Thanks you

**Comment by lwitzel** [comment]
@davidhemphill When is that commit getting deployed to production? I've just spent the last 5 hours trying to build a basic card to show a simple resource-specific link, but I'm not familiar with Vue and I'd rather build it on the server side. Sending the resourceId to the /cards endpoint would be really handy...

**Comment by thomasdominic** [comment]
@davidhemphill May we have some visibility on this issue ?

**Comment by judahnator** [comment]
Any updates on this? It would be nice to be able to access the current resource from within the resource `cards()` method. As it is...
```
public function fields(Request $request)
{
  $this->model()->exists; // true when editing/viewing
  $this->model()->getKey(); // works fine as well
}

public function cards(Request $request)
{
  $this->model()->exists; // always false
  $this->model()->getKey(); // always null
}
```

**Comment by riabiy-denis** [comment]
@davidhemphill 
> [laravel/nova@f62c390](https://github.com/laravel/nova/commit/f62c3907eef233650f77f25593eb4ea566b285fe) should fix this. We'll pass along the `resourceId` to the `/cards` endpoint on Detail views.

Could you help on how to use that? 
Since I can't look at the source code, I'm not quite sure on how to use this fix :D 
I'm using the latest Nova (v3) and...any guesses? The issue seems to persist. 

```php
public function cards(Request $request)
{
  $this->model()->exists; // always false
  $this->model()->getKey(); // always null
}
```

**Comment by riabiy-denis** [comment]
> @davidhemphill
> 
> > [laravel/nova@f62c390](https://github.com/laravel/nova/commit/f62c3907eef233650f77f25593eb4ea566b285fe) should fix this. We'll pass along the `resourceId` to the `/cards` endpoint on Detail views.
> 
> Could you help on how to use that?
> Since I can't look at the source code, I'm not quite sure on how to use this fix :D
> I'm using the latest Nova (v3) and...any guesses? The issue seems to persist.
> 
> ```
> public function cards(Request $request)
> {
>   $this->model()->exists; // always false
>   $this->model()->getKey(); // always null
> }
> ```

Feel myself an idiot :D 

In the description of the `Card.vue`

```
// The following props are only available on resource detail cards...
// 'resource',
// 'resourceId',
// 'resourceName',
```
