### ISSUE TITLE
Option to customize the precision when rounding values in a Trend class

### ISSUE THREAD

**Issue by Taronyuu** [laravel/nova-issues#151]
Allow the user to set the precision to round values to in a Trend class. This will allow users to have a graph with values that use decimals. 

Patch file to give an idea how to fix this: 
```diff
diff --git a/Website/nova/src/Metrics/Trend.php b/Website/nova/src/Metrics/Trend.php
index 8b4ecf5..0769dc3 100755
--- a/Website/nova/src/Metrics/Trend.php
+++ b/Website/nova/src/Metrics/Trend.php
@@ -502,7 +502,7 @@ abstract class Trend extends RangedMetric
         $results = array_merge($possibleDateResults, $results->mapWithKeys(function ($result) use ($request, $unit) {
             return [$this->formatAggregateResultDate(
                 $result->date_result, $unit, $request->twelveHourTime === 'true'
-            ) => round($result->aggregate, 0)];
+            ) => round($result->aggregate, $this->getPrecision())];
         })->all());
 
         if (count($results) > $request->range) {
@@ -705,4 +705,14 @@ abstract class Trend extends RangedMetric
                         : __($date->format('F')).' '.$date->format('j').' - '.$date->format('G:i');
         }
     }
+
+    /**
+     * getPrecision function.
+     *
+     * @return int
+     */
+    protected function getPrecision(): int
+    {
+        return 0;
+    }
 }

```

**Comment by drehimself** [comment]
Agree. Maybe have the ability to use computed properties like fields do. As @reganjohnson says, I'm in a situation where I'm summing up a price column in my Orders table, but I can't convert it to dollars (since price is stored in cents).

```php
public function calculate(Request $request)
{
    // can't convert to dollars
    return $this->sum($request, Order::class, 'price');
}
```

I can probably use `return $this->result($sumNow)->previous($sumPrevious);` as an alternative, but lose all the nice date ranges.

**Comment by alexpgates** [comment]
@drehimself Did you happen to come up with a solution for the cents to dollars conversion?

**Comment by drehimself** [comment]
@alexpgates I have not, unfortunately. Let me know if you figure out a (not too hacky) way.

**Comment by drehimself** [comment]
@hotmeteor Thank you! This solution works great.

**Comment by willmkt** [comment]
@hotmeteor how can i get other currencies?

**Comment by RicLeP** [comment]
> 
> 
> @hotmeteor how can i get other currencies?

Instead of `dollars()` use your `prefix()`

`return $this->countByDays($request, User::class)->prefix('£');`

**Comment by RicLeP** [comment]
> 
> ```
> public function calculate(Request $request)
> {
>     return $this->sum($request, Order::class, DB::raw('(price/100)'))->dollars();
> }
> ```

When I do this it’s rounding the result to the nearest pound so 2540 becomes £25

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by zedix** [comment]
Nova Version: 2.4.0

@jbrooksuk 
This issue is still relevant. Today, value metrics sent by `nova-api/metrics` api to front-end are rounded with _zero_ precision.

![image](https://user-images.githubusercontent.com/27975/66769887-8a1b1500-eeb6-11e9-91ae-48488d33195d.png)

In order to achieve the simple result above, we currently must override the `Laravel\Nova\Metrics\Value` class like this:

```php
<?php

namespace App\Nova\Metrics;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Builder;
use Laravel\Nova\Metrics\Value as NovaValue;

class Value extends NovaValue
{
   // This is the protected method to add to allow customization of the `round` precision in aggregate method in derivated classes
    protected function getRoundPrecision()
    {
        return 0;
    }

    /**
     * Return a value result showing the growth of a model over a given time frame.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Database\Eloquent\Builder|string  $model
     * @param  string  $function
     * @param  string|null  $column
     * @param  string|null  $dateColumn
     * @return \Laravel\Nova\Metrics\ValueResult
     */
    protected function aggregate($request, $model, $function, $column = null, $dateColumn = null)
    {
        $query = $model instanceof Builder ? $model : (new $model)->newQuery();

        $column = $column ?? $query->getModel()->getQualifiedKeyName();

        $previousValue = round(with(clone $query)->whereBetween(
            $dateColumn ?? $query->getModel()->getCreatedAtColumn(), $this->previousRange($request->range)
        )->{$function}($column), $this->getRoundPrecision());

        return $this->result(
            round(with(clone $query)->whereBetween(
                $dateColumn ?? $query->getModel()->getCreatedAtColumn(), $this->currentRange($request->range)
            )->{$function}($column), $this->getRoundPrecision())
        )->previous($previousValue);
    }
```

This would be a great addition. The fix is also quite trivial to add.

**Comment by gpressutto5** [comment]
@jbrooksuk I was going to open a new ticket as you suggested, but feature requests are closed by default so I will use this one. laravel/nova#681 should not mention this issue because it changed nothing for Trend metrics. I will create a PR fixing this when I have the time later, but it's as easy as applying the same changes you made on that 681 but to Trend instead of Value.

**Comment by jonasbrenig** [comment]
@gpressutto5 Thank you!!!
