### ISSUE TITLE
Validation still running on readonly fields

### ISSUE THREAD

**Issue by jasonlbeggs** [laravel/nova-issues#1546]
- Laravel Version: 5.7.28
- Nova Version: 2.0.1
- PHP Version: 7.2.4
- Operating System and Version: Mac OSX High Sierra
- Browser type and version: Chrome 73

### Description:
When a form with a readonly field is submitted in Nova, the validation still seems to be running on the readonly field. We have a form than anonymizes the email field in the `resolveUsing` method, so the form is submitted with "---" in the email input. Even with `->readonly(true)` set on the field, it fails validation because the email field is not a valid email address.

### Steps To Reproduce:
This is the code for the field.
```php
            Text::make('Email')
                ->sortable()
                ->rules('required', 'email', 'max:254')
                ->creationRules('unique:users,email')
                ->updateRules('unique:users,email,{{resourceId}}')
                ->resolveUsing(function ($email) {
                    // returns '---'
                    return $this->anonymize('email', $email);
                })
                ->readonly(true),
```

**Comment by SebastianMueller87** [comment]
The current `readonly`-implementation adds just a `disable`-element-attribute to the field. (front-end)

Docs:
 > [...] which will disable the field's corresponding input:

The field value will still be send to the server. Validation and everything will still be triggered. 

You need to know that because of security. 

If anyone just removes the `disabled="disabled"` element attribute from the DOM, the one is able to change the value and still update it.

**Comment by jasonlbeggs** [comment]
I figured out a work-around for my use case. I think in future versions of Nova, readonly fields might be removed from validation and updates.

**Comment by justindantzer** [comment]
@jasonlbeggs could you share your case and solution? I'd be curious of any alternativs, rather than what I've implemented.

I was running into this issue and modeled a solution off of the suggestion by @SebastianMueller87 

in `\App\Nova\Resource.php` I've added an override for the `fillForUpdate()` method:

```php
public static function fillForUpdate(NovaRequest $request, $model)
{
    $resource = $request->resource();

    if(method_exists($resource, 'filterForUpdate')) {
        $request->replace($resource::filterForUpdate($request, $model));
    }

    return parent::fillForUpdate($request, $model);
}
```

Then in any resource needing filtered fields, I've added the `filterForUpdate()` method, which returns the filtered request input:

```php
public static function filterForUpdate(NovaRequest $request, $model)
{
    return collect($request->except('some', 'readonly', 'fields'))->all();
}
```

**Comment by jasonlbeggs** [comment]
@justindantzer, I actually just ended up using the [canSee()](https://nova.laravel.com/docs/2.0/resources/authorization.html#fields) method instead of readonly and checking to see if the user is updating a model using the `$request->isUpdateOrUpdateAttachedRequest()` method.

```php
Text::make('Name')->sortable()
    ->canSee(function ($request) {
        return ! $request->isUpdateOrUpdateAttachedRequest() 
                  || $request->user()->isAdmin();
    }),
```
