### ISSUE TITLE
BelongtsTo loses her selection when validation errors

### ISSUE THREAD

**Issue by Yannik-Slym** [laravel/nova-issues#1576]
- Laravel Version: 5.8.15
- Nova Version: 2.0.3
- PHP Version: 7.3.4
- Operating System and Version: macOS 10.14.4 
- Browser type and version: Firefox Dev 67b014

### Description:

![image](https://user-images.githubusercontent.com/3316758/57318876-99be5280-70fb-11e9-9dea-4af80e90f03d.png)

After save with validations errors, the BelongsTo loses her selection. 

![image](https://user-images.githubusercontent.com/3316758/57318890-9fb43380-70fb-11e9-82cf-5be134e9863d.png)

**Comment by ppisecky** [comment]
I'm seeing a similar behavior. I've been debugging a field package I'm working on for a few hours because I thought I was doing something wrong. The package injects form fields that represent a separate resource and some of the relation fields would always reset when I passed in validation errors. Then I noticed that the top parent resource via which the create form was opened was clearing as well. So I went to a different create form (where my package isn't being used) and it just seems to be the case that when a validation error occurs somewhere in the form the relation fields reset (seems to be the case for `BelongsTo` and `MorphTo`.


Before submit: 
![image](https://user-images.githubusercontent.com/10659431/57326087-ef026000-710b-11e9-8354-0fdd99d3a680.png)


After submit:
![image](https://user-images.githubusercontent.com/10659431/57326031-cd08dd80-710b-11e9-8b65-d17690d46242.png)

**Comment by ppisecky** [comment]
I've just tried in a form with many relations and it seems to be only broken for **non**-searchable relation fields.

**Comment by ppisecky** [comment]
@InfinityWebMe Have you managed to resolve this issue by any change? Could you possibly provide the list of Nova packages you use to check if we share any that might be causing the problem?

**Comment by InfinityWebMe** [comment]
@ppisecky not yet i will test with a fresh nova installation

**Comment by encomienda** [comment]
same here when submitting belongsto field get's unselected

**Comment by preliot** [comment]
Same here:

Laravel Version: 5.8.18
Nova Version: 2.0.5
PHP Version: 7.2.10
Operating System and Version: Windows 10 (64 bits)
Browser type and version: Chrome 75.0.3770.80 (64 bits)

BelongsTo field looses it's selected value upon saving and validation errors (elsewhere). Will work when 
`->searchable()` is activated.

**Comment by good-system** [comment]
It seems adding this in select-control would fix this issue

<select-control
     ....
        :value="selectedResourceId"
     ....
>

**Comment by renky** [comment]
I can confirm that behaviour on several selection-fields

Code that I use for example:
```
BelongsTo::make(__('Serviceclass'), 'serviceclass', Serviceclass::class)
                ->canSeeWhen('viewPrivateFields', $this)
                ->hideFromIndex(),
```

Can also confirm:
`->searchable()`
solves the issue - but is not my preferred solution there.

**Comment by preliot** [comment]
@renky Saving stil works indeed, it's only in the frontend.

**Comment by jbrooksuk** [comment]
Confirmed in v2.0.10 as well.

**Comment by renky** [comment]
Updated to Nova v2.3.1 now
still have this problem - in which version is it solved?

**Comment by preliot** [comment]
Seems to be fixed in version 2.4.0, no longer seeing the issue.

**Comment by renky** [comment]
ok, updated to v2.4.0 now - still facing the same issue - what do I have to do after update?

I ran npm run development for my whole page, cleared all caches (artisan optimize:clear), and cleared Browsercache  - CTRL+F5

**Comment by preliot** [comment]
Perhaps: 

`php artisan nova:publish`

**Comment by renky** [comment]
shame on me - that's it - now its working. Thanks a lot - maybe it even worked in 2.3 :-(

**Comment by seanareed** [comment]
I'm still having this issue.

- Nova 2.9.2
- Laravel 5.8.36
- I've run `php artisan nova:publish`
- I've run `config:clear`, `cache:clear`, `optimize:clear`
- I've cleared the browser cache and site data 

The `->searchable()` trick seems to only work when attaching a new item, but not when updating an existing attached item.

Any other hints?
