### ISSUE TITLE
Run actions without conditions

### ISSUE THREAD

**Issue by covobo** [laravel/nova-issues#1646]
I'd like to run some actions on all my resource, like "send marketing sms to everybody".
Technically I can do it, but why I have to choose at least one row to see actions control panel?

**Comment by noahlocke** [comment]
@covobo sounds like maybe a [custom tool ](https://nova.laravel.com/docs/2.0/customization/tools.html)would work better for this. The UI is already designed to only apply actions to the selected resource(s), I don't see them changing that.

**Comment by covobo** [comment]
If you like my issue they will redesign it =)
"custom tool" is too difficult way to develop small feature like "send marketing sms to everybody".

**Comment by davidhemphill** [comment]
I'm not opposed to having this, but we wouldn't stick it in the existing actions dropdown. It'd be some sort of "global actions" type function. 

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
