### ISSUE TITLE
Transient field (not stored in DB)

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#168]
Is there a way to define a field that won't be stored in database (like password confirmation for example)?

**Comment by CmdrSharp** [comment]
I'm curious to this as well. Not all fields are necessarily linked to the resource we're updating either. Take something like Spatie's Permissions package. I want the ability to use something like a Select field, pre-populate it with the users current Role, and on update, pass a function that instead of **updating** a direct value, calls a method of a **trait** on the user role (like `$this->assignRole('abc');`). Unless I'm missing something, this is not currently possible?

**Comment by lucasromanojf** [comment]
I figured out a way:

`public static function fill(NovaRequest $request, $model)
    {
        if ($request->input('password_confirmation')) {
            $request->offsetUnset('password_confirmation');
        }

        return parent::fill($request, $model);
    }`

**Comment by lucasromanojf** [comment]
Actually the solution above works when we dont need the fields from the request later in a model observer for example, but if we need them, that cant be done. So in this case I am reopening this ticket.

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.
