### ISSUE TITLE
Hasmanythrough relationship 

### ISSUE THREAD

**Issue by Pamposgsk** [laravel/nova-issues#1683]
Hi,
Do you have a plan to include hasManyThrough relationship.Now it fails on create method.(you can view only)

**Comment by davidhemphill** [comment]
We don't currently have any plans to support this relation type. 

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by davidhemphill** [comment]
I just put in a PR to add this to Nova. Thanks everybody!
