### ISSUE TITLE
Removing `withAuthenticationRoutes()` causes a `Route [nova.logout] not defined.` error

### ISSUE THREAD

**Issue by JonoB** [laravel/nova-issues#1689]
- Laravel Version: 5.8.23
- Nova Version: 2.0.6
- PHP Version: 7.3.1
- Operating System and Version: Homestead, Ubuntu 18.04
- Browser type and version: Chrome
- Reproduction Repository: n/a

### Description:
The `->withAuthenticationRoutes()` method needs to also include the logout route in the view. I don't want my nova to have any login, logout, etc routes. However, if you disable this in the `NovaServiceProvider`, then every nova view will throw a `Route [nova.logout] not defined` error. 

### Steps To Reproduce:
Comment out or remove ->withAuthenticationRoutes() from the `routes()` method in the `NovaServiceProvider`

```
    /**
     * Register the Nova routes.
     *
     * @return void
     */
    protected function routes()
    {
        Nova::routes()
                //->withAuthenticationRoutes()
                //->withPasswordResetRoutes()
                ->register();
    }
```

**Comment by JonoB** [comment]
In the meantime, I have deleted the following block from `resources/views/vendor/nova/partials/user.blade.php` :

```
<dropdown-menu slot="menu" width="200" direction="rtl">
    <ul class="list-reset">
        <li>
            <a href="{{ route('nova.logout') }}" class="block no-underline text-90 hover:bg-30 p-3">
                {{ __('Logout') }}
            </a>
        </li>
    </ul>
</dropdown-menu>
```

**Comment by jbrooksuk** [comment]
I don't believe this is a frequent use-case in which we have time to address it. In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by JonoB** [comment]
I'm not sure that this is a feature request.

I'm also not sure why you would expose `withAuthenticationRoutes()` in the `NovaServiceProvider` if removing it causes the entire app to not work.

I don't really mind if you close this or not, but its clearly a bug.

**Comment by jbrooksuk** [comment]
@JonoB I've flagged this as a feature request, because I think that having Nova run with no authentication routes is a feature change, it's not a bug that we use named routes.

I'm unsure of why `withAuthenticationRoutes` is exposed if it's required, but I'll speak with @davidhemphill about it.

**Comment by leemason** [comment]
+1 on this, the method called `withAuthenticationRoutes` is effectively NOT optional, but implies it through naming.

I too ran into this with a spark app, which already provides auth routes, i don't really want two login routes but not a big deal.

**Comment by mjbnz** [comment]
With a Breeze install, I've modified `user.blade.php` with the following:

```diff
 <dropdown-menu slot="menu" width="200" direction="rtl">
     <ul class="list-reset">
         <li>
-            <a href="{{ route('nova.logout') }}" class="block no-underline text-90 hover:bg-30 p-3">
-                {{ __('Logout') }}
-            </a>
+            <form method="POST" action="{{ route('logout') }}">
+                @csrf
+
+                <a href="route('logout')" class="block no-underline text-90 hover:bg-30 p-3"
+                        onclick="event.preventDefault(); this.closest('form').submit();">
+                    {{ __('Log out') }}
+                </a>
+            </form>
         </li>
     </ul>
 </dropdown-menu>
```

Perhaps both options could be present with a conditional based on whether or not `withAuthenticationRoutes()` was used? I am unsure if the form logout method is more common than a link in other auth frameworks.

Yet another alternative - users can create a `nova.logout` named route alongside the logout route for their auth framework of choice.

Either way, yes, it's cumbersome that not using `withAuthenticationRoutes()` means that there's a Logout link generated within Nova that's inherently broken. A less desirable option that actually resolves the bug is to make the logout link in `user.blade.php` conditional on the usage of the `withAuthenticationRoutes()` method.
