### ISSUE TITLE
Form in edit view empty after update to 2.0.8

### ISSUE THREAD

**Issue by bilobait-balleyer** [laravel/nova-issues#1717]
- Laravel Version: v5.8.27
- Nova Version: v2.0.8
- PHP Version: 7.3.5
- Operating System and Version: Debian
- Browser type and version: Google Chrome

### Description:
The form of a resource in edit view is empty after Update from 2.0.7 to 2.08

Console error:

```
[Vue warn]: Unknown custom element: <form-undefined> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Update> at resources/js/views/Update.vue
       <Root>
```
### Steps To Reproduce:
Update to 2.0.8 and open resource in edit view

### Steps To Fix:
Downgrade to 2.0.7 and everything is fine

**Comment by tpetry** [comment]
Same problem for me. But i do not get any error message or messages anywhere. All nova http requests are working and return the form information but nothing is displayed.

**Comment by bilobait-balleyer** [comment]
After some debugging:

The structure of the response of the Ajax call:

`/nova-api/resource/125/update-fields?editing=true&editMode=update&viaResource=&viaResourceId=&viaRelationship=`

is different from the new version. The JSON array has NOT the same structure!

**Comment by gaabora** [comment]
App\Providers\NovaServiceProvider
```
public function tools()
    {
        $tools = [
            // \ChrisWare\NovaBreadcrumbs\NovaBreadcrumbs::make(), // this breaks forms for me
```

**Comment by davidhemphill** [comment]
Update your Nova assets using `php artisan nova:publish --force`.

If you're using any 3rd-party fields, make sure they're compatible with the latest versions of Nova.

**Comment by renky** [comment]
Thanks david - this helped...
but honestly: I updated from v2.0.3 => v2.0.9 today and this is the second breaking change that i got with this update - why are such changes made with a minor update? I could understand it when switching to Nova 3 - or even if we switch to Nova 2.1 I could understand such changes... But to be honest, it is a payed software - and I expect after a minor update in the third version part, that it runs smooth afterwards without having additional effort on my side like re-publishing assets or changing routes (nova.login was removed also) - republishing also brings additional effort, since I have to re-create my changes to this assets.
That's not really customer friendly

**Comment by davidhemphill** [comment]
**These aren't breaking changes.** They are bug fixes and additions. If you can't be bothered to update your software (it takes literally 10 seconds to publish the new assets), feel free to contact support for a refund.

If you notice an issue with the create resource buttons, feel free to open an issue and we will look into it.
