### ISSUE TITLE
The requested package laravel/nova could not be found in any version

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#1755]
When I add the "laravel/nova" pakages as described in the documentation: 

**Next, add laravel/nova to the require section of your composer.json file:**

`"require": {
    "php": "^7.1.3",
    "fideloper/proxy": "^4.0",
    "laravel/framework": "5.6.*",
    "laravel/nova": "*"
}`

I'm receiving this error during a composer update.

<img width="833" alt="image" src="https://user-images.githubusercontent.com/10268813/44506618-866f7200-a6a7-11e8-9152-b333099add78.png">

**Comment by kariachintan** [comment]
Try adding it like this. It fixed for me.

`"minimum-stability": "dev",
    "prefer-stable": true,
    "repositories": {
        "laravel/nova": {
            "type": "path",
            "url": "./nova"
        }
    }`

**Comment by ARZI87** [comment]
Hello, 
one additional point to take into consideration is the composer repository path that you indicate and the location where you unzip Nova's package. As per Laravel's documentation, you should:

1. create a new directory 'nova' in root directory of your project.
2. unzip nova's package files into 'nova' directory + modify the composer.json.

However, for me the error was occurring because after unzipping in './nova', the actual package was placed in sub-folder './nova/laravel-nova-{key}'. So for me it was enough to modify composer.json :
 
"repositories": [
    {
        "type": "path",
        "url": "./nova/laravel-nova-{key}"
    }
],

{key} is automatically generated by Laravel Nova and will be unique for each developer.

Hope this helps!

**Comment by slowdream** [comment]
add to composer file
`"repositories": [
    {
        "type": "composer",
        "url": "https://nova.laravel.com"
    }
],`

**Comment by anthonyPlexuss** [comment]
> Hello,
> one additional point to take into consideration is the composer repository path that you indicate and the location where you unzip Nova's package. As per Laravel's documentation, you should:
> 
> 1. create a new directory 'nova' in root directory of your project.
> 2. unzip nova's package files into 'nova' directory + modify the composer.json.
> 
> However, for me the error was occurring because after unzipping in './nova', the actual package was placed in sub-folder './nova/laravel-nova-{key}'. So for me it was enough to modify composer.json :
> 
> "repositories": [
> {
> "type": "path",
> "url": "./nova/laravel-nova-{key}"
> }
> ],
> 
> {key} is automatically generated by Laravel Nova and will be unique for each developer.
> 
> Hope this helps!

This one worked for me!

**Comment by m-usmananwar** [comment]
Hi I've cloned  Laravel Nova Project But I'm facing an error when I'm running composer install/update it gives me an error.

In PathRepository.php line 163:
The `url` supplied for the path (./modules/core) repository does not exist
  
Even this (.modules/core) does not exist in my project
