### ISSUE TITLE
Bug in ManyToMany on same resource

### ISSUE THREAD

**Issue by nysso** [laravel/nova-issues#1780]
- Laravel Version: 5.8.28
- Nova Version: 2.0.6
- PHP Version: 7.3.1
- Operating System and Version: Windows 10 build 1903 version 18362.175
- Browser type and version: Google Chrome 75.0.3770.100 64bits

### Description:
When trying to attach a resource to the same resource via a ManyToMany relation, the field on the attach UI doesn't get the **_required_** rule, and when clicking Attach without selecting a resource we get an SQL exception:

**SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'controlled_role_id' cannot be null (SQL: insert into `controlled_roles` (`role_id`, `controlled_role_id`, `created_at`, `updated_at`) values (4, ?, 2019-07-28 10:44:18, 2019-07-28 10:44:18))**

Explanation/Example:
a Role model has controlledRoles (on himself):

    public function controlledRoles(): BelongsToMany
    {
        return $this->belongsToMany(
            self::class,
            'controlled_roles',
            'role_id',
            'controlled_role_id'
        )->withTimestamps();
    }
    public function controlledByRoles(): BelongsToMany
    {
        return $this->belongsToMany(
            self::class,
            'controlled_roles',
            'controlled_role_id',
            'role_id'
        )->withTimestamps();
    }

NOVA resource:

        BelongsToMany::make(__('Controlled roles'), 'controlledRoles', 'App\Nova\Role'),

        BelongsToMany::make(__('Controlled by'), 'controlledByRoles', 'App\Nova\Role'),

![image](https://user-images.githubusercontent.com/13627474/62005591-dd8e8a00-b135-11e9-89c4-f1cf6639c508.png)

### Steps To Reproduce:

1. Define a ManyToMany on the same resource
2. Access detail page of that resource
3. Attach Resource via that relationship
4. Click attach without selecting a resource

**Comment by Benjacho** [comment]
Did you resolve this?

**Comment by nysso** [comment]
no @Benjacho , unfortunately I'm still stuck

**Comment by jbrooksuk** [comment]
@nysso can you provide us with a reproducible code example (this can be a repository). Thanks!

**Comment by lizhineng** [comment]
The problem caused by given a relationship name which is not the same name as relatedResource in the routing.

> /nova-api/resources/teams/1/attach/**users**?viaRelationship=**members**&polymorphic=0

## Here are the steps to reproduce the problem:

1. Define a relationship in model and Nova resource

```
// in App\Team.php

...

public function members()
{
    return $this->belongsToMany(User::class);
}

...
```

```
// in App\Nova\Team.php

...

public function fields(Request $request)
{
    return [
        ....

        BelongsToMany::make('Members', 'members', User::class),

        ....
    ];
}

...
```

2. Attaching without selected user, the bug will be occurred.

---

I can't figured out how to fix this, but my temporary workaround is to keep the relationship name the same as the model name, which is modify `members` to `users`(See the example below), or else you will lose all the validation rules of the relationship that needs to be checked by the request.

```
// ... in src/Http/Controllers/ResourceAttachController.php

$resource::creationRulesFor($request, $request->relatedResource);
```

The issue I found is the method _creationRulesFor_,  **"users"** is giving in `$request->relatedResource`, but when execute the method creationRulesFor, we will never find out the target field because the attribute of the field which defined in resource is **"members"**.

Execute for my bad English, I try my best to explain the problem, hope you can understand me.😅


###  My Temporary Workaround

```
// in App\Team.php

...

public function users()
{
    return $this->belongsToMany(User::class);
}

...
```

```
// in App\Nova\Team.php

...

public function fields(Request $request)
{
    return [
        ....

        BelongsToMany::make('Members', 'users', User::class),

        ....
    ];
}

...
```

**Comment by davidhemphill** [comment]
Closed due to inactivity. If the issue still persists, feel free to post a new issue with the requested information above. Thanks!

**Comment by monaye** [comment]
@lizhineng did you solved your issue? I am trying to do the exact same things for Team <-> Member(user)  and getting the error as well.
