### ISSUE TITLE
duplicate index query on resources

### ISSUE THREAD

**Issue by gaabora** [laravel/nova-issues#1810]
- Laravel Version: 5.8
- Nova Version: 2.0.7+, 2.0.10 as well (maybe earlier too)

### Description
When navigating to any resources Index view duplicate index queries with different perPage parameter happens.

### Steps To Reproduce
open any resouce's Index page and whitness an example
```
/nova-api/user?search=&filters=W10%3D&orderBy=&orderByDirection=desc&perPage=&...
...
/nova-api/user?search=&filters=W10%3D&orderBy=&orderByDirection=desc&perPage=25&...
```
### Solution

I found a cause and fix it manually in my custom views plugin.
In `views\Index.vue` when `initializePerPageFromQueryString()` happens `this.$route.query[this.perPageParameter] || _.first(this.perPageOptions)` mirght return `undefined` so
 **|| this.perPage** added
```
initializePerPageFromQueryString() {
    this.perPage = this.$route.query[this.perPageParameter] || _.first(this.perPageOptions) || this.perPage
},
```

**Comment by jbrooksuk** [comment]
Confirmed in v2.0.10.

It looks like we're both fetching and counting the users twice. I've confirmed your fix works, so I shall push it upstream now.

**Comment by jbrooksuk** [comment]
I've made a PR.

**Comment by bakerkretzmar** [comment]
This change causes the custom `$perPageOptions` set on the resource to be ignored.

> In `views\Index.vue` when `initializePerPageFromQueryString()` happens `this.$route.query[this.perPageParameter] || _.first(this.perPageOptions)` mirght return `undefined`

When `initializePerPageFromQueryString()` is called, `_.first(this.perPageOptions)` will **always** be `undefined`. It's called before the resources are loaded, and `this.perPageOptions` is computed from `this.resourceResponse`, which doesn't exist yet.

I'm going to submit a PR to revert this change, because the duplicate queries are annoying but don't break anything, so I figure finding a solution for that (which I'll look into this week if I have time) is less important than not breaking other stuff.

**Comment by jbrooksuk** [comment]
@bakerkretzmar don't worry @davidhemphill and I were working on this issue last night and will have a fix soon.

**Comment by midorikocak** [comment]
I am having this issue on the resource detail page with morphmany relation. Should I open a new ticket for this?
