### ISSUE TITLE
Access selected resourceId on Action fields() method

### ISSUE THREAD

**Issue by hsharghi** [laravel/nova-issues#1813]
I have an Action to share a public/private link of a resource. When showing the modal dialog of the action I want to show the share link of the resource. But I don't have access to the selected resource so I can generate the share link.

<img width="817" alt="Screen Shot 1398-05-19 at 18 18 52" src="https://user-images.githubusercontent.com/2873823/62822630-675d3f00-bb9b-11e9-8ac5-e71b61f19539.png">

I think it would be useful to access selected resource Ids before returning `fields[]`, because some actions should be ran on single resource (link sharing the link), and the action can be disabled if more than one resource is selected.

I tried to use nova-button package to add a share button for each row, but it seems impossible to run an existing action via button. 

<img width="1582" alt="Screen Shot 1398-05-19 at 18 16 50" src="https://user-images.githubusercontent.com/2873823/62822647-b1462500-bb9b-11e9-9daf-7d8f54b2cd24.png">

I'm stuck with the way to show the modal dialog to user and handle the job.

**Comment by davidhemphill** [comment]
The selected resource IDs are available in the props passed to the modal component: 

<img width="1484" alt="image" src="https://user-images.githubusercontent.com/58970/62875221-41918080-bce8-11e9-8b11-636e91318263.png">

Also, it's not documented, but you can specify your own Vue component to use instead of the ConfirmActionModal on your Action class by overriding the `component` method. The Modal will receive the selected resource IDs as an array. If your action is only used on a single resource, you can then fetch details about the resource to show in the modal however you'd like.

**Comment by jivanrij** [comment]
You can get the resourceId from the request on the detail page of the model. This is not possible on the index page.

```
        if (isset(request()->resourceId)) {
                Model::find(request()->resourceId)->first()
        }
```

**Comment by lifeblood** [comment]
> The selected resource IDs are available in the props passed to the modal component:
> 
> <img alt="image" width="1484" src="https://user-images.githubusercontent.com/58970/62875221-41918080-bce8-11e9-8b11-636e91318263.png">
> 
> Also, it's not documented, but you can specify your own Vue component to use instead of the ConfirmActionModal on your Action class by overriding the `component` method. The Modal will receive the selected resource IDs as an array. If your action is only used on a single resource, you can then fetch details about the resource to show in the modal however you'd like.

How can get it?

**Comment by NowakAdmin** [comment]
I have a resource with field "size" for example 3KG, 4KG

I have an action with (only on index rows) field "amount" (number field)

I want to user to be able only to put multiplication of "size" in "amount" and a field that display on action value of "size"

I tried in action fields:
            Text::make(__('Package'), 'size')
                ->default(function(){
                    //need to load value of current model resource "size" to inform user
                    
                })
                ->readonly(),

			Number::make(__('Amount'), 'amount')
				->sortable()
				->min(1) // -> i need to change this based on "size" form model resource
				->max(9999)
				->step(1) // -> i need to change this based on "size" form model resource
				->updateRules('nullable')
				->rules('required', 'number')
				->help(__('in kilograms')),

How to load ConfirmActionModal['selectedResources'][0] in fields?

**Comment by AlbinoDrought** [comment]
[A hack like this might work](https://github.com/tunezilla/nova-dynamic-action-fields). I can confirm it at least works for simple actions, but we haven't done anything crazy with it yet.

**Comment by matthewjumpsoffbuildings** [comment]
> The selected resource IDs are available in the props passed to the modal component:
> 
> <img alt="image" width="1484" src="https://user-images.githubusercontent.com/58970/62875221-41918080-bce8-11e9-8b11-636e91318263.png">
> 
> Also, it's not documented, but you can specify your own Vue component to use instead of the ConfirmActionModal on your Action class by overriding the `component` method. The Modal will receive the selected resource IDs as an array. If your action is only used on a single resource, you can then fetch details about the resource to show in the modal however you'd like.

@davidhemphill why not pass the `selectedResources` prop down to each field component in the ConfirmActionModal? that way instead of having to override the nova ConfirmActionModal component, we can make custom fields and use the selectedResources prop to display information as we desire?

it would be as simple as updating the Action fields loop to the following in `ConfirmActionModal.vue`:
```html
          <!-- Action Fields -->
          <div
            class="action"
            v-for="field in action.fields"
            :key="field.attribute"
          >
            <component
              :is="'form-' + field.component"
              :errors="errors"
              :resource-name="resourceName"
              :field="field"
              :show-help-text="field.helpText != null"
              :selectedResources="selectedResources"
            />
          </div>
```
this is similar to this issue https://github.com/laravel/nova-issues/issues/3559 with Actions i posted recently where the `:query` props arent being passed down to the Action selector on table rows, it seems like a pointless oversight to not pass these kind of props along
