### ISSUE TITLE
Customizing Partition Colors requires all cases

### ISSUE THREAD

**Issue by michaellindahl** [laravel/nova-issues#1876]
- Laravel Version: 5.8.34
- Nova Version: v2.1.1
- PHP Version: 7.3.8

### Description

The [docs](https://nova.laravel.com/docs/2.0/metrics/defining-metrics.html#customizing-partition-colors) show in an example for the partition colors, that when a type is not in the array the "the default color from Nova" will be used. This is not the case and cause the metric to fail to load. 
In addition, changing the label also changes the value the colors array expects.

### Steps To Reproduce

1. Create a partition where not all states are listed in the array passed to colors.
2. Encounter a crash.

I was hoping this would be the code for custom colors and labels:
```
return $this->count($request, Model::class, 'state')
            ->label(function ($value) {
                return ucwords(str_replace("_", " ", $value));
            })
            ->colors([
                Model::STATE_ONE => '#63B3ED',
                Model::STATE_TWO => '#E2E8F0',
                Model::STATE_THREE => '#F56565'
            ]);
```
However, it appears that when you alter the label this also alters the type value that you need to key off of. This seems like a second bug, and it would be nicer if the label didn't modify the value that is needed in the colors array. The modified values meant that colors array wasn't explicit and the metric failed to load. The following code gets around both issues:
```
return $this->count($request, Report::class, 'state')
            ->label(function ($value) {
                return ucwords(str_replace("_", " ", $value));
            })
            ->colors([
                ucwords(str_replace("_", " ", MountainStatus::OUT)) => '#63B3ED',
                ucwords(str_replace("_", " ", MountainStatus::NOT_OUT)) => '#E2E8F0',
                ucwords(str_replace("_", " ", MountainStatus::UNKNOWN)) => '#F56565'
            ]);
```

**Comment by kidereo** [comment]
Connected to this issue, I believe, is the fact that presently if both `label` and `color` are used, the metric will return the first specified colour when the query returns 100 % need for the other. 

In other words, if you have a column `is_published` , custom colours e.g. red for `false` and green for `true`, and the values in the column are all `true`, the metric will return the correct label with e.g. "Posts Published - (5 - 100%)" but the colour will still be all red, not all green. If there is at least one `false` in the column, then the colour distribution will appear correctly.

This definitely comes from the `label` method because without it the all `true` colour displays correctly but of course without the benefit of that human friendly legend.

**Comment by ibrunotome** [comment]
This is a bug. I got a "undefined offset 0" if there is a missing color mapped.

**Comment by domstubbs** [comment]
Confirming this is still an issue with 2.9.3. Looking at the changelog I assume it was introduced with 2.0.2. This did work previously as I have an identical metric working in a Nova 1.3.1 project.

**Comment by mpoma** [comment]
Fom 3.13.0 i have an error Serialization of 'Closure' is not allowed.
The only closure is in the label

->label(function ($value) {
            return \App\DataPlan::find($value)->name; 
        });
