### ISSUE TITLE
Searchable component in the filter selector

### ISSUE THREAD

**Issue by wlarch** [laravel/nova-issues#1894]
**Feature request**
Possibility of using the searchable component in the filter selector.

**Problem**
Using the `select-filter` component for a Filter that has a large dataset is not user friendly.

![image](https://user-images.githubusercontent.com/5958500/64362862-468eda80-cfdd-11e9-92d9-16821bbde2d1.png)

**Implementation**
Within a Filter class, assigning the `search-input` component to the `$component` class variable would show a searchable input field. At the moment, it shows as follow : 

![image](https://user-images.githubusercontent.com/5958500/64363395-7ee2e880-cfde-11e9-874f-9bb1274fffd1.png)

**Comment by davidhemphill** [comment]
I see why you'd want this, and we'll probably see how we could do it at some point, but for now, you'll need to create a custom filter to handle this yourself.

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by anotherfrontendguy** [comment]
@wlarch We had the same problem as you, here is our take at a solution for it:
[suenerds/nova-searchable-belongs-to-filter](https://github.com/suenerds/nova-searchable-belongs-to-filter)

**Comment by keizah7** [comment]
Trying to find same solution to use with `nova-bi/nova-dashboard-manager` filter
