### ISSUE TITLE
Dashboard full width cards display last

### ISSUE THREAD

**Issue by rodrigoreyes79** [laravel/nova-issues#1895]
- Laravel Version: 5.8.35
- Nova Version: 2.2.0
- PHP Version: 7.2.19-1
- Operating System and Version: ubuntu18.04.1
- Browser type and version: Chrome (Mac) 76.0.3809.100

### Description

Full width cards placed in dashboard appear last.

![Captura de Pantalla 2019-09-05 a la(s) 14 49 11](https://user-images.githubusercontent.com/3924426/64375815-59f57200-cfec-11e9-8a96-a1a0d208f822.png)

```
    /**
     * Get the cards that should be displayed on the default Nova dashboard.
     *
     * @return array
     */
    protected function cards()
    {
        return [
            (new HtmlCard())->width('full')->markdown('# Hello World!'),
            (new App\Nova\Metrics\CallsPerDay())->width('2/3'),
            (new App\Nova\Metrics\ContactsPerDay())->width('1/3'),
        ];
    }
```

### Steps To Reproduce

Create a full width card as the first card in the cards array. Then add more non full width cards after that one.

**Comment by rodrigoreyes79** [comment]
@taylorotwell Any comments on this?

**Comment by davidhemphill** [comment]
This was an intentional design decision when we built metrics and cards. The first consideration was to keep the user from accidentally creating an overflow on the parent container by creating a card that exceeded the remaining width, e.g. 1/2 + 3/4. The other reasoning was since Nova's full-width cards are not limited in height like the other ones, even if a full-width card was forced to take up only the remaining width, you'd get an ugly space because it's height was not limited.

In general, I'm not a fan of full-width cards for anything, except maybe a large graph or something like that. Everything else should be a custom tool.

Closing since this is an intentional aspect of Nova, but feel free to post your thoughts!

**Comment by rodrigoreyes79** [comment]
@davidhemphill Thanks for your thorough response. It make sense.

Having said that, in our case we wanted to add a "notification" card that could be attached to the top of the dashboard above all the rest of the cards. Because of this, I think it won't be possible. And creating a full custom tool just for this looks like an overkill.

Any recommendations on how to accomplish this? Any workarounds maybe?

Thanks in advance.

**Comment by cord** [comment]
https://novapackages.com/packages/ericlagarda/nova-text-card stays where it should ;)

**Comment by rodrigoreyes79** [comment]
@cord Yes, you are right. It looks like they found a "hack" to force full width. Thanks for the tip!!!

@davidhemphill It may not be a bad idea to give developers the option of full width top cards on their own responsibility. Although I do agree with your perspective on this matter, there may still be some edge cases where having this option natively could help. Hope you reconsider.

**Comment by davidhemphill** [comment]
@rodrigoreyes79 I agree with you, and I generally prefer to give developers sharp tools and let them cut themselves, but in this case the alternative (where you could have overflowing cards) could easily be considered a bug by other people, you know? Not saying there's isn't a way we can fix it though.

**Comment by rodrigoreyes79** [comment]
@davidhemphill Yes. That makes sense too. I liked what @cord package did. The package provided a "special" method for forcing full width. So, you need to go out of your way to actually make it happen. That may be a way of giving devs the option but not allowing them to step over it without understanding the consequences. 

In the end, I do agree that this could end up being more work Nova's team. So feel free to disregard my opinion on this matter. Having said that, thanks for taking the time to discuss it.

**Comment by davidhemphill** [comment]
What if we made Dashboard cards use a "masonry" style layout so they'd just stack as they need to. We could remove the height restriction on full-width cards and they'd never break the width? Just an idea.

**Comment by rodrigoreyes79** [comment]
@davidhemphill What if Nova provided a way to create "custom layouts"? I do like what Nova has done so far. I wouldn't change it to "masonry" but rather provide the "masonry" layout for dashboards. Hopefully, if there is a way to add custom layouts, people will find a way to either build what they need or use what someone else built. What do you think about that?

**Comment by davidhemphill** [comment]
I'm not sure what this means.

**Comment by codebykyle** [comment]
@davidhemphill The current implementation doesn't allow something without the use of a hack. In my opinion, that means this is probably not the right way to go about this. 

The explanation that some users may may consider an overflow a bug, and therefor, not allowing a full-width container to be positioned by the developer, is a bit nonsensical. Who is the target audience for Nova, in this scenario? 

Maybe I am overestimating the user-base here, but in your example, if we are professional woodworkers, and you are giving us toy handsaws to build some furniture with, because we cant be trusted to use a table saw, I'll be honest in saying I'm going to go find somewhere else which will let me use a table saw and do my job. I enjoy Nova, and appreciate your hard work on this, but I just want to illustrate the absurdity I see in that argument. The concept of ignoring user input for the sake of design and "developer safety" is frustrating when you're the one having to implement the hack.

I'd ask you to reconsider.

**Comment by davidhemphill** [comment]
You probably are overestimating the user base. I've got a lot of time with them, so I have a good idea of what they run into. And I get the whole "sharp tools" argument and generally agree with the sentiment, but in the end calling it "absurd" or threatening to go somewhere else because of a minor inconvenience is not a good way to convince us. If this one thing is a deal-breaker, then Nova probably isn't the right product for you as it's very opinionated in other areas as well...on purpose. :-) 

I appreciate your response, but this is the direction we're sticking with for now.

**Comment by codebykyle** [comment]
@davidhemphill Thanks for the reply

I didn't call the argument absurd, I said I view it as absurd. My opinion is worth nothing, so take it with a grain of salt. I would rather make Nova more usable, not leave.

I was hoping, through use of a metaphor, you would understand the frustration of having to dig through source files, of not just Nova, but also third party packages, search through Google, and find a hacky solution for something that is undocumented and seems almost arbitrary.

My response may have come off a bit too strong, sorry about that. However, I do strongly disagree with overriding developer driven content.

**Comment by 4n70w4** [comment]
Why is this behavior not described in the documentation? I spent an hour to understand that this is not a problem with my code.

**Comment by cord** [comment]
> This was an intentional design decision when we built metrics and cards. The first consideration was to keep the user from accidentally creating an overflow on the parent container by creating a card that exceeded the remaining width, e.g. 1/2 + 3/4. The other reasoning was since Nova's full-width cards are not limited in height like the other ones, even if a full-width card was forced to take up only the remaining width, you'd get an ugly space because it's height was not limited.
> 
> In general, I'm not a fan of full-width cards for anything, except maybe a large graph or something like that. Everything else should be a custom tool.
> 
> Closing since this is an intentional aspect of Nova, but feel free to post your thoughts!

There is a range of vue based grid layouts on https://awesome-vue.js.org/components-and-libraries/ui-layout.html#ui-layout - these would allow to arrange cards in different widths and heigths.

**Comment by vesper8** [comment]
> ```
>     mounted() {
>         this.$parent.$el.classList.remove('w-5/6');
>         this.$parent.$el.classList.add('w-full');
>     }
> ```

In addition to this working hack to allow you to place your full-width card anywhere you want and not have it go straight to the bottom.

If you want to also benefit from the variable height (allowing your full width card to grow higher than a regular card, add this:

```
this.$el.classList.remove('card-panel');
```

**Comment by kuvar0158** [comment]
can you please explain full width card is going first and 1/2 width card show on last

**Comment by theianjohnson** [comment]
Also would like to see this behavior changed to simply display cards in order. Until finding this GitHub issue it was pretty confusing why setting up the array of cards caused some to display in order and others not to with no explanation.

_That_ seems like a poor developer experience

**Comment by jankapusta** [comment]
This behaviour of placing "full"-width cards below other cards is very confusing and seems arbitrary. And is undocumented. Seems like bad development practice.

**Comment by andy-laravel** [comment]
How can this be closed when it's still an open issue and no fix applied?

**Comment by rhino-corey** [comment]
I wish this didn't get closed. It certainly isn't very intuitive for a new Nova developer.
