### ISSUE TITLE
"displayUsing" doesn't work with null values

### ISSUE THREAD

**Issue by salomonsanz** [laravel/nova-issues#1901]
- Laravel Version: 5.8.35
- Nova Version: 2.2.0
- PHP Version: 7.1.23

### Description

The fields method "displayUsing" doesn't works if value is null, the function always returns a empty string.
A case of use, if you have an integer field called "periodicity", if is null you maybe want to display to the user the "never" instead of empty text...

### Steps To Reproduce
Create a field with null value, and call the method 
```
// this should work, but doesn't work
->displayUsing(function($value){
if (empty($value))
        return 'empty value';
    else
        return 'my value is: '.$value;
}
```

**Comment by jbrooksuk** [comment]
Confirmed.

**Comment by reytarovskiy** [comment]
Confirmed.

**Comment by mdavis1982** [comment]
This also happens with `resolveUsing()`. It tries to get the data from the model and sets a default value... But then compares that against the value:

https://github.com/laravel/nova/blob/2.0/src/Fields/Field.php#L243-L247

I believe this should be changed so that `null` values allow the `resolveUsing()` callback to be fired even if the value is `null`.

The lines of code that are doing this for `displayUsin()` are here:

https://github.com/laravel/nova/blob/2.0/src/Fields/Field.php#L215-L219

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/96404112-a578d880-120c-11eb-9994-6f641f840e57.png)

I wasn't able to replicate the issue on latest v3.12.1

Reproducing code: https://github.com/nova-issues/issue-1901/commit/1694bf74d781a7f08ddea82d91b3a9d97b9f15d0

----- 

At this point I assume the problem has been fixed sometimes in the past but never got updated here. Closing this for now but feel free to create a new issue with reproducing code so we can move forward with this, thank you.
