### ISSUE TITLE
Queued Actions not working. "Serialization of 'Closure' is not allowed"

### ISSUE THREAD

**Issue by alexjose** [laravel/nova-issues#194]
I am getting `Serialization of 'Closure' is not allowed` error when trying to queue the action.

```php
class Activate extends Action implements ShouldQueue
{
    use InteractsWithQueue, Queueable, SerializesModels;

    public function handle(ActionFields $fields, Collection $models)
    {
        foreach($models as $model){
            $model->status = true;
            $model->save();
            $this->markAsFinished($model);
        }
        return Action::message('Activated Selected User(s)');
    }
}
```

Also, how is the memory managed if action is performed on a huge collection of models? Say for example my `Select All Matching` is around 20K records.

**Comment by patrickbrouwers** [comment]
Doesn't you stack trace show you what the Closure is that it's trying to serialize?

About your memory question: the action uses model chunks behind the scenes with a chunk size of 200.

**Comment by jianminLee** [comment]
I have encountered the same error, the registration "Action" can not use “canSee” ，“canSeeWhen” “canRun” authorization, otherwise it will throw the same error

**Comment by rickmacgillis** [comment]
@jianminLee Nice catch. I was wondering why that happened. To take it a step further, the reason it can't serialize it is because it attaches that closure to the `seeCallback` and/or `runCallback` when using those methods.

Team Nova: I suggest allowing those to use the popular `Class@method` notation as the callback.

**Comment by pix2D** [comment]
So what is the solution when one has to use canRun because of #676 #558?

**Comment by bolechen** [comment]
Issue still present in v1.3.2

**Comment by dkulyk** [comment]
You need to override `authorizedToRun` method in the action for queued actions instead using can* methods.

**Comment by chuangbo** [comment]
@dkulyk `authorizedToRun` works for queued action, but it seems to conflict with #114 "Run actions without update authorization". If we add `authorizedToRun`, nova would still require a model `update` permission for the action.

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.

**Comment by chescos** [comment]
Why has this issue been closed? The issue still persists and it's clearly a bug

**Comment by aaronahearne** [comment]
This seems to be related to the constructor rather than the `canSee `function specifically. Without looking into the source code, I would take a guess that the one of the traits required for queuing actions (probably SerializesModel) is attempting to serialize the entire action ([as would be normal for a Laravel job](https://laravel.com/docs/5.8/queues#generating-job-classes)). But maybe the Action class that we are extending contains a closure somewhere. So when the system attempts to serialize the model to enter it into the queue, it fails.

[I was having the same issue combined with an issue with the Queueable trait](https://stackoverflow.com/questions/56340502/job-class-and-illuminate-bus-queueable-define-the-same-property-connection/56340503#56340503).

Moving everything into the `handle` function and removing the constructor solved this for me... but Im not entirely sure why as it would usually be possible to include a constructor within your job definition.

I guess it could be something to do with the way the action needs to be instantiated within a resource when it injects dependencies like:

```
 return [
            resolve(ScheduleInventoryUpdate::class),
        ];
```

So to solve the issue my code went from:

```
class ScheduleInventoryUpdate extends Action implements ShouldQueue
{
    use InteractsWithQueue, Queueable, SerializesModels;

    private $inventoryService;

    public function __construct(InventoryService $inventoryService)
    {
        $this->inventoryService = $inventoryService;
        $this->connection = 'database';
        $this->queue = 'inventory_update';
    }


    /**
     * Perform the action on the given models.
     */
    public function handle(ActionFields $fields, Collection $products)
    {
        foreach ($products as $product) {
            try {
                $this->inventoryService->updateProductInventory($product);
```


```
To:

class ScheduleInventoryUpdate extends Action implements ShouldQueue
{
    use InteractsWithQueue, Queueable, SerializesModels;
    
    /**
     * Perform the action on the given models.
     */
    public function handle(ActionFields $fields, Collection $products)
    {
        $this->connection = 'database';
        $this->queue = 'inventory_update';
        $inventoryService = app(InventoryService::class);

        foreach ($products as $product) {
            try {
                $inventoryService->updateProductInventory($product);
                $this->markAsFinished($product);
            } catch (\Exception $e) {
                $this->markAsFailed($product);
            }
```

**Comment by gerardnll** [comment]
@davidhemphill Please, can you take a look at this issue? I've posted how to reproduce it.

**Comment by dkulyk** [comment]
it fixed in 2.1.0. You should remove `SerializesModels` trait from an action

**Comment by gerardnll** [comment]
> it fixed in 2.1.0. You should remove `SerializesModels` trait from an action

Why?

**Comment by dkulyk** [comment]
Because SerializesModels override __sleep method in action. This trait no need in actions.

**Comment by gerardnll** [comment]
Well, actions generated by the command or as explained in docs, include this trait. So there’s something strange here.

**Comment by dkulyk** [comment]
I've added PR for remove it from Action stub

**Comment by SadeghPM** [comment]
> I've added PR for remove it from Action stub

In a scenario I remove `SerializesModels` trait and the error changed to `serialization of 'Illuminate\Http\UploadedFile' is not allowed`.

**Comment by gerardnll** [comment]
> > I've added PR for remove it from Action stub
> 
> In a scenario I remove `SerializesModels` trait and the error changed to `serialization of 'Illuminate\Http\UploadedFile' is not allowed`.

There's a note in Nova documentation: 

> At this time, Nova does not support attaching File fields to a queued action. If you need to attach a File field to an action, the action must be run synchronously.

Here: https://nova.laravel.com/docs/2.0/actions/defining-actions.html#queued-actions

**Comment by SadeghPM** [comment]
yeah , thanks @gerardnll
