### ISSUE TITLE
search with separator not working

### ISSUE THREAD

**Issue by Dontorpedo** [laravel/nova-issues#1974]
- Laravel Version: 5.8
- Nova Version: 2.0.9
- PHP Version: 7.2

i have many values like 420.25, 190.15 etc etc
in nova search i can only search for 420 or 190 and not for the exact match of 420.25 etc
tried also with 420,25 etc.. is there a trick to make it work or workaround?

**Comment by davidhemphill** [comment]
I'm not able to replicate your issue. I can search for a value. I've tested this with both string and decimal column types (set as Text and Number field types, respectively). The column is set in the resource's `search` property.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/58970/65721834-7bd49880-e070-11e9-9ca8-032e59c2b2b7.png">

As there's no other information included in your issue, I'm going to assume the problem is somewhere on your end. Please feel free to post a new issue if you can provide more information to reliably reproduce the problem.
