### ISSUE TITLE
Action fields. Make fields() method able to access $models

### ISSUE THREAD

**Issue by h-zone** [laravel/nova-issues#1988]
Case:
in example website application with request for something...
guest fills name/email with application form.

im making an ability for programmable creation of the user, so i cant access to $models from fields() method to pre-fill the required fields from the application(s)

if anybody knows hot to easy access to $models and it is not crutch... i will be glad to see solution.

**Comment by jbrooksuk** [comment]
This is out of scope of the Nova project.

**Comment by potsky** [comment]
An other use case, I use the Spatie States Model package → https://docs.spatie.be/laravel-model-states

In a Nova user form for example, according to user current state (eg. Pending), I should only show Failed and Success states and not Init. Currently I cannot because I cannot generate a Select and populating options according to current user state value.
