### ISSUE TITLE
Complex Fields & Nested Objects

### ISSUE THREAD

**Issue by bayareawebpro** [laravel/nova-issues#207]
## Vue Components / ReUsability

I would like to use nova field components outside of their default implementations, such as combining them in an alternate layout / grid for complex fields. For example, the text field. If I add props to the component such as :value, or @change they will be bound to the parent component "default-field" not the actual input. This is a huge problem for reusability which is the primary reason to use components. You shouldn't force an implementation when you don't have to.  In simple terms, don't wrap the basic implementation of a component with other components unless it’s in the layout where it’s used.
```
<template>
<default-field :field="field">.... Move this to the layout when used. 
<template slot="field">
<input :id="field.name" .... This should be root.  I want to use this elsewhere. 

<template>
<field-wrapper>
<div class="w-1/5 px-8 py-6"> The grid size should then be configurable with props.
```
This is partially a Vue Framework and you should approach it as such to insure maximum reusability of the included assets. Essentially, what I would like to see is each of these primary components reworked so they can be used standalone in our own custom fields & tools.

-Form Inputs & Selects
-Searchable Dropdown
-Etc… 

## Forced Use of FormData as the Primary Transport Container in a JSON focused application. 

FormData is great for uploads and single values but it's a real headache to try and deal with complex objects which contain nested data. It would have been a better choice to use Objects as the primary transport method with support for FormData as a secondary transport method. A solution to this is to use JSON.stringify to store the data in a single formData field, but that means you sacrifice validation of said nested properties. In reality, Validation of Nested Objects from a complex field should be supported. Most of the Vue Framework’s I’ve used only used FormData inside uploader components.   The current implementation feels backwards and limits what we can do.

Possible Solutions  (Adapt Fields to use Objects instead of FormData):
1. Move the uploading capability to it's own special type of request. 
2. Implement a FormData Library that will build the FormData before the request is sent allowing Objects to be passed to and from fields. 

## No actual documentation for the included FormField classes and Vue Components. 
This make things difficult to grasp. Everything should be documented.

## No Ability to set a default for a field value. 
We can use accessors, but how bout a method, or did I miss something?

**Comment by zeroseed** [comment]
+1 This is very great, like grid size props etc to be have customizable and reusable, 
we should have ability to make all possibilities on building form components , how great !

**Comment by davidhemphill** [comment]
Not be short, but our components are designed to work the way we want them. You are free to use them if they're useful for you and also free to create any custom ones that do exactly what you need. 😄

**Comment by martynling** [comment]
@davidhemphill This kind of attitude might perhaps be justifiable in an open source project. However, Nova is a product that is being sold to developers and we, as customers, have opinions on how we would like the product to function - on things that would make it better for us and other customers. As customers, it is surprising to hear you say that "our components are designed to work the way we want them" rather than that they were designed for the benefit of your customers. The customer does not always know what is best for them, but I think your customers' views deserve a little more respect. 

If you'd like to prominently explain in the marketing that the Form UI/UX is limited to what you, the Nova team, need it to do, that you're only selling it to make it a bit of extra money on the side and that you're not interested in making it easily extendible for developers then fair enough but that doesn't seem to match the sales pitch.

**Comment by demency** [comment]
As alternative solutions for grid systems:

https://github.com/nibri10/nova-grid (For create/update views)
https://github.com/demency/nova-gridder (For details views)

👀
