### ISSUE TITLE
Nova tries to show singularLabel of not yet selectable Morphable

### ISSUE THREAD

**Issue by pfried** [laravel/nova-issues#2074]
- Laravel Version: 6.3.0
- Nova Version: 2.5.0
- Database Driver and Version: #.#
- Operating System and Version: #.#
- Browser type and version: Chrome  77.0.3865.120

### Description

Nova trys to access a SingularLabel for a non selected MorphTo Type resulting in an error on the console (only there, so no usability impact):

    TypeError: Cannot read property 'singularLabel' of undefined

Code from `MorphToField.vue`:

        /**
         * Return the selected morphable type's label
         */
        fieldTypeName() {
            if (this.resourceType) {
                return _.find(this.field.morphToTypes, type => {
                    return type.value == this.resourceType
                }).singularLabel
            }

            return ''
        },

### Steps To Reproduce

Create a Morphable Relation and create a new object with that relation, the select field for the Morphable will be empty at first as no Type is yet selected, this is where the error appears on the console (only there).

**Comment by Pamposgsk** [comment]
Hi the problem is not only in the console.It also reset the form.see below
![053C5895-7FA9-423F-81B4-FA356D38D7A6](https://user-images.githubusercontent.com/8403769/74683730-85eb6500-51d2-11ea-9018-af32037558b4.png)
![87B5AFD4-189E-4E76-A3C5-86D15645BC96](https://user-images.githubusercontent.com/8403769/74683735-8ab01900-51d2-11ea-8336-2906e2056143.png)
![BBD56245-E3A3-455C-A867-F67EC3694A3A](https://user-images.githubusercontent.com/8403769/74683736-8d127300-51d2-11ea-9b84-a56cb8252ad0.png)
![734ED354-989C-4018-9700-F5BADA150511](https://user-images.githubusercontent.com/8403769/74683741-8f74cd00-51d2-11ea-993f-c2ec4a04a61c.png)

**Comment by jbrooksuk** [comment]
You should upgrade to the latest version of Nova now.
