### ISSUE TITLE
 If action_events changed content greater than `text` type then exception

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#2082]
- Laravel Version: 5.8.35
- Nova Version: 2.5.0
- PHP Version: 7.3

### Description
```
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'changes' at row 1 (SQL: insert into `action_events`
```

https://github.com/laravel/nova-issues/issues/1937

### Steps To Reproduce

Edit resource with too big text.

**Comment by jbrooksuk** [comment]
You should modify this migration to suit your needs.

**Comment by 4n70w4** [comment]
@jbrooksuk no. I do not want to change migration.
I want don’t save events about certain resources into the action_events table.
I don’t need data about changed huge data.

**Comment by jbrooksuk** [comment]
https://nova.laravel.com/docs/2.0/actions/defining-actions.html#disabling-the-action-log

This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).

**Comment by NoelDeMartin** [comment]
@jbrooksuk Is it possible to disable the action log on a built-in action? I'm editing a blog post and getting this error because the contents are too big. But I'm not sure how to disable the action log for the "update" action. If this weren't possible, it'd be nice to ignore some fields from the changes.
