### ISSUE TITLE
[Currency Field] Function money_format() is deprecated | PHP 7.4

### ISSUE THREAD

**Issue by haxmedia** [laravel/nova-issues#2089]
- Laravel Version: 6.4.0
- Nova Version: 2.5.0
- PHP Version: 7.4
### Description

Currency Field uses money_format function, that is deprecated from PHP 7.4, and broke the endpoint response as the screen below.

![image](https://user-images.githubusercontent.com/7444239/67769662-2a477100-fa55-11e9-814a-5da8b53f6a11.png)

**Comment by jbrooksuk** [comment]
One of many duplicates https://github.com/laravel/nova-issues/issues/2051

**Comment by ProdigyView** [comment]
Read here: https://medium.com/helium-mvc/installing-php-7-4-on-docker-108b79203fad

You should be using NumberFormatter.

**Comment by rgehan** [comment]
@jbrooksuk It seems a bit different from the issue you've linked though.

In one case, the function doesn't exist (on Windows it seems), and in this specific case, it is throwing because it is marked as deprecated (which happens on PHP 7.4).

I understand that the plan is to move to something else than `money_format`, so the fix might be the same, but marking these issues still aren't duplicates

**Comment by jbrooksuk** [comment]
Fixing one will fix another.

**Comment by kosmonowt** [comment]
just switched to PHP7.4 and having this issue. Could help only by suppressing the deprecation message on this function.

Could you please provide a working solution in the repo for that one?

**Comment by gldrenthe89** [comment]
Please fix this couse can't use it anymore now

**Comment by gldrenthe89** [comment]
> just switched to PHP7.4 and having this issue. Could help only by suppressing the deprecation message on this function.
> 
> Could you please provide a working solution in the repo for that one?

How did you do it?

**Comment by kosmonowt** [comment]
Currency.php line 27: 
```php
- return ! is_null($value) ? money_format($this->format ?? '%i', $value) : null;
+ return ! is_null($value) ? @money_format($this->format ?? '%i', $value) : null;
```

replaced the 1st line with the 2nd one.

I would not recommend this for productive environments, since it suppresses all possible other warnings etc. 

But it's sufficient at least for me until the maintainers will provide a better solution.
 
_Thanks for the person who fixes it appropriately eventually._

**Comment by gldrenthe89** [comment]
> Currency.php line 27:
> 
> ```
> - return ! is_null($value) ? money_format($this->format ?? '%i', $value) : null;
> + return ! is_null($value) ? @money_format($this->format ?? '%i', $value) : null;
> ```
> 
> replaced the 1st line with the 2nd one.
> 
> I would not recommend this for productive environments, since it suppresses all possible other warnings etc.
> 
> But it's sufficient at least for me until the maintainers will provide a better solution.
> 
> _Thanks for the person who fixes it appropriately eventually._

thanks

**Comment by jonassiewertsen** [comment]
I got the same problem and am waiting to get this issue fixed for PHP7.4. 

Changing vendor files in production isn't an option for me.

**Comment by kosmonowt** [comment]
I use my own privately hosted and maintained Repository - included as a submodule within my core project. so that’s quite easy to track and maintain once a new Version If nova came out. At least if I need just a quick fix until the next release.

So for me it’s rather a temporary fork than a change of my vendors.

Cheers

**Comment by jonassiewertsen** [comment]
I do use Laravel Forge for production, so my vendor files will be updated via composer. 

For me its an option in production.

I did swap the Currency field with the Number field and am waiting for Laravel Nova to fix the issue

**Comment by mydnic** [comment]
@jbrooksuk this is not the same error as #2051 
This issue needs to be reopened, because of this it's impossible to use the Currency field with PHP7.4

**Comment by KaptinLin** [comment]
Still having this issue. Any update?

**Comment by abishekrsrikaanth** [comment]
any updates on this issue?

**Comment by abishekrsrikaanth** [comment]
I was able to use the `displayUsing` method to resolve this:

```
Currency::make('Registration Fee', 'fee')->displayUsing(function ($fee) {

       $formatter = new NumberFormatter('en_US', NumberFormatter::CURRENCY);

       return $formatter->formatCurrency($fee, 'USD');
}),
```
I know this is just a temporary solution..

**Comment by chissevo** [comment]
It's Work for me

public function price_format()
    {
        return @money_format('%i', $this->value);
    }
