### ISSUE TITLE
Duplicated requests on detail view.

### ISSUE THREAD

**Issue by vDk3** [laravel/nova-issues#2118]
- Laravel Version: 5.8
- Nova Version: 2.6.1

### Description
Nova firstly fetches resource with param perPage=25 and then same resource with param perPage=5 on detail view.

### Steps To Reproduce
1. Enable Action Events or add any MorphToMany/HasMany/BelongsToMany field to your resource.
2. Go to detail view
3. Check network tab in your browser

`http://127.0.0.1:8000/nova-api/action-events?search=&filters=W10%3D&orderBy=&orderByDirection=desc&perPage=25&trashed=&page=1&viaResource=users&viaResourceId=34727&viaRelationship=actions&relationshipType=hasMany http://127.0.0.1:8000/nova-api/action-events?search=&filters=W10%3D&orderBy=&orderByDirection=desc&perPage=5&trashed=&page=1&viaResource=users&viaResourceId=34727&viaRelationship=actions&relationshipType=hasMany`

**Comment by jbrooksuk** [comment]
Can you please provide more information? What browser are you using?

**Comment by jbrooksuk** [comment]
Never mind, confirmed in Google Chrome.

**Comment by jbrooksuk** [comment]
I forgot to reply to this. Action events will refresh automatically.

**Comment by vDk3** [comment]
@jbrooksuk so what?
I mentioned action events as example, you can add any MorphToMany/HasMany/BelongsToMany field and you will see dupliacted requests after page load.

**Comment by renky** [comment]
Confirmed bug with Nova v2.9.2

I have a "user" resource and want to search for the user id 6558 - the problem described is imho related to the auto-refresh-trigger - as you see in my situation it starts a search for 65 and one for 6558 - this is, because I entered 65 fast and needed a bit more time to enter the additional 58 - the search already started for 65, when the search for 6558 was triggered. Since the response for my 65-search is much bigger as for the exact id 6558 you can see that the first one takes much longer than the second one, and thats the reason, why my search result in the end shows the result of searching 65 instead of 6558. 

I'd suggest that in case of a second search request, the first should be canceled, or at least the result should be ignored

![searchbug](https://user-images.githubusercontent.com/6528960/72070383-c0b3d080-32e9-11ea-9299-670ba0b3f84b.png)
