### ISSUE TITLE
The name attribute in Nova's action cannot be Chinese！

### ISSUE THREAD

**Issue by alex-liu-sudo** [laravel/nova-issues#2127]
- Laravel Version: 5.8
- Nova Version: 2.6.1
- PHP Version: 7.3

**Comment by jbrooksuk** [comment]
Sorry, but there's not enough information to go off of here. If the issue you have still persists, please feel free to open a new issue with all the details of what you're trying, what you expect to happen, what's happening, and how to reproduce it. Thanks!

What happens when you use Chinese characters? Can you provide screenshots or log files?

**Comment by bolechen** [comment]
#2150
