### ISSUE TITLE
KeyValue field sent empty object {} if no KeyValue filled (all KeyValues are deleted)

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#2167]
Case 1: one empty KV - sending `{}` to backend
![image](https://user-images.githubusercontent.com/38257723/69248052-97fe3d00-0bbc-11ea-9121-cc5480b4a4ce.png)

Okay.

Case 2: no one KV - sending `{}` to backend
![image](https://user-images.githubusercontent.com/38257723/69248071-a0567800-0bbc-11ea-82f8-404fb2f51acf.png)

Why? I expected to get different values in the backend for these cases.

 I need ability to choise send `null` or send `{}` if KeyValue field not filled. Because I have separate logic for `null` or `{}`. Example: if `null` - use dafault behavour, if `{}` - nothing to do.

**Comment by jbrooksuk** [comment]
The `KeyValue` field works with `{}` being an empty value since it's expecting JSON.

For your case, you could override the `KeyValue` field and modify the `fillAttributeFromRequest` method to return a different default value.

**Comment by RomainMazB** [comment]
Facing this today.

I agree that `KeyValue` works with `{}` the same way `Number` works with `0`.

The problem is that it can break the application logic process managed by Nova to not have a `{}` value instead of a `null`

Example: I am using [spatie/laravel-data](https://github.com/spatie/laravel-data), which converts some of my database json field into a DTO to be more consistent.

With a `{}` value instead of `null`, the package attempt to create the DTO but doesn't have the data to fill the DTO properties, resulting to this:
![image](https://github.com/laravel/nova-issues/assets/53976837/e27bf48d-c790-4854-b064-705c112531e4)

I tried something like this: 
```php
KeyValue::make('Data')
  ->nullable()
  ->nullValues(fn ($v) => blank($v))
  ```
without success...
`->nullable()` and `->nullValues()` with a callback doesn't work either with `KeyValue` because the Field doesn't even look at these fields, which emphasize from the final-user that there are bugs here:
```php
protected function fillAttributeFromRequest(NovaRequest $request, $requestAttribute, $model, $attribute)
{
  if ($request->exists($requestAttribute)) {
    // The value for KeyValue fields are serialized on the front-end using `JSON.stringify`,
    // so we need to convert it to an associative array before saving it to the database.
    $this->fillModelWithData($model, json_decode($request[$requestAttribute], true), $attribute);
  }
}
```
Coupled to the fact that this could be easily solved by a tiny addition to the core to look at the `nullValues` (which should be`'{}'` as default for `KeyValue` field), @jbrooksuk @davidhemphill can we reconsider this as an open issue?
