### ISSUE TITLE
Ability to lock a resource while editing ( disabling / warning others users to edit it )

### ISSUE THREAD

**Issue by olivM** [laravel/nova-issues#2170]
I would like to be able to lock a resource to disable ( or warn before ) its editing
the main purpose is to avoid multiple users to edit the same resource at the same time ( and overwriting their updates ... )

Many CMS have this kind of security, and Nova should have this useful functionnality either natively or via a custom package

(i'll try to work on a package of my own, if no solution exists )

thx !

**Comment by davidhemphill** [comment]
Nova already has this feature: https://nova.laravel.com/docs/2.0/resources/#preventing-conflicts

**Comment by lisotton** [comment]
I understand that Laravel Nova has this feature, but it prevent content from being overwritten, but it does not prevent a user to start editing a resource, spend some time in this page and at the end loose his/her entire work because someone else changed the resource in the meantime. As @olivM mentioned, it would be nice to warn before saving the resource that somebody else is also editing the resource.

**Comment by ericmulder** [comment]
Are there any plans or packages for this? For example, WordPress uses a heartbeat ajax call which reserves the resource every x seconds and offers the possibility to take over the resource if needed.
