### ISSUE TITLE
Nova Action ability to stream response

### ISSUE THREAD

**Issue by rogierverbrugge** [laravel/nova-issues#2191]
I've created an export action for streaming large files but just found out that's not a possible response for the action. Would be nice to have this as an option :)

**Comment by jbrooksuk** [comment]
Downloads are actually links which are then clicked to trigger, hence why streaming downloads don't work.

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
