### ISSUE TITLE
BelongsToMany pivot fields don't respect onlyOnForms

### ISSUE THREAD

**Issue by d-pollard** [laravel/nova-issues#2205]
- Laravel Version:  6.6.2
- Nova Version: 2.8.0
- PHP Version: 7.2.25
- Database Driver & Version: MySQL 8
- Operating System and Version: MacOS Catalina
- Browser type and version: Any

### Description:

I have 2 resources connected by a pivot table, `House` and `User`

#### `\App\User.php`

```php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

   # ... other stuff, shortened for brevities sake ...

    public function houses()
    {
        return $this->belongsToMany(House::class, 'house_users')->using(HouseUser::class)->withPivot(['access_status', 'role']);
    }
}

```

#### `\App\House.php`

```php

<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class House extends Model
{
    public function users()
    {
        return $this->belongsToMany(User::class, 'house_users')->using(HouseUser::class)->withPivot(['access_status', 'role']);
    }
}

```

#### Nova resource `BelongsToMany` field

```php

BelongsToMany::make('Users')
    ->fields(function () {
        return [
            Badge::make('Access Status')->map(HouseAccessStatusEnum::STATUSES)->labels(HouseAccessStatusEnum::LABELS),

            Select::make('Access Status')->options(HouseAccessStatusEnum::LABELS)->displayUsingLabels()->onlyOnForms(),

            Select::make('Role')->options(HouseRolesEnum::LABELS)->displayUsingLabels()->nullable()->onlyOnForms()

        ];
    })

```

#### End Result

<img width="1153" alt="Screen Shot 2019-12-07 at 7 08 00 PM" src="https://user-images.githubusercontent.com/16292606/70382656-fb120280-1924-11ea-8d2e-e3fc7d5bde0e.png">
<img width="1153" alt="Screen Shot 2019-12-07 at 7 08 28 PM" src="https://user-images.githubusercontent.com/16292606/70382658-fb120280-1924-11ea-8b18-3f0ce8a9fa3a.png">

**Comment by arjasco** [comment]
I also have this issue. I have quite a few columns on a pivot table I don't want to appear on the index view of a relationship, for example a notes column which contains a lot of text looks horrible in the index view.

It seems any field within the array return by the fields method doesn't respect any of the visibility methods. hideFromIndex, onlyOnForms etc etc.

Any time frame on when this will be fixed? It's been like this for a long time.

**Comment by henninghorn** [comment]
+1

I have a JSON column on a pivot table, and all the data is pushed into the row:

![pivot](https://user-images.githubusercontent.com/742607/73658923-8a256780-4695-11ea-845c-42024fc8f4ce.png)

This is a especially weird behaviour, since a code field should not be displayed on a index listing:

> **Code Fields On The Index**
> By default, Nova will never display a Code field on a resource index listing.

Adding onlyOnForms() or other variants doesn't have any effect.

**Comment by aniket-magadum** [comment]
Does this have any workaround

**Comment by gaelreyrol** [comment]
Unfortunately I couldn't find anything :/

**Comment by roberto-mgquadro** [comment]
Try putting this:
```
->canSee(function () use ($request) {
  return !!$request->editing;
})
```
in place of
`->onlyOnForms()`

**Comment by lasseeee** [comment]
Bug still present on Nova v3.0.1. Hack above works.

**Comment by lasseeee** [comment]
Still present on Nova v3.1.0

**Comment by davidhemphill** [comment]
@lasseeee A PR fixing this issue has been merged. This has been fixed and will be included in the next release. 👍

**Comment by ilvalerione** [comment]
Hi @davidhemphill, I waited the last release to check this behaviour. It steel present in 3.2.0

I have a belongsToMany relation between `Project `and `Channel` with two pivot fields cated as `array` in the eloquent pivot model.

Pivot model:
```php
class ChannelProject extends Pivot
{
    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = true;

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'configuration' => 'array',
        'notifications' => 'array',
    ];
}
```

The relation in the Project class:
```php
/**
     * The channels that belong to the project.
     *
     * @return BelongsToMany
     */
    public function channels(): BelongsToMany
    {
        return $this->belongsToMany(Channel::class)
            ->using(ChannelProject::class)
            ->as('connection')
            ->withPivot('id', 'configuration', 'notifications');
    }
```

The relation in the Channel class:
```php
/**
     * The projects that belong to the channel.
     *
     * @return BelongsToMany
     */
    public function projects(): BelongsToMany
    {
        return $this->belongsToMany(Project::class)
            ->using(ChannelProject::class)
            ->as('connection')
            ->withPivot('id', 'configuration', 'notifications');;
    }
```

I'm using an invokable class (`ChannelProjectFields`) to define pivot fields:

```php
/**
     * @return array
     */
    public function __invoke()
    {
        return [
            Code::make('Configuration')->json(),
            Code::make('Notifications')->json(),
            /*Text::make('Configuration'),
            Text::make('Notifications'),*/
        ];
    }
```

Using `Code` fields they aren't showing in the index view and in the edit view they appears as `null`:

![code-edit](https://user-images.githubusercontent.com/13559278/78253849-53cd6280-74f5-11ea-8f37-7147b3d1756c.png)

Using Text fields they are shown in the index view as text:

![text-view](https://user-images.githubusercontent.com/13559278/78254708-96436f00-74f6-11ea-91eb-862b92e439ca.png)

But in the edit view an empty input field is shown:

![text-edit](https://user-images.githubusercontent.com/13559278/78254765-a9eed580-74f6-11ea-8926-7337ea1b1d22.png)

Maybe because in the eloquent pivot model there's a `cast` as `array`.

Thank you for your support.
