### ISSUE TITLE
Call to a member function gt() on string

### ISSUE THREAD

**Issue by stonkeep** [laravel/nova-issues#2208]
- Laravel Version: 5.8
- Nova Version: 2.7.1
- PHP Version: 7.3
- Database Driver & Version: SQLSserver 2012
- Operating System and Version: Windows 10
- Browser type and version: Chrome 68
### Description:

When I try to update a big json field I get the follow msg 
```
Call to a member function gt() on string
Symfony\Component\Debug\Exception\FatalThrowableError
C:\****\nova\src\Http\Controllers\ResourceUpdateController.php
```

Anyone have a idea?

**Comment by jbrooksuk** [comment]
The `gt` method is called on the `getUpdatedAtColumn` column.  Have you changed this in your model?

**Comment by zareismail** [comment]
Hi.
I think this is not bug. Because your update column is string. 
Nova using restriction for stop editing in same time. You can disable dis feature on. Your resource by add *'$trafficCop = false'* or convert your 'upated_at' into carbon lnstance.
Reffer here [preventing-conflicts](https://nova.laravel.com/docs/2.0/resources/#preventing-conflicts)

**Comment by aghayeff** [comment]
I think it is a bug. Receive this error when use Mutators in model:


    public function getUpdatedAtAttribute($value)
    {
        return (new Carbon($value))->format('d M Y, H:i');
    }

**Comment by newtonkim** [comment]
got this error on 
 if($user->two_factor_expires_at->lt(now()))
