### ISSUE TITLE
403 on running actions against status of model

### ISSUE THREAD

**Issue by bobbybouwmann** [laravel/nova-issues#2221]
- Laravel Version: 6.6.2
- Nova Version: 2.9.2
- PHP Version: 7.3.11
- Database Driver & Version: n/a
- Operating System and Version: n/a
- Browser type and version: n/a
- Reproduction Repository: n/a

### Description:
We currently have an action defined that may only run whenever our model has a certain status. We defined this check in both actions array of the Nova Resource.
```
(new SendBillReminderAction())
    ->canSee(function () {
        return $this->resource instanceof Bill
            && in_array($this->resource->status, Bill::STATUSES_UNPAID, true);
    }),
```
This just returns a boolean if the statement matches. Now the problem is that whenever the action is available in our table and execute the action we get a 403 back. If I replace the above statement in the `canSee` callback to just `return true;` it works fine. However, with the above check, it simply doesn't work and gives a permission denied error. 

After some debugging and adding logs using the following code we found some weird behavior of the actions
```
->canSee(function () {
    Log::info('id: ' . $this->resource->id);
    Log::info('status: ' . $this->resource->status);
    Log::info('unpaid: ' . (in_array($this->resource->status, Bill::STATUSES_UNPAID, true) ? 'true' : 'false'));

    return $this->resource instanceof Bill
        && in_array($this->resource->status, Bill::STATUSES_UNPAID, true);
}),
```
When running the action again we got the following results in the logs
```
[2019-12-12 08:14:41] local.INFO: id:
[2019-12-12 08:14:41] local.INFO: status:
[2019-12-12 08:14:41] local.INFO: unpaid: false
[2019-12-12 08:14:41] local.INFO: id: 1
[2019-12-12 08:14:41] local.INFO: status: unpaid
[2019-12-12 08:14:41] local.INFO: unpaid: true
```
This tells us that first an empty model is tried, which gives a false response here. I believe this is the bug here that it first checks against an empty model. Because of that the status doesn't match and the authorization is not allowed. 

Let me know if you need any more information to reproduce this.

**Comment by sebsel** [comment]
I have almost the exact problem, and adding the Log as stated also give me an empty model.

```
[2019-12-20 12:18:50] local.INFO: id:
[2019-12-20 12:18:50] local.INFO: status: pending
[2019-12-20 12:18:50] local.INFO: importable: false
```

Laravel 6.5.2, Nova 2.7.1, PHP 7.4.0.

**Comment by skoyah** [comment]
I was also thinking in a way of how to solve this problem @bobbybouwmann .

The thing here is that when you run an action it sends a request to an endpoint to get all the Actions available for the resource class and not the actual instance you are trying to check.
Since there is no resourceId during this request, your canSee will actual returns false, hence the 403 forbidden because the data returned from that api request will not contain the filter you want to use. 

My only current workaround is to use the action on the detail view and that way I am able to do the following:

<img width="850" alt="Screenshot 2019-12-22 at 01 30 00" src="https://user-images.githubusercontent.com/36083448/71315328-985b5380-245a-11ea-9089-5a652277ada9.png">


This way if there is a `resourceId` I can use the instance in question using the `fiindModelQuery()` method in my custom policy method.

Otherwise it returns true. But since it will not be displayed on the index view, I am not having problems in returning true.

But I agree that allowing to use the current instance on the action will help us a lot, kinda like we already to in authorization fields.

**Comment by bobbybouwmann** [comment]
@skoyah Thanks for thinking with me. The detail page is not a problem for me at least. The only problem I have is on the index page. Still looking for a solution.

**Comment by bobbybouwmann** [comment]
@davidhemphill Can I get some eyes on this?

**Comment by bobbybouwmann** [comment]
@jbrooksuk @davidhemphill Is it possible to get some eyes on this? Just a message that this is going to be an issue till the end of days is also fine.

**Comment by chrispage1** [comment]
Further to @bobbybouwmann I have raised issue #2308 which I believe is the same problem.

@jbrooksuk @davidhemphill a fix would be appreciated. While @skoyah approach is plausible it is very much a temporary workaround to this issue. Thanks!

**Comment by marijoo** [comment]
Also have this problem. A fix would be very welcome.

**Comment by vladski** [comment]
Same issue. Please fix it. Thanks.

**Comment by khalil-htme** [comment]
This was an issue that I had to deal with many months ago, and it seems like its still part of Nova until now #2010 

What is happening, is that the action model is not referencing/pulling the instance properly or ever at all, because if you try to debug this issue, and pull the model (use incognito chrome), you will notice it is almost always NULL, which is weird, because sometimes it does work if you are saving cookies? in normal chrome? this bug puzzled me for months and I gave up working on it entirely.

My **VERY VERY UGLY** work around it, is to take the ID from the URL, and pull the resource and canSee based on that.

I actually did try to modify Nova action files, and there i could not find a proper way to make it work otherwise.

If anyone ever found a hack for it, let me know please

**Comment by jbardnz** [comment]
As far as I can tell the issue is that the `$request->findModelQuery()` is sometimes empty on certain requests, I'm not 100% sure if this is the correct way to handle this but the following solution seems to work well for me:

```
->canSee(function () use($request){
    return $request->findModelQuery()->first() ? $request->findModelQuery()->first()->status === 'Active' : true;
})
```

**Comment by khalil-htme** [comment]
@jbardnz yeah that is what we are supposed to be doing, but back few months ago it was doing some wacky unstable results, when the issue was raised in #2012 it was added to the current issues that needed fixing.

Anyways a more detailed solution was raised in #1943 thank you and good luck to everyone!

**Comment by tsummerer** [comment]
I found that when I submitted the Action from the Detail View, my `canSee` function received an `ActionRequest` rather than a `NovaRequest`. 

The ActionRequest did not include anything in the `resourceId` property, so `findModelQuery()` did not return the current model. 

On an `ActionRequest` the current model id(s?) are in the `resources` property.

So my workaround has been to check the type of Request, and then, if needed, pass the `$request->resources` to `findModelQuery`:

```
(new Actions\ExportRoundData)
->confirmText('Export round data?')
->confirmButtonText('Export')
->onlyOnDetail()
->canSee(function($request){
    if ($request instanceof ActionRequest){
        $q = $request->findModelQuery($request->resources);
    }else{
        $q = $request->findModelQuery();
    }
    
    return optional($q->first())->active;
}),
```


I have not tested this against an Index view action yet.

**Comment by GDanielRG** [comment]
This really needs attention seems to me like its a very requested and needed feature

**Comment by ljmoleiro** [comment]
What works for me

 return [
            (new LogsDiffAction($this->id))
                ->onlyOnTableRow()
                ->confirmButtonText('Revert Change')
                ->canSee(function ($request) {
                    if($this->id)
                        return 'updated' == $this->description;
                    if($request->has('resources'))
                        return true;

                    return false;
                }),
        ];

**Comment by lptn** [comment]
I also had this issue, there is a method `canSeeWhen` that doesn't help on details page:

`(new CancelUserAction())->canSeeWhen('cancel', $this),`

We use `CancelUserAction` with `public $onlyOnDetail = true;` so it's basically hidden on details page even if a policy returns `true`.

All these methods:
 - canSee
 - canSeeWhen
 - canRun

should support all types of requests/context
 - resource index page
 - resource details page
 - index as subresource
 - `ActionRequest` (accept POST request from Action)

**Comment by skoyah** [comment]
By the way, I really don't like to use `$request->findModelQuery()` all the time.

If I want to get the current resource in different actions, this becomes a performance issue since for every action I'm performing the same query everytime.

**Comment by alberto-bottarini** [comment]
I dream for a `->canSee(function (User $user, Model $model) { ... }`

**Comment by alberto-bottarini** [comment]
My silly solution is to throw a `danger` in my handle method:

```php
        if ($model->active) {
            return Action::danger('This profile is already active!');
        }
```

**Comment by crynobone** [comment]
I'm working on a possible solution based on laravel/nova#1035

```php
(new Actions\MarkAsInactive)->showOnTableRow()->showOnDetail()->canSee(function ($request) {
                return $request instanceof ActionRequest
                    || ($this->resource->exists && $this->resource->active === true);
            }),
```

`$request instanceof ActionRequest` is required to handle running `POST /{resource}/action`.

**Comment by erndaleiht** [comment]
@crynobone

That saved my day 👍

**Comment by crynobone** [comment]
```php
(new Actions\MarkAsInactive)->showOnTableRow()->showOnDetail()->canSee(function ($request) {
    return $request instanceof ActionRequest
        || ($this->resource->exists && $this->resource->active === true);
}),
```

Unfortunately we're stuck with `$request instanceof ActionRequest` for the current series as the current behaviour that we need to respect is that "Action can only be run if it can be seen". Changing that would potentially causing a huge breaking change to some customers

**Comment by trippo** [comment]
I solved with:
```
->canSee(function ($request) {
                    return  $this->resource->id ? $this->resource->isShippable() : true;
                })
```

**Comment by AshutoshJha15** [comment]
i solved with ` return [
            (new ViewResponseAction())->onlyOnTableRow()->canSee(function () {
                return $this->r_f_p_status == null ? true : $this->r_f_p_status == \App\Models\RFP::SENT;
            }),
            (new SendRFPAction())->onlyOnTableRow()->canSee(function () {
                return $this->r_f_p_status == null ? true : $this->r_f_p_status == \App\Models\RFP::DRAFT;
            }),
        ];`

**Comment by erichowey** [comment]
@tsummerer 's solution works perfectly, but it's super ugly. This really needs to be addressed in Nova 4.

**Comment by mnsuccess** [comment]
> I'm working on a possible solution based on laravel/nova#1035
> 
> ```
> (new Actions\MarkAsInactive)->showOnTableRow()->showOnDetail()->canSee(function ($request) {
>     return $request instanceof ActionRequest
>         || ($this->resource->exists && $this->resource->active === true);
> }),
> ```
> 
> `$request instanceof ActionRequest` is required to handle running `POST /{resource}/action`.

Awesome it works for me

**Comment by baszach** [comment]
Does this problem still exist in Nova 4 or is it even viewed as a problem by the team?

There are some good solutions here (e.g. ` $request instanceof ActionRequest || ($this->resource->exists && $this->resource->active === true);`) but it's cumbersome to always add this part.

This is one of the things that's annoying in Nova. Laravel has such a great documentation while many concepts in Nova can only be found after searching a lot in **this issues repo**.

**Comment by janzankowski** [comment]
> Does this problem still exist in Nova 4 or is it even viewed as a problem by the team?

The problem still exists in Nova 4.

Laravel Nova team: you said that "_[c]hanging that would potentially causing a huge breaking change to some customers_". This is understandable - but it'd help if you also say that you'll never fix it for this reason, if that's true / likely. People on this thread and others in the future will know that we just have to live with it instead of hoping for a fix in new Nova versions.

**Comment by crynobone** [comment]
@janzankowski We not reopening an old issue. So, if you reporting a bug please submit a new bug report with full reproducing code.
