### ISSUE TITLE
Make Nova Customizable

### ISSUE THREAD

**Issue by jawittdesigns** [laravel/nova-issues#2234]
After looking at other issues relating to the customization of Nova, I really think it would be great if you could make Nova more customizable. I seen in other related issues some good ideas and requests, unfortunately it seems like you are unwilling to do anything towards making Nova customizable. 

This is the one point that is making me reluctant to ever use Nova with anything that's not a personal or in house project. On the client side of things, clients want their projects to be customized to their specifications and with Nova a lot of these kinds customizations just aren't possible as it stands.

It real a real shame though, Nova a a really good system. It just isn't ready for real world applications in it's current state. So I'm asking again, would you consider making Nova more customizable.

**Comment by jbrooksuk** [comment]
Nova is already highly customisable, as you can already:

- Create custom themes
- Customise the translations
- Create custom tools
- Create custom cards

**Comment by bernhardh** [comment]
@jbrooksuk:
Thats right. But you still can't do such simple things as changing the style of any part of nova in a realistic way. See

- #1710 last bullet point
- #2218 
- #617
- #1892 
- ... and probably a lot more

davidhemphill commented on 23 Sep 2018 on #617 (over 1 year ago)

> Looking into automatically appending the Vue component's tag name to its element classList. So a <ResourceTable> component would have resource-name added as a class. No guarantees, but if it doesn't break anything or slow rendering down significantly it could get added.

No progress. I am not an anyoing person, but if a lot of PAYING CUSTOMERS want a really simple function, where you have already a solution for it, I just can't understand why you just not add it.

**Comment by davidhemphill** [comment]
If Nova doesn't do what is needed to satisfy the requirements of your project, or the progress on Nova's features and bug fixes doesn't meet your satisfaction, then it wouldn't be wise to use it. There's lots of options and everyone should use the one the best meets your needs!

However, as I mentioned in the similar comment you made, there's a PR to solve this issue in review right now. :🤙

**Comment by bernhardh** [comment]
Nova is currently the best solution right now, thats why I want to get the maximum out of it. Good to read, that there is a progress. I was just a bit frustrated, since you already said one year ago, that you have a solution, but nothing happens afterwards. I hope you understand my reaction. Thank you.

**Comment by bruno-rodrigues** [comment]
Any updates @davidhemphill ?

**Comment by Kainnan** [comment]
> If Nova doesn't do what is needed to satisfy the requirements of your project, or the progress on Nova's features and bug fixes doesn't meet your satisfaction, then it wouldn't be wise to use it. There's lots of options and everyone should use the one the best meets your needs!
> 
> However, as I mentioned in the similar comment you made, there's a PR to solve this issue in review right now. :

What a bad way to reply someone that are trying to improve your project. I've seen others replies of you, i can't even imagine how hard is to you accept some kind of feedback. Personally, i really haven't done a good job of research before to buy one license from your company. If i had searched well, i definely wouldnt.

**Comment by TheSETJ** [comment]
I agree with more control over customizing Nova.

For example, I need a `Text` field to be displayed with a specific text-color or text-decoration based on its value. It's not a rational way to create a whole new custom component or new custom field when such a simple change can be done by passing a `class` or `style` using `withMeta` method (if you've supported those as valid `extraAttributes`). Especially when extending a Nova component is not possible easily (because you don't support that either).

Nova is a tool to let _me_ build _my_ admin panel. So it should let me apply _my own look and feel_ easier.
