### ISSUE TITLE
Need manual scrolling to the top of the page

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#2242]
- Nova Version: 2.9.2
- Browser type and version: Chrome v.79.0.3945.88

### Description:

I have 100+ resources in sidebar menu and users need scroll down to see bottoms menu element.
After click link in scroll down scrolling to the top of the page does not occur and the content of the resource is not displayed on the screen. Manual scrollup is required. This annoys users.

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/38257723/71439183-b1d5f700-2709-11ea-833a-438e157fcd77.png)

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
Feel free to add the following:

```js
Nova.addShortcut('t', () => {
  window.scrollTo(0, 0)
})
```

**Comment by Arndeverafter** [comment]
After the Nova [v4.21.0 (Silver Surfer)](https://nova.laravel.com/releases/4.21.0) update, it was said that this issue was fixed, I tried testing this in my Mac Pro and it was scrolling to top for each navigation page. the client kept on saying this was not the issue on their end, i switched to my Windows laptop, that's when i experienced what the client was saying. Hopefully you guys get to test this and address the issue. 

Since there is no way to hook into the router events with Inertia i have had to edit the compiled JS file in `/public/vendor/nova/app.js` in the `inertia:navigate` event registration by adding `window.scrollTo(0,0)` within the `async` block.
