### ISSUE TITLE
Cache do not appear in Telescope

### ISSUE THREAD

**Issue by kamilkozak** [laravel/nova-issues#2274]
- Laravel Version: 5.8.36
- Nova Version: 2.9.3
- PHP Version: 7.3.13
- Database Driver & Version:
- Operating System and Version: Ubuntu 18.04
- Browser type and version: Chrome 79

### Description:
Information about cache (missed, set, hit) and also ajax requests do not appear in telescope v2.1.3

### Steps To Reproduce:
Use cache facade and look at the "Cache" tab in the telescope.

**Comment by jbrooksuk** [comment]
Nova requests are excluded by default because they’re not apart of _your_ app as such.

**Comment by stancl** [comment]
@jbrooksuk This is somewhat related and I don't want to create a new issue because it's not a bug per se.

Is there any way to explicitly include Nova stuff in Telescope? My use case is that I'm using Telescope to inspect Mail. And that works flawlessly for local development with the `log` driver for mail. But I also send Mail from events triggered by Nova actions. It would be really useful to be able to view this in Telescope.

Thank you.
