### ISSUE TITLE
Action Fields loading index when i am using onlyOnDetail()

### ISSUE THREAD

**Issue by bsormagec** [laravel/nova-issues#2298]
- Laravel Version: 5.8.36
- Nova Version: 2.9.4
- PHP Version: 7.3.13
- Database Driver & Version:
- Operating System and Version: OSX
- Browser type and version: Chrome latest
- Reproduction Repository: https://github.com/###/###

### Description:
I am using select fields from database on my fields and filling options method from database. And i am setting onlyOnDetail method when adding action to $actions property on Resource, but when i check queries for index of this resource. its working already on index and we can't use eager loading here. I think when Action using onlyOnDetail method its not need to work on index of resource.

### Steps To Reproduce:
It will be stop to call on ResourceIndex Vue file when onlyOnDetail set related resource.

**Comment by DmitrySur** [comment]
The problem is really relevant, at the moment I found for myself such a temporary solution for the fields, I think it will work for actions:
`
            Select::make('fio')->onlyOnForms()->hideFromIndex()->options(function () {
                $textUrl = url()->previous();
                if (strpos($textUrl, 'new?') or strpos($textUrl, 'edit?')) {
                    return [
                        '11111',
                        '22222'
                    ];
                }
`

**Comment by bsormagec** [comment]
I have really big action queries and its working for each row and my index pages working slow :(

**Comment by florentpoujol** [comment]
I have just noticed this behavior after upgrading from v2.10.1 from v2.12.0, yet I confirm that it happens since before v2.9.  
I am still on Laravel 5.8, so I can not update to v3 yet.

To be clear, the issue is that *when loading a resource index list*, all actions defined for that resource gets instantiated and their `fields()` method is called, and that **for every row** displayed.

If you do SQL requests in the `fields()` method to populate a select field for instance, this is obviously not needed/wanted at all.

The action's visibility modifier (`onlyOnDetails()`, etc...) do not change that behavior.

Related issue https://github.com/laravel/nova-issues/issues/2509 with a workaround to return early in `fields()` when you actually do not want the action to run at all on the index.
