### ISSUE TITLE
Contributing to Nova

### ISSUE THREAD

**Issue by albalooshi** [laravel/nova-issues#233]
Is there a way for people to contribute to Nova source directly and not using tools or cards? It it would be neat if we can do pull requests to Nova and help it grow..

**Comment by cloudstudio** [comment]
Nova is not open source, so i don't think so

**Comment by antonkomarev** [comment]
@cloudstudio Nova is Open Source Software, but not Free Open Source Software :}

I suppose Taylor wouldn't give an access to source code, because next major release (v2.0) will be downloadable from repository then.

**Comment by jwjcmw** [comment]
Since it's not free, I'm guessing that the `"license": "MIT",` in the composer.json is an oversight.  That should really be `proprietary`.

**Comment by ryanmortier** [comment]
It's too bad license holders didn't have private access to the repo like the way `Laravel Spark` is setup.

**Comment by zeroseed** [comment]
Yeah , we bought the license ,we should know how about the progress of development or maybe can contribute some PR, because currently everyday i always login to nova site then refresh the release page, always found it 1.0.6 😂
Always curious : when this bug will be fixed ? When the next version released ?
So if we have private repo, we will know the progress

**Comment by davidhemphill** [comment]
We're working on this.

**Comment by mkarnicki** [comment]
Since the other thread #964 has just been locked to contributors, I would urge the team to prioritize addressing this issue. I totally understand you may not be open for *feature* contributions, but a repository would at least allow for submitting PR (better than just filing issues) - I'm guessing quite a few of the issues are just minor fixes that you could review and accept, similarly to what is occasionally done for Spark. Thanks.

**Comment by dillingham** [comment]
@everyone you can add yourself to the nova repo
https://nova.laravel.com/settings#github

**Comment by YassineGherbi** [comment]
> you can add yourself to the nova repo
> https://nova.laravel.com/settings#github

What does this exactly do??

**Comment by zek** [comment]
> you can add yourself to the nova repo https://nova.laravel.com/settings#github

I guess this is not an option anymore
