### ISSUE TITLE
Readonly and withMeta not respected and overwritten

### ISSUE THREAD

**Issue by sirikkoster** [laravel/nova-issues#2411]
- Laravel Version: 6.18.0
- Nova Version: 2.12.0
- PHP Version: 7.3.10

### Description:
withMeta is not respected

### Steps To Reproduce:

Field with placeholder "0,0"
```php
->withMeta([
	'extraAttributes' => [
		'placeholder' => '0,0'
	]
])
```

Field readonly with Fieldname as placeholder
- It doesn't matter what the order of the definition is.
```php
->readonly(true)
->withMeta([
	'extraAttributes' => [
		'placeholder' => '0,0'
	]
])
```

Field readonly with the correct placeholder
```php
->withMeta([
	'extraAttributes' => [
		'placeholder' => '0,0',
		'readonly' => true
	]
])
```

**Comment by jbrooksuk** [comment]
What field is this for?

**Comment by sirikkoster** [comment]
> What field is this for?

Sorry, it's for Number
- Laravel\Nova\Fields\Number;

**Comment by bing8u** [comment]
```php
Number::make('Name')->withMeta(['readonly' => true])
```
I know it's OK. Try it.

**Comment by sirikkoster** [comment]
> ```
> Number::make('Name')->withMeta(['readonly' => true])
> ```
> 
> I know it's OK. Try it.

@bing8u This is not the point, the readonly function is not respected. As shown above i'll know how to make a workaround.

@jbrooksuk I think it's the order of merging the array's for the withMeta data

**Comment by bing8u** [comment]
```php
Image::make('Image')->required()
```

@sirikkoster the same is true

**Comment by sirikkoster** [comment]
> ```
> Image::make('Image')->required()
> ```
> 
> @sirikkoster This field is not filled in. It can also be submitted

@bing8u I think this is an different issue

**Comment by jbrooksuk** [comment]
This is because `Metable` uses `array_merge` instead of `array_merge_recursive`, so the `extraAttributes` children are overwritten each time.

I'm not sure of the impact of changing the behaviour, @davidhemphill?

**Comment by davidhemphill** [comment]
I'm confused as to what exactly the issue is. 😅  

The `readonly` method has precedence over setting the attribute manually using the `withMeta` method. That means when using `withMeta` to make the field not-readonly (`['extraAttribute' => [ 'readonly' => false]]`) and using the `readonly` method to make the method readonly (`readonly()`), the field will actually be readonly. This is by design.

Other than that, I don't understand what the actual problem is.

As an aside, I really dislike the `withMeta` functionality of fields and it will probably be removed in the next major series.
