### ISSUE TITLE
Request: what can we expect from the Nova team?

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2431]
Dear Nova team,

I've been working with Nova for about a year now and i have a request. What can we expect from you guys in terms of support, communication & fixing bugs? 

I will try to explain. 

A year ago issues were solved slowely. Then i saw a teammember picking up the slack, there were about 60+ issues left, but the last couple of weeks it seems working on issues is slowing down again. So instead of 'us' demanding service, what can we expect from the Nova team?

I've posted several bugs and requests. Sometimes i get feedback, other times an issue is just closed. That leaves me guessing to what is happening. Is the issue fixed (for the next release)? Or is it ignored? Would be nice to have some insights.

Finally, some bugs seem to be open for long periods of time (example #2023). Right now that is not a big issue (still in development), but the project will launch soon. And then it's hard to explain to a customer that a bug is open for several months. 

Could you please give some insights in what we can expect from the Nova team?

**Comment by jbrooksuk** [comment]
@preliot when I joined the Laravel team my first task was to work through the backlog of Nova. I took the issues down from over 200 to under 60 in the first two weeks (most of that was just general cleaning). My current focus is now on Laravel Forge, but I've also been finding time to work on Nova maintenance in between that.

A new Nova version is released every second Tuesday and we recently made a v3.0 release (with a few patch releases since then). Nova is very much in active development.

When we merge a PR in [laravel/nova](/laravel/nova) and it's linked to an issue, it'll automatically close the issue. We don't follow up on those issues because if you have access to the Nova repo, you'll see that the PR was merged within the issue itself.

We do actively keep an eye on all issues, but realistically we're unable to comment on and fix everything in one go. @davidhemphill and I are the two people who actively maintain Nova day to day, plus we have support to attend to.

**Comment by ziming** [comment]
Just an idea, maybe in addition to auto close the issue when the PR is merged, auto post a comment on it as well that it is resolved by PR # [Some Number]. :)

Thank you for the hard work so far

**Comment by jbrooksuk** [comment]
@ziming GitHub does this for us, see https://github.com/laravel/nova-issues/issues/2416

![image](https://user-images.githubusercontent.com/246103/76517137-a5358500-6454-11ea-9518-9d9fa84a31a7.png)

Note that you need to be a member of the **laravel/nova** repository to see this.

**Comment by ziming** [comment]
Nice!

**Comment by preliot** [comment]
> Note that you need to be a member of the **laravel/nova** repository to see this.

That would be great to see, but how does one become a member?

**Comment by jbrooksuk** [comment]
https://nova.laravel.com/settings#github

**Comment by preliot** [comment]
Did not know this... this is great! Thanks @jbrooksuk
