### ISSUE TITLE
Search only returning 200 results from Resource

### ISSUE THREAD

**Issue by jhull** [laravel/nova-issues#2452]
Latest version of everything. Using Scout/Algolia to search. One Resource has 311 rows, but Nova only returns 200 of them. Can't find the setting where it's limiting that.

In the Algolia Dashboard, searching for same returns all 311. I see a `count?` query in the Network tab returning this: `{"count":200}`.

**Comment by davidhemphill** [comment]
You can override the `initializeQueryUsingScout` method to customize the amount of results returned.

What's the use-case for returning more than 200 results?

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by jhull** [comment]
Use-case is using Laravel Nova to clean-up database of 10s of thousands of entries in one model. Searching with Nova, I would like to filter those thousands by one column -- sometimes resulting in over 200 entries.

Overriding the above worked great--might be something you could set in a config file instead.

**Comment by davidhemphill** [comment]
Interesting. Thanks for letting us know. We could probably make that a separate method or property so you don't have to reimplement the whole method. 👍
