### ISSUE TITLE
"Setting tz to application tz before query for metrics" didn't get applied in Nova 3.0 and 3.1

### ISSUE THREAD

**Issue by iamoat** [laravel/nova-issues#2460]
- Laravel Version: 7.3.0
- Nova Version: 3.1.0
- PHP Version: 7.2
- Database Driver & Version: SQLite
- Operating System and Version: Ubuntu 18.04
- Browser type and version: Chrome
- Reproduction Repository: https://github.com/###/###

### Description:

"Setting tz to application tz before query for metrics" which was applied in 2.x but not in 3.x.

### Steps To Reproduce:

Create trend metric and compare with the value metric. 

Today is Mar 27, 2020. We only have data till Mar 27, 2020. 

The trend metric show data of Mar 27 - 28, 2020. 
 
<img width="1021" alt="Screen Shot 2020-03-27 at 20 44 15" src="https://user-images.githubusercontent.com/1286835/77762245-cceb3680-706b-11ea-850f-c7d98d989ccd.png">

**Comment by vladski** [comment]
The issue here is that Nova assumes that dates in database are stored as UTC. Nova, when creating trend query, calculates offset between current user timezone and UTC and applies it to DB query. 

We need a way to tell Nova what timezone are the model datetime DB columns. Then offset should Nova calculate between current user timezone and model timezone - not UTC.

**Comment by daniel-wright** [comment]
I am experiencing the same/similar issue. However, I feel that vladski is wrong as this is a common misconception. The timestamps in the database SHOULD ALWAYS be on the same timezone, preferably UTC. Otherwise, there is no way to query across multiple users entries accurately. 

For example, if 2 different users create records at exactly the same time but from timezones on the opposite sides of the planet, the timestamp in the database should be EXACTLY the same (like Nova currently does). Then, when querying or displaying the dates, you would adjust the offset based on the users timezone.

In my specific case, to ensure the user displays dates to the exact timezone they choose, I am currently setting the users timezone as the documentation suggests in the NovaServiceProvider.

```php
public function boot() {
  parent::boot();

  Nova::userTimezone(function(Request $request) {
    return $request->user()->timezone;
  });
}
```

Now, when creating or updating records the timestamps such as created_at and updated_at are correctly storing as UTC timezones. However, when pulling the count with metrics, Nova is using the users timezone without applying the offset. 

For example, I created a new User record at 2:00 PM PST, which was correctly added to the database table as UTC timestamp = 2020-04-20 21:00:00. Then five minutes later, I ran my total user count metric for the past 30 days and the query log shows:
```mysql
select count(users.id) as aggregate from users where created_at between '2020-03-21 14:05:00' and '2020-04-20 14:05:00'
```
Because I am UTC-7, it should add back the 7 hours before querying. Instead, my metrics will always be off by 7 hours.

It appears that in the file Metrics/Trend.php, the aggregate function (around line 475) is using a TrendDateExpressionFactory class to apply the offset. However, in Metrics/Value.php, the aggregate function (around line 105) is not applying the same sort of offset. If I had to guess, this is where is the issue will be addressed by the Nova masters ;)

**Comment by vladski** [comment]
Agree, timestamps in DB at the same moment are the same regardless of user timezone. Data-time is formatted in application timezone set in config('app.timezone'). 

However Trend metric is applying offset in hours to DB query that is incorrectly calculated in Nova/Metrics/TrendDateExpression.php at line 66:

```
return (new DateTime(
    Chronos::now()->format('Y-m-d H:i:s'),  // here the application timezone is ignored !
    new DateTimeZone($this->timezone))
)->getOffset() / 60 / 60;
```

**Example:**
`config('app.timezone')`  => "Australia/Sydney"
`Chronos::now()` => date: 2020-04-28 16:06:17.733328 Australia/Sydney (+10:00)

DB timestamp at this moment would be saved as '2020-04-28 16:06:17' by user from any place in the world.

**CASE 1:** Lets assume user's timezone is the same 'Australia/Sydney'
`new DateTime('2020-04-28 16:06:17', new DateTimeZone('Australia/Sydney'))`
    => date: 2020-04-28 16:06:17.0 Australia/Sydney (+10:00) 

**CASE 2:** Lets assume user is from Berlin 'Europe/Berlin'
`new DateTime('2020-04-28 16:06:17', new DateTimeZone('Europe/Berlin'))`
    => date: 2020-04-28 16:06:17.0 Europe/Berlin (+02:00)
`
In both cases is Nova applying incorrect offset +10 or +2 hours, and even when user is in the same timezone as DB timestamps! 

In case 1 logically the offset should be zero instead of +10 hr. 

in case 2 the the offset should be +8 hr instead of +2 hr as it should be calculated as difference between user and application timezones (application Db is in this case 8 hours ahead).

The mistake is that these offsets are differences between user timezone and 'UTC' because application timezone is ignored here. This would be correct only if application timezone is set to UTC or user is coming from UTC zone.

**My workaround:**

Place following to Providers/NovaServiceProvider.php inside booth() function:
```
public function boot()
{
    parent::boot();
    
    Nova::userTimezone(function (\Illuminate\Http\Request $request) {
        // only for metrics/trends api set user timezone to UTC
        if(stripos($request->path(), 'nova-api/metrics/') !== false) {
            return 'UTC';
        };
    });
    ....
}
```

**Comment by alekseyp** [comment]
Same issue with Metrics, my db is UTC and user is -4.

I've also tested on fresh install with homestead and it's the same behaviour.

@vladski thanks for temp workaround!

**Comment by vladski** [comment]
There is even more elegant workaround using Laravel makro I found [here](https://github.com/laravel/nova-issues/issues/2044#issuecomment-569567821). 

```
use Laravel\Nova\Metrics\TrendDateExpressionFactory;
use Laravel\Nova\Metrics\MySqlTrendDateExpression;

public function boot()
{
    parent::boot();

    TrendDateExpressionFactory::macro('mysql', function ($query, $column, $unit, $timezone) {
        return new MySqlTrendDateExpression($query, $column, $unit, 'UTC');
    });
    ....
}
```

**Comment by GDanielRG** [comment]
Such a shame that this is part of the core feature of a paid product and 3 years later that feature cannot be used properly. I just wasted 3 days of my time trying to figure out why my metrics where not working blaming the configuration and coding on me, to find out its a problem with the product itself.

**Comment by yangqi** [comment]
I believe the issue is in currentRange() and previousRange() in Value.php
```php
    protected function currentRange($range, $timezone)
    {
        if ($range == 'TODAY') {
            return [
                now($timezone)->today(),
                now($timezone),
            ];
        }
```
today() will set time to 00:00:00, which is incorrect with timezone calculated. This should be changed to following
``` php
    protected function currentRange($range, $timezone)
    {
        if ($range == 'TODAY') {
            return [
                now($timezone)->subHour(24),
                now($timezone),
            ];
        }
```
And similar for previousRange()
```php
    protected function previousRange($range, $timezone)
    {
        if ($range == 'TODAY') {
            return [
                now($timezone)->subDays(2),
                now($timezone)->subDays(1),
            ];
        }
```
