### ISSUE TITLE
Computed Currency Field regression in v3.2.0

### ISSUE THREAD

**Issue by DSpeichert** [laravel/nova-issues#2473]
- Laravel Version: 7.3.0
- Nova Version: 3.2.0
- PHP Version: 7.4.4
- Database Driver & Version: mysqlnd
- Operating System and Version: Linux
- Browser type and version: Chrome v80
- Reproduction Repository: -

### Description:

Visiting any resource (index or detail view) containing computed Currency field throws the following exception:
```
Brick\Math\Exception\NumberFormatException
The given value "" does not represent a valid number.
```

### Steps To Reproduce:
```
Currency::make('Amount', function () {
    return $this->items()->sum('price');
}),
```

### Affected Nova Versions

Nova v3.1.0: Works
Nova v3.2.0: Broken
Nova v3.2.1: Broken

**Comment by AlbinoDrought** [comment]
This is fixed in at least 3.4.0, for anyone like me that just sees this above:

![image](https://user-images.githubusercontent.com/852873/79396802-86ce1800-7f31-11ea-8240-765f5ca42e31.png)

Fixed versions seem to require ext-intl which was disabled on my local install, preventing composer from automatically updating to those versions. Try an explicit `composer require laravel/nova:^3.4` :sweat_smile:
