### ISSUE TITLE
Sortable shouldn't fire xhr request if there's one row.

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2504]
When there is one row clicking on the sortable buttons shouldn't fire a xhr request.

Would make sense if:

* cursor-pointer doesn't change
* no xhr request is fired

Explanation:

When you first search a table for a specific result, it's possible only one row is found. Then it wouldn't make sense to allow sorting.

**Comment by davidhemphill** [comment]
It seems unnecessarily pedantic to disable that functionality when there's only one row. 😄 

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by preliot** [comment]
I doubted if i should mention this indeed, doesn't seem to be that important. Nevertheless, now you know :-)
