### ISSUE TITLE
Hide search and create buttons on panel

### ISSUE THREAD

**Issue by thegregthomp** [laravel/nova-issues#252]
Is it possible to hide these tools for a relation within a resource? 
<img width="1401" alt="screen shot on 2018-08-27 at 11_57_08" src="https://user-images.githubusercontent.com/1554124/44670366-7aa9e580-a9f0-11e8-87e0-457c84153cc8.png">

**Comment by poxin13** [comment]
You can create a policy to hide resource actions https://nova.laravel.com/docs/1.0/resources/authorization.html#policies

**Comment by thegregthomp** [comment]
Thanks, this a good way of doing it. Preferably, I'd like to disable them for all users of any level but this may have to do.

**Comment by lucasromanojf** [comment]
For search, you can add the following to your Resource:

```
public static function searchable()
{
    return false;
}
```

Or give $search an empty array

**Comment by boyfromhell** [comment]
Add this to resource:
```
public static function authorizedToCreate(Request $request)
    {
        return false;
    }
        public function authorizedToDelete(Request $request)
    {
        return false;
    }

    public function authorizedToUpdate(Request $request)
    {
        return false;
    }
public static function searchable()
{
    return false;
}
```

**Comment by skalero01** [comment]
What if i want to hide the button only on the index page and not on the view page? I tried with the `authorizedToCreate` function but it works only the first time is loaded, after that it doesnt enter to the function anymore.

**Comment by MHassanSaqib** [comment]
> What if i want to hide the button only on the index page and not on the view page? I tried with the `authorizedToCreate` function but it works only the first time is loaded, after that it doesnt enter to the function anymore.

Did you find any solution for this scenario?

**Comment by skalero01** [comment]
> > What if i want to hide the button only on the index page and not on the view page? I tried with the `authorizedToCreate` function but it works only the first time is loaded, after that it doesnt enter to the function anymore.
> 
> Did you find any solution for this scenario?

Nope :/

**Comment by az-splatt** [comment]
This isn't a real solution. But..... because there doesn't seem to be a view dependant permissions way of governing the create button, ie. a permission that says for the create permission when viewing this parent class return no, all others yes. I think if you were to handle it with permissions that would be the way to do it. Alternatively and IMO this should already be a thing, `HasMany::make()` should have a -`>canCreate(false)` option. But that failing, here's some CSS.

````
div[dusk="parent-class-detail-component"] div[dusk="has-many-child-class-index-component"] a[dusk='create-button'] {
  display: none;
}
````

Credit for the concept here: https://vander.host/knowledgebase/software-development/using-css-selectors-to-hide-button-in-laravel-nova/

Obviously this is by-passable security wise, however, I don't want to outright block creation of new line items in the HasMany child class referenced from this class... I just want to block attempting to create them from this class because there's a dual belongs to relationship on the child class and the other class is authoritative, and can, depending on the users access level, dictate what entries can and can't be selected from the other belongsto class.

**Comment by azariah001** [comment]
This isn't a real solution. But..... because there doesn't seem to be a view dependant permissions way of governing the create button, ie. a permission that says for the create permission when viewing this parent class return no, all others yes. I think if you were to handle it with permissions that would be the way to do it. Alternatively and IMO this should already be a thing, `HasMany::make()` should have a -`>canCreate(false)` option. But that failing, here's some CSS.

````
div[dusk="parent-class-detail-component"] div[dusk="has-many-child-class-index-component"] a[dusk='create-button'] {
  display: none;
}
````

Credit for the concept here: https://vander.host/knowledgebase/software-development/using-css-selectors-to-hide-button-in-laravel-nova/

Obviously this is by-passable security wise, however, I don't want to outright block creation of new line items in the HasMany child class referenced from this class... I just want to block attempting to create them from this class because there's a dual belongs to relationship on the child class and the other class is authoritative, and can, depending on the users access level, dictate what entries can and can't be selected from the other belongsto class.

**Comment by ekazda** [comment]
> For search, you can add the following to your Resource:
> 
> ```
> public static function searchable()
> {
>     return false;
> }
> ```
> 
> Or give $search an empty array

The `searchable()` function is effective in making the search box disappear. However `public static $search = [];` still makes the search box appear.
