### ISSUE TITLE
availableForNavigation() still returning TRUE

### ISSUE THREAD

**Issue by issour** [laravel/nova-issues#2544]
- Laravel Version: 7.7.1
- Nova Version: 3.4.1
- PHP Version: 7.4.4

### Description:

Hi !
The resource remains visible on the navigation even if the function returns false

`public static function availableForNavigation(Request $request)
    {
        return $request->user()->isAdmin();
    }`

### Steps To Reproduce:

copy and paste this function in resource post : Posts stills visible. even returning false manually

 `public static function availableForNavigation(Request $request)
    {
        return $request->user()->isAdmin();
    }`
Thx !!!

**Comment by wfeller** [comment]
It looks like the static property is used rather than the method in ResourceManager :                 https://github.com/laravel/nova/blob/c14a97d3ca9404951a1e69a5300c8f5cc0c70333/src/Tools/ResourceManager.php#L36

Should be `return $resource::availableForNavigation($request);` rather than `return $resource::$displayInNavigation;`

**Comment by mathd** [comment]
I have the same issue with Nova version 3.4.1, the workaroud for the moment is to downgrade to 3.4.0

**Comment by issour** [comment]
@mathd yes! that the solution for the moment :)

**Comment by issour** [comment]
hi @davidhemphill Can you please explain this issue ?
Many thx

**Comment by francauxach** [comment]
@issour Yeah, fixed in v3.5.0!
