### ISSUE TITLE
Relation Create/Edit from Details Page

### ISSUE THREAD

**Issue by dbpolito** [laravel/nova-issues#256]
When you're creating/editing a relation from `Details Page`:

1. There is no `Cancel` button to return to `Details Page`, you need to hit `Back` on `Browser`
2. When you click `Save`, if goes to the `Relation Details Page`, it would be better if you get redirected back to first `Details Page`.

**Comment by davidhemphill** [comment]
1. That's what the back button is for. I don't see a need to clutter up the UI with something already built-in and fundamental to the web.
2. No plans to change that. We want the context to always be about the most-recently created item.

**Comment by packytagliaferro** [comment]
@davidhemphill  

I agree with @beerbuddha . I understand you dont want to clutter up the UI but would be nice to navigate to where you want after save. I belive even Laravel Backpack allows this. Example:

I have 2 models Posts and Questions You can never create a Question without a Post. For this reason it would be nice to not show Questions on the left panel menu at all only Posts. Then from a Post detail you add questions and return to that Post detail. 

This scenario seems like a perfect time to allow that functionality. For my admins they dont want to look at a giant list of all Questions, they only care about the Post and questions associated with it.

**Comment by dillingham** [comment]
@packytagliaferro you're overlooking the big button "create & add another"

**Comment by packytagliaferro** [comment]
Thanks @dillingham, I guess I am a "big" dummy. I still agree though it would be nice to be able to alter the route after save because if they dont use the  big button "create & add another" the admin, in my opinion, would like to see where they started (parent detail).Just a thought. Seems like a few threads on the issues about this ability.

**Comment by beerbuddha** [comment]
@packytagliaferro @dillingham 
yes when the detail page is available or "accessible" to the user is creating - create and add helps.
But when relationships do not have a particular landers (so lets say a many to many searchable) in order to not break maybe passing a callback route to enforce certain landers after saving would be preferred because currently Nova is assuming that certain route are accessible after the creation of such relationship / or resource. (which is how i  managed to stumble on such problem)

**Comment by dillingham** [comment]
I think if you’re allowing users to create resources without letting them see it, you need to make a tool with your own form and hide the resource entirely from that user role.
