### ISSUE TITLE
Can't update column when using Custom Casts

### ISSUE THREAD

**Issue by hnphi** [laravel/nova-issues#2574]
- Laravel Version: 7.9.2
- Nova Version: 3.5.0
- PHP Version: 7.4.3

### Description:
When I use custom casts for column, I can't update column anymore from Nova form.

### Steps To Reproduce:
1. Create custom casts ([follow Laravel docs](https://laravel.com/docs/7.x/eloquent-mutators#custom-casts))
2. Use custom casts for a column.
3. Open Nova Edit page and try update value of column which have casts  (update 2 or 3 times).

**Comment by jbrooksuk** [comment]
I'm not able to replicate this using the JSON example given on the Laravel docs. Both getting and setting works for me.

**Comment by ryangjchandler** [comment]
I actually ran into this problem today. I have a custom cast that explodes a string from the database and returns a `Collection`. Nova was automatically running `implode` on that collection which resulted in a different string being displayed in the input.

I had to change my custom cast a tad to check whether the current request was for Nova or not, I added the following bit of code into my casts `get` method:

```php
if (request()->is('nova-api/*')) {
    return $value;
}
```

This is slightly annoying because now my cast has to have some knowledge of the current request, @jbrooksuk can you think of any way this could be worked around with Nova, perhaps some sort of method on the field that uses `getOriginal` instead of running it through the casts?

**Comment by peterfox** [comment]
@ryangjchandler I had the same issue. The way I fixed this was adding:

```php
public static function newModel()
{
    return tap(parent::newModel())->withCasts(static::$casts ?? []);
}
```
 to `app/Nova/Resource.php`

Then in each resource I can override the custom castable being used purely for Nova.

e.g. in `app/Nova/User.php` I can put:

```
public static $casts = [
        'my_json_column' => 'array',
];
```

This allows for reading/updating that behaves as it would have done.

I don't know if it's something with my castable that breaks Nova but it's been a difficult issue and I found this was the cleanest way to solve the issue.
