### ISSUE TITLE
View, Edit, Delete icons visible on HasMany relationship when Policy denies ability

### ISSUE THREAD

**Issue by 949mac** [laravel/nova-issues#2582]
- Laravel Version: 6.x
- Nova Version: 3.4 (tested on 3.5 too)
- PHP Version: 7.3

### Video Download:
[Nova-HasManyIssue.mov.zip](https://github.com/laravel/nova-issues/files/4588694/Nova-HasManyIssue.mov.zip)

### Description:
Using HasMany within a resource shows view, edit, delete icons even if policy is set on model

### Steps To Reproduce:
- [x] Create two models w/ corresponding resources
- [x] Give one model a hasMany relationship to the other
- [x] Create a policy on the related model
- [x] Observe when accessing resource directly, action icons respect policies ✅
- [ ] Observe when accessing resource via related resource (w/ HasMany field), action icons don't respect policies ❗

**Comment by ramcda** [comment]
This is a serious vulnerability that was never researched and still exists in the latest version of Nova.

**Comment by irfanhkm** [comment]
any recommended stable version for this issue?

**Comment by preliot** [comment]
Finally resolved this. The first thing i needed to realize was the related model policy is not used, because you are working with the relation (and not the related model). So you have to add additional methods to your policy to remove the buttons. Second issue was the edit button, this can only be removed by adding the `attach{Model}` method. This seems odd to me, but it works. 

```php
//removes main 'Attach button'
attachAny{Model}(User $user, model $model) 
{
 return false;
}

//removes delete button next to row
detach{Model}(User $user, model $model) 
{
 return false;
}

//removed edit button next to row
attach{Model}(User $user, Model $model1, Model $model2) 
{
 return false;
}
```
