### ISSUE TITLE
Translation: Resources Name uppercase instead of lowercase

### ISSUE THREAD

**Issue by orlyapps** [laravel/nova-issues#2610]
Hello,

this is a really small issue and only affects translations. But its a bit annoying for our customers.

The following translation
> No :resource matched the given criteria.

is used in the Index View

```
{{
__(‘No :resource matched the given criteria.’, {
     resource: singularName.toLowerCase(),
})
```

In the german language the resource name has to be uppercase instead of lowercase. Thats really small detail but non technical users always complain about these spelling mistake. 

I don't really know how this can be fixed so that it works in all languages.

Thanks! :)

**Comment by MazzMazz** [comment]
Can confirm - we have the same situation right now.

**Comment by schonhoff** [comment]
Same issue for me.

**Comment by jbrooksuk** [comment]
Please see https://github.com/laravel/nova-issues/issues/1144#issuecomment-658842802

**Comment by schonhoff** [comment]
It is not working in the cases I wrote above.
My de.json:
`"No :resource matched the given criteria.": "Kein/e :Resource entspricht den angegebenen Kriterien.",`

![image](https://user-images.githubusercontent.com/42345405/87569056-e4a40480-c6c6-11ea-8110-79cab558d717.png)

It is because of the .toLowerCase() in this particular case.
