### ISSUE TITLE
Cannot update relationship field if try to edit via relationship

### ISSUE THREAD

**Issue by mehranhadidi** [laravel/nova-issues#2652]
- Laravel Version: 7.13.0
- Nova Version: 3.6.0
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7
- Operating System and Version: OSX catalina 10.15.5
- Browser type and version: Chrome version 83.0.4103.61
- Reproduction Repository: https://github.com/###/###

### Description:
I have 2 models. ProductGroup & Product with relation Nv1. Each product group can have multiple products and each product belongs to a group. just a simple relationship. **HasMany** and **BelongsTo**.

When I try to edit a product resource using nova it works just fine. Everything works as expected.
When I try to edit the same product resource via product group it gets disabled and I cannot change it.
![image](https://user-images.githubusercontent.com/897774/83396769-27ef3000-a405-11ea-85d6-857e51e208f3.png)

Looks like the problem is related to **viaResource**.
My URL looks like this: 
edit?viaResource=product-groups&viaResourceId=28&viaRelationship=products

Any Idea?
Thanks

**Comment by mehranhadidi** [comment]
@taylorotwell @davidhemphill Any idea guys?

**Comment by JoseLuisRNP** [comment]
I think  it's the expected behavior, when you try to edit a resource from his relation this field is attach to him

**Comment by adnanchowdhury** [comment]
I'm having the same problem.

Laravel Version: 7.11.0
Nova Version: 3.6.0
PHP Version: 7.4
Database Driver & Version: MySQL 5.7
Operating System and Version: OSX catalina 10.15.4
Browser type and version: Chrome Version 83.0.4103.97 (Official Build) (64-bit)

**Description**:

I have a Question model with a 1:MorphMany relationship with Issues. 

Question.php (Question Resource)
```
MorphMany::make('Issues', 'issues')
```

Issue.php (Issue Resource)
```
            MorphTo::make('Topic', 'issueable')->types([Question::class]),
```

The 'Topic' field appears to be disabled, whenever I click on Create Issue from the Question Resource. It works fine when I create an Issue through the usual way of creating an Issue (not through a relationship on another Resource)

<img width="616" alt="Screenshot 2020-06-14 at 13 23 08" src="https://user-images.githubusercontent.com/656394/84593114-321c2000-ae42-11ea-84f5-43e8ad0cf110.png">

The problem seems to go away if I delete the 'viaRelationship=issues' at the end of the URL.

**Comment by loekwetzels** [comment]
might be related to #1897

**Comment by 4n70w4** [comment]
The same issue with `HasMany` and `BelongsTo`.

**Comment by davidhemphill** [comment]
Nova disables this field on purpose. It's expected to either edit the resource directly or to recreate it.

**Comment by 4n70w4** [comment]
It is not convenient for users (not IT specialists). Users scream when they have to press at least one extra button.

**Comment by 4n70w4** [comment]
Workaround. Edit file `vendor\laravel\nova\resources\js\components\Form\BelongsToField.vue`

```vue
    isLocked() {
      return false
    },
```

Recompile, and 

```bash
php artisan nova:publish
```
