### ISSUE TITLE
Image Fields not downloadable if only defined in fieldsForDetail() 

### ISSUE THREAD

**Issue by bzarzuela** [laravel/nova-issues#2667]
- Laravel Version: 7.14.0
- Nova Version: 3
- PHP Version: 7.4
- Database Driver & Version:
- Operating System and Version: macOS Catalina
- Browser type and version: Chrome Latest

### Description:

Image Fields only defined in fieldsForDetail() will not be downloadable because the FieldDownloadController will return a 404.

The only resolution is to include the field in the fields() method of the Resource and use ->hideFromIndex() on it. 

I'm reporting as a bug because I don't know if it's a documentation issue or something that needs to be fixed in the code itself.

**Comment by jbrooksuk** [comment]
Confirmed!

**Comment by jbrooksuk** [comment]
Pinging @mdavis1982 on this one as he wrote the implementation for `fieldsForDetail`.

**Comment by mdavis1982** [comment]
@jbrooksuk Thanks. I've just tested this and confirmed it as well. This also happens when adding relationships in one of the added methods and not in `fields`.

@bzarzuela I've had a quick look at this particular issues and I think it's easy enough to fix. I'm in the middle of some stuff at the moment, but if you're okay to wait for a little while I can get this fixed. Sorry about this! 😄

**Comment by bzarzuela** [comment]
@mdavis1982 that's okay, I'd offer to submit the PR myself but I don't have enough experience with the Nova codebase to do so. 😄
