### ISSUE TITLE
BelongsTo doesnt work when used within fieldsForUpdate

### ISSUE THREAD

**Issue by milewski** [laravel/nova-issues#2770]
- Nova Version: 3.8.2

```
public function fieldsForUpdate(Request $request): array
{
  return [
     BelongsTo::make('Boutique', 'boutique', Boutique::class)
  ]
}

```

```
https://dashboard.docker.localhost/nova-api/users/associatable/boutique?current=5&first=false&search=&withTrashed=false&resourceId=5&viaResource=&viaResourceId=&viaRelationship=
```

![image](https://user-images.githubusercontent.com/2874967/88660674-c4823580-d109-11ea-8129-ed477054437b.png)

**Comment by milewski** [comment]
Same as closed issue: https://github.com/laravel/nova-issues/issues/2580

**Comment by mdavis1982** [comment]
@milewski You need to ensure that the `BelongsTo` field is also present in the `fields()` method.

It's a known issue and something that I'm going to try to fix next week 😄 It's discussed in #2667

**Comment by milewski** [comment]
The work around worked as mentioned above.. But doesn't seems ideal

**Comment by crynobone** [comment]
> The work around worked as mentioned above.. But doesn't seems ideal

We attempted to merge `fields` with `fieldsFor*` methods in order to solve this issue but that created another issues for other users. Unfortunately at the moment this is a limitation with `fieldsFor*` that can't be solved. 

If anyone has an idea on how to solve this feel free to share the idea, until then I'm closing this.

**Comment by LucileDT** [comment]
Would it be possible to create a more user friendly error message for debugging purpose?
