### ISSUE TITLE
Computed Value in Select Field is lost on update / save

### ISSUE THREAD

**Issue by latwelve** [laravel/nova-issues#2824]
- Laravel Version: 7.x
- Nova Version: 3.8.4
- PHP Version: 7.x

I'm using a Select with a computed field to populate the values. This works fine until I try to update or save and the computed value is lost.. I found a similar issue on here but it was for showing a computed value on view.. I need it to work for creation / updating

```
                  Select::make('Journey To','booking_journey_to_id')
                       ->options(
                         $this->booking_family->booking->booking_journeys_to->pluck('description','id')->toArray()
                       )->displayUsingLabels()
                        ->hideFromIndex()
                        ->hideFromDetail(),


```

**Comment by davidhemphill** [comment]
Where's the computed field? Nova wouldn't be able to "lose" a computed value, since you define where it comes from. Would need more code and a little more info to be able to diagnose anything.

Also, I'd wrap return the values for the select inside a `Closure` instead of directly as you have it... Every time Nova boots the `Resource`, it'll hit the DB otherwise.
