### ISSUE TITLE
Search by resourse fields: Invalid text representation

### ISSUE THREAD

**Issue by 4EPHblN** [laravel/nova-issues#2844]
- Laravel Version: 7.24.0
- Nova Version: dev-master
- PHP Version: 7.3
- Database Driver & Version: PostgreSQL 11.2 x64
- Operating System and Version: Windows 7 x64
- Browser type and version: *no relevant*
- Reproduction Repository: —

### Description:
Declared in resourse:

```php
    public static $search = [
        'id',
        'pm_code',
        'version',
    ];

    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Code', 'pm_code'),
            Text::make('Version', 'version'),
        ];
    }

```

When i input "1." in serch field, Nova receives an error:

```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "1." (SQL: select * from "releases" where ("releases"."id" = 1. or "releases"."id"::text ilike %1.% or "releases"."pm_code"::text ilike %1.% or "releases"."version"::text ilike %1.%) and "releases"."deleted_at" is null order by "releases"."id" desc limit 26 offset 0)
```

![image](https://user-images.githubusercontent.com/9990351/92495200-4e401b00-f1ff-11ea-9922-a5ad2c40b022.png)

I think a trouble in `Laravel\Nova\PerformsQueries` on line 66:

```php
66            $canSearchPrimaryKey = is_numeric($search) &&
67                                   in_array($query->getModel()->getKeyType(), ['int', 'integer']) &&
68                                   ($connectionType != 'pgsql' || $search <= PHP_INT_MAX) &&
69                                   in_array($query->getModel()->getKeyName(), static::$search);
```

ID field is type of BigInteger and can't contains a dot (.).
Check `is_numeric(1.)` returns `true`, but `is_int(1.)` returns `false`.
I think use `is_numeric()` to determine can entered value be use for search by primary key is incorrectly.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Declare ID field as searchable;
Input in search field value "`1.`" (one with dot on the end).

**Comment by 4EPHblN** [comment]
Temporary solution:
```php
    protected static function applySearch($query, $search) {
        $search = preg_replace('/^(\d+)\.$/', '$1\\\.', (string)$search);

        return parent::applySearch($query, $search);
    }
```

**Comment by AlbinoDrought** [comment]
Just ran into the same issue. We have some fields that contain the string `'2.0'`. Searching this currently throws with the exception mentioned above, because it attempts to search the bigint ID column with `2.0` instead of not searching it at all, or searching it with just `2`.

`is_int` only returns true if the value is a real integer. It returns false for string representations:

```
>>> is_int(2)
=> true
>>> is_int(2.0)
=> false
>>> is_int('2')
=> false
```

An alternative that would work for our case could be `is_numeric($value) && ($value === strval(intval($value)))` (if the value is numeric and the string representation doesn't change when truncated to an int) when deciding `$canSearchPrimaryKey`. I'm not sure if this sort of function is built into PHP/Laravel/Illuminate somewhere already:

```
>>> is_numeric('2') && ('2' === strval(intval('2')))
=> true
>>> is_numeric('2.0') && ('2.0' === strval(intval('2.0')))
=> false
```

This would prevent "2.0" from searching primary key int fields.

**Comment by 4EPHblN** [comment]
@AlbinoDrought Not `2` or `2.0`, but `2.`

**Comment by 4EPHblN** [comment]
@davidhemphill , why you cose this issue??
You resolve this??

**Comment by crynobone** [comment]
Latest Laravel Nova fixed the issue. If you link your GitHub account on Laravel Nova website you should be able to see the relevant PR for this issue.
