### ISSUE TITLE
Is this a stable package with a future?

### ISSUE THREAD

**Issue by codicastudio** [laravel/nova-issues#2891]
I purchased my first Nova license more than a year ago. It has basically sat in a dev env ever since, never seeing a production env. Does this package have a future in the Laravel Ecosystem? It seems to be struggling. I keep waiting for this package to be brought to a production level, however there are open bug reports 16 months old (yes, I'm sure some have been dealt with in later releases, but the lack of issue management is concerning if that is the case). I cant even follow the update links on the Nova download page to read about changes. It links to the private repo not here so they aren't publicly visible which drives me to the code to review all changes. So, basic question, is this product alive and planned for future dev and when is the next major release? I'd appreciate a more insightful answer than "Yes, otherwise I'd be out of a job." as I previously read on Github. All conversations regarding this topic I could find on Github by purchasers are locked and shutdown with no meaningful guidance.

From what I can find, there is no roadmap, no scheduled release cycle, and in general Laravel seems to not want user feedback or to communicate future plans.

**Comment by preliot** [comment]
I've asked a question similar a while ago: https://github.com/laravel/nova-issues/issues/2431

To see the update links:  connect your laraval nova account to your github account (laravel nova > account settings > github).

But still, this concerns me too.

It seems to me the last year the team is increasingly depending on pull requests to add features. Although i'm fine with pull requests, it seems odd that the community should fix bugs for a payd product.

What bugs me the most (pun intended) is the stale-bot that autocloses bugs that are not answered or fixed. And if a bug is fixed (but there is still something wrong), you can't reopen the bug. It is possible to add information after a bug is closed, but nobody checks this. And i agree, the wait on fixing some of the bugs is way too long.

**Comment by davidhemphill** [comment]
These sorts of issues always come off trollish, especially when they come from accounts only created 4 days ago, but I'll bite.

Nova has had 1 full-time person since the beginning and one part-time person since @jbrooksuk started. We're in the process of getting another full-time person. Even so, Nova has regularly gotten releases every two weeks with new features and bug fixes. All updates have been included in each license purchased so far.

You can join the private repository to watch the progress by connecting your GitHub account here: https://nova.laravel.com/settings#github

Not every issue in the tracker is a verifiable bug or is common enough to warrant sticking it in the front of the line.
When you manage a project as large as Nova, it's not really feasible to keep notifications on for every closed issue. That's why we direct users to create new issues to bump theirs if something was closed in error, or is missing a key aspect of the fix.

There's also a lot going on behind the scenes. Hiring folks to help, Pro support, diagnosing/triaging issues, creating bug fixes, adding new features, planning the next series, etc... We just don't comment on what new features and when a new series is coming out. 

Nova is very active and not struggling at all. 😅
