### ISSUE TITLE
User partial view extensibility

### ISSUE THREAD

**Issue by Ludar-Pavel** [laravel/nova-issues#2895]
Affected file: resources/views/partials/user.blade.php

The user menu typically displayed in the top-right corner is currently hard-coded to have only one option - logout. To change that, one has to modify the vendor file. This makes it hard to keep up-to-date and not viable to mess with in general.

There should be a way to extend the menu that does not depend on that flow.

**Comment by davidhemphill** [comment]
In a future series of Nova we will likely not have user-customizable Blade files, but will have a way to customize the options via code. That won't happen inside Orion thought. 

It should be noted the user partial hasn't changed very much at all in this series, so shouldn't bee too much of a headache to sync changes. 👍 

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
