### ISSUE TITLE
Currency field only shows custom symbol on forms page

### ISSUE THREAD

**Issue by mattiasgeniar** [laravel/nova-issues#2932]
- Laravel Version: 7.28.3
- Nova Version: 3.11.1
- PHP Version: 7.4.10

### Description:

Given the following `fields()` content on a Nova resource:

```php
Currency::make('Retainer')
                ->symbol('My Symbol')
                ->nullable()
                ->rules(['numeric','gt:0']),
```

This will only show the custom `symbol()` on the forms page, the detail & index page will default to the dollar symbol at all times.

### Detailed steps to reproduce the issue on a fresh Nova installation:

I believe the cause can be found in:
- vendor/laravel/nova/resources/js/components/Form/CurrencyField.vue
- vendor/laravel/nova/resources/js/components/Index/CurrencyField.vue
- vendor/laravel/nova/resources/js/components/Detail/CurrencyField.vue

Only the `Form` Vue component has logic to display the custom symbol, the  `Index` and `Detail` do not have this.

**Comment by navidnadali** [comment]
@crynobone just faced this issue too.. any plans for a fix?

**Comment by crynobone** [comment]
I have a mixed feeling about this issue. `symbol()` was initially added to solve issue before `brick/money` was introduced but now it feel sort of redundant since we can always get the currency symbol from `brick/money`. As for now I'll will make a PR to ensure `symbol()` will be honored if defined.
