### ISSUE TITLE
Smart polling

### ISSUE THREAD

**Issue by nickkuijpers** [laravel/nova-issues#3004]
The polling feature is very nice, thank you.

What would be nice is that whenever the data did not change in the database, we are not re-rendering the resources so we don't see a flash screen of reloading the resources.

**Comment by crynobone** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by stephan-v** [comment]
This would be very helpful. It is kinda of strange to see the screen flashing every time the interval is hit. Services like Sentry also manage to implement polling without refreshing the entire page.

**Comment by cwilby** [comment]
As this approach requires a web socket server, I think this would be better as a third-party package.

It makes sense given how this was implemented as polling instead of socket notifications.

Considerations for a third-party package:
- Bring in `laravel-echo` via npm.
- Create broadcast events for each eloquent event type.
- Add event listeners for enabled nova resources to dispatch broadcast events on eloquent events
- Add logic to handle broadcast events via `laravel-echo` on the frontend

**Comment by nickkuijpers** [comment]
I dont think the polling is the issue, i think the issue is that whenever there is no new data, the list gets refreshed. If we can disable refreshing the list when there is no new data received, the problem will mostly disappear.

If we use websockets, the same issue will occur, as the websockets gives us new information to display like the polling does.

**Comment by cwilby** [comment]
@nickkuijpers Related: https://github.com/laravel/nova-issues/issues/3432

**Comment by cwilby** [comment]
The problem with that approach is the loading spinner is visible while the network request is active.  The front-end would not be able to determine whether the loadmask (flash) should be displayed based on data it hasn't received yet.  

The solution to this problem is to only re-render the UI when the server broadcasts new data to it.

**Comment by nickkuijpers** [comment]
Ah i understand, thank you for the explanation.
