### ISSUE TITLE
Issue with Composer v2 and packages requiring Nova

### ISSUE THREAD

**Issue by SquareBeard** [laravel/nova-issues#3019]
With Composer v2 I can't update my dependencies anymore.
It fails with packages requiring Nova like this: `"laravel/nova": "^2.0|^3.0"`.
I think this is what I'm talking about: https://github.com/composer/composer/issues/8890

I don't know who should fix the problem, Nova, the packages or Composer, But it can be fixed by adding a version to the composer.json of Nova, eg: `"version": "3.14.0",`.

Unless there is another way, could this be added to composer.json please ?

**Comment by crynobone** [comment]
If you're downloading `nova` using zip and reference it using `path` you should be able to add the version on your own. 

However AFAIK adding `"version"`: 

```
cd nova
composer config version 3.14.0
```

I wasn't able to replicate the issue when requiring `laravel/nova` using composer installation.

**Comment by ziming** [comment]
I believe most installations of nova is with the path method, partly because of how unstable nova is between releases that we need to be able to easily edit the package files to fix things as we wait for the next release. (but it is improving!)

Although we can add "version": "3.14.0" to nova composer.json ourselves, it requires us to always remember to do so. Hence I think it will be good if the nova team can do it until a better way to fix this is found.

**Comment by crynobone** [comment]
We are discussing this internally at the moment but for the time being above is a quick solution until we can have a permanent direction (without downgrading to composer v1).
