### ISSUE TITLE
"Cancel" button on edit and create forms

### ISSUE THREAD

**Issue by vyuldashev** [laravel/nova-issues#311]
Along with "Update & Continue Editing" and "Update User" there should be "Cancel button" in order to go back.

<img width="453" alt="screen shot 2018-08-29 at 12 53 34" src="https://user-images.githubusercontent.com/1809081/44780464-b082d180-ab8a-11e8-95df-cea072665a4d.png">

**Comment by Livijn** [comment]
I concur!

**Comment by reganjohnson** [comment]
This would be useful.

**Comment by Andy-Baker** [comment]
+1

**Comment by davidhemphill** [comment]
Why not just hit the back button or navigate somewhere else?

**Comment by StanBarrows** [comment]
@davidhemphill 

I'agree with you, but most of the time I do not develop for developers. I code for users and unfortunately   hey sometimes expect things a little different.

**Comment by vyuldashev** [comment]
@StanBarrows @davidhemphill Exactly, as a developer I know there is a "Back" button. But users seeking for "Back" or "Cancel" button and ask me for it.

**Comment by laraning** [comment]
Fully agree, made a demo to a client and they were not understanding how to “go back” from the form. Also, if the browser history cache is disabled there is no way to go back.

**Comment by Fabio1988** [comment]
fully agree, a back or cancel button would be helpful

**Comment by johanvanhelden** [comment]
When I did a demo people did expect a cancel button to go back to the index. As has been said before, that's the difference between developers and end-users.

**Comment by davidhemphill** [comment]
After talking this over, this isn't going to be a top-priority. Closing for now.

**Comment by Livijn** [comment]
Maybe re-open?  👍 👍

**Comment by jfoliveira** [comment]
@davidhemphill I understand you guys in Laravel LLC are top developers developing for other developers but, unfortunately to most of us, we develop for average people that do not think about a form as a part of a web application that is contained in a browser that has a `Back` button.

I've just purchased Laravel Nova yesterday, build two resources, did a demo to our internal users, and all of them complained about the lack of a cancel button.

That might not be a coincidence that so many people are here asking you guys about that. It's not because we want, it's because average users are used to that in other applications so they expect simular behaviour.

Also, please consider that this isn't supposed to have an expensive cost of implementation on your side, but would save we NOVA users a lot of time when implementing forms.

Please consider re-opening and prioritizing this issue. Please!

Alternatively, if you believe there is an easy way to achieve that on our side by implementing common/additional buttons in a reusable way, please let us know how.

**Comment by dillingham** [comment]
![cancel](https://user-images.githubusercontent.com/29180903/52132788-edf1fc00-260d-11e9-9865-6d70f5547f33.png)

**Comment by davidhemphill** [comment]
If someone wants this sooner, feel free to make a PR to https://github.com/laravel/nova. I would support this being default and not opt-in through a config. Everyone will just have to live with it! 😄

**Comment by jfoliveira** [comment]
@davidhemphill I tried to access nova repo at https://github.com/laravel/nova but it seems to be a private repository.
How can we contribute and send a PR to it?

**Comment by rovansteen** [comment]
@jfolveira if you login at https://nova.laravel.com you can get access by connecting your GitHub in the user settings

**Comment by davidhemphill** [comment]
☝️

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
