### ISSUE TITLE
Use Laravel-Mix v6 in tools?

### ISSUE THREAD

**Issue by marktopper** [laravel/nova-issues#3184]
- Laravel Version: v6.18.14
- Nova Version: v2.8.0
- PHP Version: v7.3.21

### Description:
Is it possible to use laravel-mix v6 in tools?

Whenever I try to upgrade a tool to use laravel-mix v6, it fails upon build with the `Can't resolve` error. Seems to be unable to load the .vue file extension after upgrade to v6.

If anyone has succeeded in this, please share your setup for this.

**Comment by crynobone** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or other support channel listed at <https://nova.laravel.com/docs/3.0/support.html#support-questions>

**Comment by crynobone** [comment]
In term of Laravel Nova itself, this will be considered when we worked on next series with updated Tailwind and Vue.js (planned this year).

**Comment by AlbinoDrought** [comment]
This is one of the first results when I google `laravel nova laravel mix`. My templated tools were created with `laravel-mix@^1.0` which uses a version of `node-sass` that doesn't work with Node 16+. Later versions of `laravel-mix` default to dart-sass instead, which works great. Here's what I did to get my tool building on Node 16 + laravel-mix:^6

-----

Install it: `npm install --save-dev laravel-mix@^6.0`

Loosely following the upgrade guide at https://laravel-mix.com/docs/6.0/upgrade#update-your-npm-scripts , update your scripts in `package.json` to:

```json
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
```

Still loosely following the upgrade guide at https://laravel-mix.com/docs/6.0/upgrade#before-1 ,  let laravel-mix know you're building Vue in `webpack.mix.js` by adding `.vue()` to the end of the `.js()` line:

```js
.js('resources/js/tool.js', 'js').vue()
```

Update your `resources/js/tool.js` to `import` your components instead of using `require`. If you don't do this, your project will appear to build successfully but you will see a blank space where it should be on the Nova dashboard. If running Vue in devtools mode, you will see a ` Failed to mount component: template or render function not defined.` message when this happens.

```js
import Tool from './components/Tool.vue';

Nova.booting((Vue, router, store) => {
  Vue.component('your-tool', Tool)
})
```

Let laravel-mix install the rest of the required dependencies by running `npm run dev`. You should see something like this:

```
 	Additional dependencies must be installed. This will only take a moment.
 
 	Running: npm install sass-loader@^11.0.1 resolve-url-loader@^3.1.2 vue-template-compiler vue-loader@^15.9.5 --save-dev --legacy-peer-deps
```

This failed for me, no idea why, and I had to run the printed command manually:

```
npm install sass-loader@^11.0.1 resolve-url-loader@^3.1.2 vue-template-compiler vue-loader@^15.9.5 --save-dev --legacy-peer-deps
```

That's all I needed to do. `npm run dev`, `npm run watch`, and `npm run prod` all work as expected now :+1:

**Comment by lucacri** [comment]
@AlbinoDrought Thank you so much for that snippet. I was just going through the same problem, and your solution worked perfectly

**Comment by FrazeColder** [comment]
Hi @AlbinoDrought,
first of all, thank you for your answer! I have already switched to laravel mix v6 and done all of this steps. However, I did not do them for my custom written nova components. I know have done that as well but I am ending up with a weird problem. This is the problem I get.

```
ERROR in ./resources/js/components/FormField.vue?vue&type=script&lang=js& (../../node_modules/babel-loader/lib/index.js??clonedRuleSet-5[0].rules[0].use[0]!../../node_modules/vue-loader/lib/index.js??vue-loader-options!./resources/js/components/FormField.vue?vue&type=script&lang=js&) 20:0-66
Module not found: Error: Can't resolve 'laravel-nova' in '/Myproject/nova-components/PricePercentage/resources/js/components'

```

Do you have any idea on how to solve this?

**Comment by gekkota** [comment]
When we do this for multiple tools the `vue()` causes it to be included every time. 

Can anyone advise how I should get it to only happen once?

**Comment by JoeriTheGreat** [comment]
> Hi @AlbinoDrought, first of all, thank you for your answer! I have already switched to laravel mix v6 and done all of this steps. However, I did not do them for my custom written nova components. I know have done that as well but I am ending up with a weird problem. This is the problem I get.
> 
> ```
> ERROR in ./resources/js/components/FormField.vue?vue&type=script&lang=js& (../../node_modules/babel-loader/lib/index.js??clonedRuleSet-5[0].rules[0].use[0]!../../node_modules/vue-loader/lib/index.js??vue-loader-options!./resources/js/components/FormField.vue?vue&type=script&lang=js&) 20:0-66
> Module not found: Error: Can't resolve 'laravel-nova' in '/Myproject/nova-components/PricePercentage/resources/js/components'
> ```
> 
> Do you have any idea on how to solve this?

Any update on this? Having the same issue 
```
<script>
import {Paginatable, PerPageable} from 'laravel-nova';
`Error: Could not find a declaration file for module 'laravel-nova'.
````
