### ISSUE TITLE
Add X-Requested-With header to all request

### ISSUE THREAD

**Issue by pavinthan** [laravel/nova-issues#323]
Add `X-Requested-With` header to all request in `resources/js/util/axios.js` file to all request to use `CreateFreshApiToken`

**Comment by bradenkeith** [comment]
What are you hoping to accomplish with this addition?

**Comment by pavinthan** [comment]
@bradenkeith to integrate with Laravel Passport so we can use the nova service with out mobile clients and extra...

**Comment by marcusmoore** [comment]
I haven't tested too deeply but it seems like this worked for me:

In `resources/js/util/axios.js` add the following lines under the `axios.create()` line

```javascript
instance.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest'
instance.defaults.headers.common['X-CSRF-TOKEN'] = document.head.querySelector('meta[name="csrf-token"]').content
```

Then compile and overwrite the existing assets:
```bash
cd nova

# get a "normal" version of the mix file
cp webpack.mix.js.dist webpack.mix.js

# install dependencies
yarn

# build new assets
yarn run prod

# go back to root folder
cd ..

# publish the assets to ./public/nova-assets
php artisan nova:publish
```

**Comment by marcusmoore** [comment]
👋 hello @davidhemphill. Is this something that can be added in a future release?

**Comment by davidhemphill** [comment]
This has been added and will be included in an upcoming release!

**Comment by pavinthan** [comment]
Thanks Guys 👍

**Comment by darynmitchell** [comment]
> This has been added and will be included in an upcoming release!

Trying to find solution to same issue, axios headers `X-Requested-With` and `X-CSRF-TOKEN`, not seeing it solved 3½ years later in Nova v4?
- I do see `"X-Requested-With":"XMLHttpRequest"` in public/vendor/nova/vendor.js, so that's ok ✔️
- But I don't see a Nova documented solution for  `X-CSRF-TOKEN`... ❌

**Comment by davidhemphill** [comment]
At some point in the transition to Inertia for version 4.0, it appears the "X-CSRF-TOKEN" common header was removed. Could've been a mistake or some implementation detail required for v4. Hard to say. 

P.S. Please open a new issue with what you're trying to do. This will help greatly instead of reviving long-dead (and solved) issues.
