### ISSUE TITLE
Nova git missing

### ISSUE THREAD

**Issue by binaryk** [laravel/nova-issues#3304]
- Laravel Version: 8.25.0
- Nova Version: 3.22.0
- PHP Version: 7.4.13

### Description:

The nova git is missing. Even the github page is down (I'm invited to it: https://github.com/laravel/nova)

### Detailed steps to reproduce the issue on a fresh Nova installation:
I've tried to fresh reinstall vendor, and it gives me the follow exception, the git is missing. 

It's high priority since we cannot upgrade the composer. 

Thanks.

![image](https://user-images.githubusercontent.com/6833714/112143954-3e0eec80-8be1-11eb-95f2-3e869c86e22b.png)

**Comment by crynobone** [comment]
You need to ensure that the application is setup using  [Installing Nova via Composer](https://nova.laravel.com/docs/3.0/installation.html#installing-nova-via-composer)

![image](https://user-images.githubusercontent.com/172966/112146797-f440f900-8c16-11eb-9905-4ae1f50a0c4d.png)

Next, make sure that Composer `auth.json` has been configured, otherwise run the following:

```
composer config --global http-basic.nova.laravel.com {email} {token}
```

`{email}` and `{token}` can be retrieved from https://nova.laravel.com/settings. 

Finally, run `composer update --prefer-dist`, you might need to remove `composer.lock` and `vendor` directory in case existing cache causing an issue.

------

> I'm invited to it: https://github.com/laravel/nova)

We removed the access in order to build next major release (new series) of Laravel Nova which would require new license. 

![image](https://user-images.githubusercontent.com/172966/106670964-b3e6d680-65e8-11eb-8c73-0f6e3dc05498.png)
