### ISSUE TITLE
Accessing Nova Date from Inside Nova Modal (Action, Menu, Custom Dialogue)  unexpectedly closed the window.

### ISSUE THREAD

**Issue by seek4silence** [laravel/nova-issues#3311]
- Laravel Version: 8.34.0
- Nova Version: 3.22.0
- PHP Version: 8.0.0
- Database Driver & Version:
- Operating System and Version: MacOS.11.2.3
- Browser type and version: Chrome.89.0.4389.90
- Reproduction Repository: https://github.com/###/###

### Description:
When you are using Nova Date inside of Nova Modal for an example from Nova Action , clicking date closes the dialogue unexpectedly. It happens sporadically. To reproduce it you have to click multiple times inside date.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create an Action. 
2. Provide Date Field. 
3. click on date field multiple times. 

https://user-images.githubusercontent.com/3577904/112622416-4d817600-8e2b-11eb-8312-ba8d3c6b9ff5.mov

**Comment by anditsung** [comment]
i have the same issue too

**Comment by crynobone** [comment]
This is a hard issue to replicate. We only trigger clickaway close event if it triggering element outside of modal or whitelisted class including known classes from flatpickr.

Would appreciate if anyone can identify the target element triggering the close, or if there any console error etc.

**Comment by MohammadAbusaleh** [comment]
@crynobone this issue has been there for a while and I believe there were multiple times that it was posted.

Just a geniuine suggestion, would you consider adding an option to allow us to select if the modal can be clicked away or have to cancelled by clicking on the cancel button.

There are many stuff that would be much easier to do inside the action modal but I always stay away from it because I know the client will call me the next morning complaining that they did filled all the fields and then the modal closed and they lost their precious work, so I end up having to spin up custom resource-tools for stuff that can easily be done with an action.

**Comment by crynobone** [comment]
> this issue has been there for a while and I believe there were multiple times that it was posted.

It has been checked multiple times and I added few bug fixes to previous release and so far I unable to replicate the issue anymore.

> Just a genuine suggestion, would you consider adding an option to allow us to select if the modal can be clicked away or have to cancelled by clicking on the cancel button.

Then this becomes a feature request, which would be major changes to cover different scenarios (modal vs filter menu etc).

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
