### ISSUE TITLE
Required method for Action fields is not doing validation.

### ISSUE THREAD

**Issue by smartameer** [laravel/nova-issues#3764]
- Laravel Version: 8.x
- Nova Version: 3.30
- PHP Version: 8.1
- Database Driver & Version: Mysql
- Operating System and Version: *
- Browser type and version: *

### Description:
Action fields with `required(true)` never does validation but `rules('required')` only does.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a action form with Any field and supply `required(true)` and form submission goes through.

```
Text('Email', 'email')->required(true)  // this is not working for validation

Text('Email', 'email')->rules('required')  // this is working for validation
```

So, unable to make the field's required property dynamically.

**Comment by davidhemphill** [comment]
The `required` method is only for indicating a field should be marked required. It doesn't apply any validation to the field. It is typically used in complex validation scenarios where it is otherwise impossible for Nova to know to visually mark the field as required. 

https://nova.laravel.com/docs/3.0/resources/fields.html#required-fields
