### ISSUE TITLE
Panel meta is not applied

### ISSUE THREAD

**Issue by jesseschutt** [laravel/nova-issues#3877]
- Laravel Version: 9.7.0
- Nova Version: 4.0.5
- PHP Version: 8.0.14

### Description:
When adding either `limit(x)` or `help()` to a field panel neither is represented in the resource creation or update view. 

### Detailed steps to reproduce the issue on a fresh Nova installation:

**1. Create a new Nova resource**
**2. Add a panel with `limit()` or `help()` to the `fields()` method**
```php
(new Panel('Test', [
    Text::make('name'),
    Text::make('test_field'),
]))
    ->limit(1)
    ->help('Help Text'),
```
**3. View either create or update resource in Nova**

The `limit` or `helpText` are both `null` when inspecting the network request.

<img width="196" alt="Screen Shot 2022-04-07 at 8 22 00 AM" src="https://user-images.githubusercontent.com/353047/162208686-ae136fee-db26-4f37-b0a7-f5e4ae1e625a.png">

**Comment by Jubeki** [comment]
The problem is probably that in `\Laravel\Nova\ResolvesFields::resolvePanelsFromFields` new Panels are created with `Panel::make` instead of using the existing one.

(This also creates an Issue if you have a class which extends panel, because they also create a new Panel instead of using the existing one)
