### ISSUE TITLE
Footer can't be overridden

### ISSUE THREAD

**Issue by aronquiray** [laravel/nova-issues#3885]
- Laravel Version:  8.83.7
- Nova Version: 4.0.5
- PHP Version: 8.0.11
- Database Driver & Version: MySQL
- Operating System and Version: Windows 11
- Browser type and version: Chrome 100.0.4896.75

### Description:
Footer can't be overridden

### Detailed steps to reproduce the issue on a fresh Nova installation:
Nova assets have been published, but seems like it doesn't work. 
optimize:clear , still no effect.

before, it can be overrided via vendor/nova/partials/footer , right now it doesn't. 
![Screenshot_1176](https://user-images.githubusercontent.com/13714092/162249071-b6ef644b-de7a-4a99-adaf-d2ebb3ad769a.jpg)

**Comment by amanpatel** [comment]
Thanks for posting this. I am having a related issue. In Nova 3, we customized the login page to use OAuth server. But since Nova 4 uses vue components for rendering UI, it is not as simple as publishing the views and updating them. I bet the Nova team is probably already aware of this and might have a solution in the next point release.

**Comment by aronquiray** [comment]
> Thanks for posting this. I am having a related issue. In Nova 3, we customized the login page to use OAuth server. But since Nova 4 uses vue components for rendering UI, it is not as simple as publishing the views and updating them. I bet the Nova team is probably already aware of this and might have a solution in the next point release.

it's not really a critical bug. however, we don't want our clients to know we're using this haha! anyway, hope it'll resolved be soon.
