### ISSUE TITLE
[FEATURE REQUEST] Delete old avatar when uploading new one successfully

### ISSUE THREAD

**Issue by rickmacgillis** [laravel/nova-issues#401]
I'm building out the functionality for avatar changes on Nova using the `Avatar` field. When I changed the picture, I noticed that the old image is still on the system.

As some websites might decide to have an avatar history, while others do not, it's prudent to allow for the possibility of cleaning up (deleting) the old avatars. Placing that functionality at the `File` field level, will allow all objects of that type to use that functionality.

For the sake of file revision history that some websites might have, it might be prudent to default to leaving the files on the system. If you add a `pruneFileOnUpdate()` method, then people can chain it in when defining the field.

**Comment by v1nk0** [comment]
+1

Same goes for normal Image fields.
To replace an image there are two ways:
1. Delete the old image first, then add the new one
2. Just upload a new file

In both cases, the image is replaced in the database, but only for the first case, the old image is actually removed from the server.
I would also expect the image to be deleted when I just upload a new file (as it is overwritten in the database anyway and there is no way to recover that image or is there?)
When there is some sort of reason to keep the image (e.g. recovery possibilities or revisions) it would be good to have a possibility to change this behavior, like @rickmacgillis suggests, because there are scenarios where this will pollute the server with unused images.

**Comment by danmatthews** [comment]
Just to jump onto this one - is there a way to disable the delete button and ONLY have replace available?

A flag on the class would be good, something like:

`Avatar::make('Picture')->replaceOnly()`

This is because i've got a path/url field in the DB that is required, so it's not `NULLABLE`, so deleting causes a MySQL exception.

**Comment by rickmacgillis** [comment]
Did anyone ever work on this issue?

**Comment by EmanueleCoppola** [comment]
+1

**Comment by rickmacgillis** [comment]
Team Nova, as this issue seems quite popular, are you guys planning to add that feature?

**Comment by dillingham** [comment]
https://nova.laravel.com/docs/1.0/resources/file-fields.html#pruning

**Comment by FaridAghili** [comment]
Any progress on this?

**Comment by dkulyk** [comment]
PR was sent to upstream.

**Comment by Pimverleg** [comment]
So how can we achieve this in the new nova version?

**Comment by amidesfahani** [comment]
Any progress on this?

**Comment by crynobone** [comment]
See https://nova.laravel.com/docs/3.0/resources/file-fields.html#pruning-deletion
