### ISSUE TITLE
Datetime Field + Safari Picker Doesn't Sync Up

### ISSUE THREAD

**Issue by parrots** [laravel/nova-issues#4058]
- Laravel Version: 9.9
- Nova Version: 4.2.3
- PHP Version: 8.1
- Operating System and Version: macOS 12.3.1
- Browser type and version: Safari 15.4

### Description:

Using the DateTime field in Nova, the date picker widget in Safari does not default to the currently entered date and time. Even after picking a date via the widget the widget stays out of sync when re-opened. This is not a known Safari issue; example pages from other sources work fine: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

<img width="284" alt="Screen Shot 2022-04-20 at 11 53 41" src="https://user-images.githubusercontent.com/171163/164293218-1e89d1ab-457e-4bd4-9053-7681eb270c23.png">

Plain date fields work in Nova 4, so I'd venture this has to do with the date-time formatting itself.

**Comment by crynobone** [comment]
It seems Safari doesn't fully support `HH:mm:ss` format. Changing this would mean we will lose seconds' precision.

**Comment by parrots** [comment]
Tricky situation if it is a Safari bug because this is defiantly a UX regression vs Nova 3. I can envision many people using Nova + Safari accidentally picking the wrong date without noticing, especially if the date-without-time field works just fine.

Playing around locally though, where are you seeing it doesn't support seconds? Specifying `step="1"` gets Safari to show, and persist, the seconds. 

```
<html><body>
<input type="datetime-local" name="meeting-time" value="2018-06-12T19:30:04" min="2018-06-07T00:00:00" max="2018-06-14T00:00:00" step="1">
</body></html>
```

In fact I'm not sure the different between fields, but one of my Nova 4 date time fields seems to have the picker work perfectly vs the one that doesn't (in both the working and non-working fields the dates end in :00).

<img width="328" alt="Screen Shot 2022-04-21 at 10 42 01" src="https://user-images.githubusercontent.com/171163/164509798-fb3891b3-3293-42e9-9bfa-1f6a31fd4a83.png">

**Comment by crynobone** [comment]
Your solution only works for seconds between `01` to `59`, once you use `00` as seconds you will start to see the same issue as before.

https://jsfiddle.net/er14j6p9/1/

**Comment by LiamKarlMitchell** [comment]
Note: On Safari browser the date picker does not have clear button because of this.
![image](https://user-images.githubusercontent.com/1968109/177340575-f1e6611f-591c-4565-b33f-235210577029.png)

Google Chrome Windows and Mac show as expected by the way.
![image](https://user-images.githubusercontent.com/1968109/177340798-21606df4-4678-4ccb-91e7-0a4d46046b16.png)

**Comment by parrots** [comment]
I just got a ping from Apple's bug reporter that they believe this is fixed in the macOS beta that just came out today. Only rocking iOS betas ATM, so can't verify (and still leaves us with the problem of older OSs)

**Comment by LiamKarlMitchell** [comment]
Happy to check on iOS Safari once the update goes through as stable.
I'll try to remember to do this :D

**Comment by crynobone** [comment]
It seems Safari can handle any value if `step="any"` is set instead of `step="1"`, you can do this by adding:

```php
DateTime::make('Created At')->step('any'),
```

We not considering `any` as the default instead of `1` for now because the behaviour is uncertain:

![image](https://user-images.githubusercontent.com/172966/182060168-ff7df270-784c-4ce7-bc77-463764997258.png)

Other than that it's totally up to Safari to fix the implementation.
