### ISSUE TITLE
[Bug] Attaching BelongsToMany relationship with intermediate table without 'id' column doesn't work

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#433]
I just tried to set up the necessary resources for this [laravel-permission](https://github.com/spatie/laravel-permission) package and the intermediate tables for the BelongsToMany relationships between permissions, roles, and users have no `id` column.

Nova seems to expect a `id` column for the `BelongsToMany` relationship, as I get this exception when I try to attach a `Role` model to a `Permission` model:

```
Undefined column: 7 ERROR:  column "id" does not exist
(SQL: insert into "role_has_permissions" ("role_id", "permission_id") values (1, 1) returning "id")
```

Is there a solution for this issue?

**Comment by swilla** [comment]
There is a nova package for this spatie package here: 
https://novapackages.com/packages/vyuldashev/nova-permission

**Comment by chescos** [comment]
@swilla thank you! Just tried it, sadly this doesn't work either. I guess the issue might be related to PostgreSQL then (which I am using), maybe it works fine with MySQL.

**Comment by swilla** [comment]
I'm using MySQL without any issues. There does seem to be a few problems around many to many relationships with non-standard naming conventions.  There are some existing issues on those.

**Comment by tvercruysse** [comment]
Do you happen to use Postgresql ? i have the same issues while using psql

**Comment by chescos** [comment]
@tvercruysse Yes. This issue seems to be related to PostgreSQL.

**Comment by tvercruysse** [comment]
@chescos https://github.com/vyuldashev/nova-permission/issues/33#issuecomment-427824606

here you go mate.

**Comment by gerardnll** [comment]
PostgreSQL here also. We shouldn't need to make a new column to fix this.

**Comment by chescos** [comment]
@gerardnll I agree that making an additional `id` column should not be necessary and is not even possible in some cases. It works fine without `id` column in MySQL, so I assume this can be considered to be a bug.

**Comment by gerardnll** [comment]
I'm not even sure it's a Nova thing or if it's going to be fixed.

When creating a Pivot, nova calls `save()` on a Eloquent\Model class that calls `performInsert()`, then goes to `insertAndSetId()` an then to `insertGetId()` of Eloquent\Builder, at the end this goes to PostgresGrammar that attaches 'returning id' to the SQL. To get the ID (always expects to get an ID) with MySQL uses 'lastInsertId' but with PSQL it expects the ID from the last executed SQL.

Pivot is treated as a Model, and Models always expect having and ID so...

**Comment by scottybo** [comment]
Does anyone have a solution to this that doesn't require adding an id column? Also on Postgres here...

**Comment by michaelsabatino** [comment]
Something similar is happening in Oracle as well, specifically "ORA-00918 column ambiguously defined." The problem is the "returning id" in a select statement when trying to attach/detach a belongsToMany relationship. 

Simply adding an 'id' column to the pivot table won't even fix it. The only workaround I've found is adding an incrementing 'pivot_id' column to the pivot table, then creating an entire model just for the pivot table so I can redefine its primary key to the new column:

`protected $primaryKey = 'pivot_id';`

AND, I have to be sure to reference this new pivot model in the related models:

`return $this->belongsToMany(User::class)->using('App\RoleUser');`

It's annoying which is very un-Laravel like :) I remember a while back Taylor Otwell asking on Twitter what keeps people from seeing Laravel as an enterprise solution and this could point to one important factor. Unless the enterprise is on MySQL, which is probably not the case for many large orgs, things get complicated for non-MySQL databases.

**Comment by chescos** [comment]
@taylorotwell any news on this?

**Comment by chescos** [comment]
Issue still exists in Nova 2.0.9

**Comment by jbrooksuk** [comment]
@chescos thanks for reporting this is in v2.0.9. Updated.

**Comment by davidhemphill** [comment]
I confirmed with @taylorotwell a while back that there's currently no way to fix this because the duplicated rows are ambiguous without a unique ID.
