### ISSUE TITLE
`hideFromIndex()` Doesn't Work on Stacked Items on Lenses

### ISSUE THREAD

**Issue by jjjrmy** [laravel/nova-issues#4625]
- Nova Version: 4.12.12

The below code works fine on a normal Resource but if you try the same code on a Lens, the Hidden line is not hidden.

```php
Stack::make('Customer', [
    Line::make('First Name')->asHeading(),
    Line::make('Email')->hideFromIndex(fn() => true),
]),
```

**Comment by crynobone** [comment]
Lenses only have Index view.

**Comment by ianrobertsFF** [comment]
Looks like the sticking point is Stack.php:98, which only checks for index requests.

As a workaround (and potential bug in itself) you can use `hideFromDetail` to control the visibility of Stack field lines within a Lens, as `prepareLines` falls back to `isShownOnDetail` when `isResourceIndexRequest` is false.

Although this is a workaround, so don't expect this behaviour not to be determined a bug in the future and fixed with an additional `isResourceDetailRequest` check.

Safest option would probably be to roll your own Stack field extending the existing nova one, only overriding the `prepareLines` function to take account of Lenses. Wouldn't even need to touch the vue, as `stack-field` can remain the component.
