### ISSUE TITLE
Dependent Fields not supported on Action

### ISSUE THREAD

**Issue by MohamedGad121** [laravel/nova-issues#4656]
Although it's supposed that the Dependent fields are supported on actions, since v4.11.0 but still It doesn't work on my project, here is a snippet of code

![image](https://user-images.githubusercontent.com/97297727/182304103-3f5ab7d8-7ccc-4028-b929-33728949686a.png)

so now after checking the "Set New Name" checkbox the dependent field still not showing
![image](https://user-images.githubusercontent.com/97297727/182304868-73988b12-b005-40ee-8dc9-9b1c0a259483.png)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Also, don't ignore the issue template: 


```markdown
- Laravel Version: #.#.#
- Nova Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:


### Detailed steps to reproduce the issue on a fresh Nova installation:
```

**Comment by juse-less** [comment]
Sorry for hijacking.
But, from what I've seen with these kind of issues (new features not working after update), it's usually because people hasn't re-published the Nova assets after the update.

I'm a bit split if'd be the issue here, but if it's the case here as well -
Laravel auto-handles this since v9, I believe. So take a look at their [scaffolding repo](https://github.com/laravel/laravel/blob/3ea3861e4bab0f39322e8ac2ac9ffd8c6481fbe6/composer.json#L40-L42) to always re-publish Laravel assets (and 1st party packages like Nova) whenever you install or update something with Composer.
Or, at least follow the guidelines in [Nova's documentation](https://nova.laravel.com/docs/4.0/installation.html#updating-nova-s-assets).
I've been running the Laravel v9 solution as I scaffolded it when it was released and moved over our v8 code, and haven't had these issues since Nova v4.0.0.
