### ISSUE TITLE
displayUsing() doesn't work for Number, Text and Select fields

### ISSUE THREAD

**Issue by TarasZakus** [laravel/nova-issues#4661]
- Laravel Version: 8.83.21
- Nova Version: 4.12.14
- PHP Version: 8.0.21

### Description:
I've just upgraded to Nova v4.12.14 and noticed that ->displayUsing() doesn't work at all: not on the Number field, Text or Select (displayUsingLabels() doesn't work too).
The only field it works for me is the DateTime field.
Seems to be an FE issue, as the correct value is passed to the corresponding Vue component.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Define any of the mentioned fields in a Nova Resource class, for example:
```
Text::make('Name')->displayUsing(function ($name) {
    return strtoupper($name);
}),
Select::make('Size')->options([
    'S' => 'Small',
    'M' => 'Medium',
    'L' => 'Large',
])->displayUsingLabels(),
```
Expected result: displayUsing() applies custom formatting to the field value

Actual result: raw value is shown.

**Comment by TheBigDG** [comment]
Same for me, I have also just upgraded to 4.12.14 and fields which were previously working and now failing.  I have a DateTime field in a resource index which no longer shows anything.

`DateTime::make('Date Time')
    ->sortable()
    ->displayUsing(fn ($date) => $date->format('Y-m-d G:i')),
`

I note this issue was reported 2 days ago and so far no feedback or acknowledgement.  I can work with this in an open source environment, but if you are going to charge for your product, you need to be more on top of things.  surely this cannot be a difficult bug to debug and fix.  Its an issue with basic functionality and need immediate attention.

:wq

**Comment by ianrobertsFF** [comment]
> Same for me, I have also just upgraded to 4.12.14 and fields which were previously working and now failing. I have a DateTime field in a resource index which no longer shows anything.
> 
> `DateTime::make('Date Time') ->sortable() ->displayUsing(fn ($date) => $date->format('Y-m-d G:i')), `
> 
> I note this issue was reported 2 days ago and so far no feedback or acknowledgement. I can work with this in an open source environment, but if you are going to charge for your product, you need to be more on top of things. surely this cannot be a difficult bug to debug and fix. Its an issue with basic functionality and need immediate attention.
> 
> :wq

A fix for DateTime should appear in the next version: https://github.com/laravel/nova-issues/issues/4665

In the very short term you can use resolveUsing for fields that don't play ball. NovaRequest has methods to determine whether its a detail/index view.

The displayAs stuff does seem to have been a bit part implemented, I've macro'd mine to setting Value and displayAs for displayUsing until its ironed out.

**Comment by TarasZakus** [comment]
@ianrobertsFF yes, as a temporary solution I'm using resolveUsing():
```php
$isIndexOrDetailRequest = $request->isResourceIndexRequest() || $request->isResourceDetailRequest();
...
Text::make('Name')
    // TODO: revert, when https://github.com/laravel/nova-issues/issues/4661 is fixed
    //->displayUsing(fn ($name) => Str::limit($name, 50))
    ->resolveUsing(function ($value) use ($isIndexOrDetailRequest) {
        if ($isIndexOrDetailRequest) {
            return Str::limit($value, 50);
        }
        return $value;
    }),

Select::make('Status')
    ->options($statuses)
    // TODO: revert, when https://github.com/laravel/nova-issues/issues/4661 is fixed
    //->displayUsingLabels()
    ->resolveUsing(function ($value) use ($isIndexOrDetailRequest, $statuses) {
        if ($isIndexOrDetailRequest) {
            return $statuses[$value] ?? $value;
        }
        return $value;
    })
```
unfortunately, this fix doesn't work for Number field.
Just wondering, this issue is open for 6 days now, but still, no actions from Nova dev team have been made to it.

**Comment by ianrobertsFF** [comment]
displayUsing is working fine for me on .14 for TextField.vue based fields. IE Text, Number, Etc.

DisplayUsingLabels is also working fine for me, both on detail and on create/update.

Have you tried publishing the latest nova assets? Sounds like nova is sending it as `displayedAs` but your vue components are still trying to use `value` (which corresponds to the value from your database now).

Try this: https://nova.laravel.com/docs/4.0/installation.html#updating-nova-s-assets

You can verify if its coming across correctly using `displayedAs` by reverting your above changes and checking `displayedAs` in your network requests in dev tools.

`DateTime` IS a bug and should be fixed in the next version.

**Comment by TarasZakus** [comment]
Thanks, @ianrobertsFF 
Re-publishing assets actually did help in my case 👍
