### ISSUE TITLE
[4.18.0] data_set with nested attributes does not work with fields that are casted to array inside fillAttributeFromRequest

### ISSUE THREAD

**Issue by KasparRosin** [laravel/nova-issues#5005]
- Laravel Version: #.#.#
- Nova Version: 4.18.0
- PHP Version: 8.1

### Description:
Fields that have nested attribute stopped working with latest 4.18.0 release.
To make it works requires the AsArrayObject cast, but this is breaking considering the previous implementation worked with array cast.

![image](https://user-images.githubusercontent.com/33309407/199540438-30e9d8f6-76f6-4afd-a3df-0671d9355612.png)
![image](https://user-images.githubusercontent.com/33309407/199540740-8c7d680d-6257-4aa4-a483-0475dd32a3c7.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Change the default user resource name field attribute to nested key.

```php
Text::make('Name', 'name->en');
```

```
exception: "ErrorException"
file: "/vendor/laravel/framework/src/Illuminate/Collections/helpers.php"
line: 124
message: "Indirect modification of overloaded element of App\\Models\\User has no effect"
```

**Comment by KasparRosin** [comment]
Working my way backwards from #3387
it seems that casting the data to `AsArrayObject` fixed the issue. Previously it was casted to `array`.

**Comment by smoothie** [comment]
Sorry to bring this up again.. but this issue was closed without any response to the underlying problem.

The issue still exists:
- When using `array` cast, stuff is no longer updated or being created. This is an issue when using AsArrayObject is not an option.
- Question: Did v4.18.0 drop support for `array` in favor of `AsArrayObject` or is there a fix in progress?

(In case this is the wrong process for asking this question please let me know)

**Comment by davidhemphill** [comment]
It was closed because a fix was pushed in the latest release. If you need to support array, the attribute name should have a dot '.' instead of an arrow "->". Does that not work for you? If not, go ahead an post a new issue with all the deets so we can check it out. Thanks!
