### ISSUE TITLE
Regression with 4.18.0 on resource table row buttons

### ISSUE THREAD

**Issue by Phr33d0m** [laravel/nova-issues#5016]
- Laravel Version: #.#.#
- Nova Version: 4.18.0
- PHP Version: #.#.#
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
Nova update 4.18.0 brought the following change:
```
- Nova will now disable the resource table row buttons instead of hiding them.
```

This is unexpected behaviour from a minor version release without the possibility to switch to the old functionality/logic of hiding the buttons. Edit/delete buttons in my use of Nova as a read-only resource is very confusing for my users.

Please roll back the change or provide a workaround.

**Comment by dmason30** [comment]
I also raised this you can find the discussion and  also provide a patch as a proof of concept for how it could work: https://github.com/laravel/nova-issues/discussions/5002

**Comment by crynobone** [comment]
The issue with #5002 is that it wouldn't work with `load-more` pagination. @davidhemphill has already done some changes to this and we will need to test it out.

**Comment by guiribmedeiros** [comment]
Is there any way to rollback that?
It went through my CI and I cannot use the 4.17, do you know anything about that?

**Comment by davidhemphill** [comment]
Hi!

Changing Nova to disable the buttons instead of hiding them is a choice we made to better communicate the available actions to users. We will not likely be rolling this back to the old method unless there's something big we've overlooked by changing it.

I've also added a check to see if any current resources can be viewed, edited, deleted, or restored. If none of the resources in the current set can do those things, those respective buttons will be hidden, which should solve your issue.

In terms of the load-more pagination style, if, when pulling a new set of resources, there's a resource that allows one of those actions, the buttons will then display. Otherwise, they'll be hidden.

That update is coming soon.

**Comment by guiribmedeiros** [comment]
The primary issue for me @davidhemphill,
That I cannot roll back to **4.17**, it was a breaking change for us since we install the package through our CI.

**Comment by ftadra** [comment]
@davidhemphill I believe the issue is that it changes an already established behavior through a minor version that we can't rollback from. While it may seem that those UX tweaks are minor, they present unnecessary changes and adjustments to customers that rely on having a predictable user experience to users.

Many of our users will not start seeing buttons that they were not supposed to see, not only making the UI busier but also potentially creating a management issue for us as they'd request such features to become available.

I don't think this discussion should be closed without **at least** a proper workaround or a way to revert this.
