### ISSUE TITLE
version 1.0.14 still says 1.08 in footer

### ISSUE THREAD

**Issue by jasonspick** [laravel/nova-issues#521]
Was this just overlooked or did I mess something up in the update?

**Comment by dillingham** [comment]
It shows the correct version for me, completely replace the contents of /nova  and maybe try ctrl +f5 or cmd + f5. This is not an issue.

**Comment by Quinndark** [comment]
You should remove  the mirror in  the composer vendor.

**Comment by ragingdave** [comment]
Rather than all this.... did you run `php artisan nova:publish`. According to the docs that is required, but additionally, if you have overridden any of the views, then potentially a `php artisan nova:publish --force` is needed.

**Comment by jasonspick** [comment]
@ragingdave I did use the --force and followed the instructions. @Quinndark removing from vendor and doing a composer update solved the issue. So this must be a bug then?

Seems like this might cause issues in the future.

**Comment by ragingdave** [comment]
@jasonspick fair enough, just covering the bases. I've run into similar issues in other projects with Chrome being overly cache-y lately but not yet with nova. Maybe it was just browser holding onto the old resource with a deathgrip? Either way I wouldn't think it was a bug unless it happens when 1.0.15 drops and it maybe happens again?

**Comment by davidhemphill** [comment]
This is 99% likely to be a view caching issue or a customized layout not being overridden.
