### ISSUE TITLE
[1.0.15] Logout link is broken

### ISSUE THREAD

**Issue by MarceauKa** [laravel/nova-issues#537]
Just upgraded Nova from .14 to .15. Assets were freshly published.
The link is just `logout`.

**Comment by davidhemphill** [comment]
This doesn't seem to be the case on any of my 1.0.15 installs. Is there anything special about your setup?

**Comment by michaelchunn** [comment]
Mine does the same thing after upgrading.

**Comment by SethTompkins** [comment]
@davidhemphill I am seeing the same issue on the latest version: 1.1.1. 

![image](https://user-images.githubusercontent.com/3925226/45898433-f573df80-bda7-11e8-9744-e4a98f840599.png)

**Comment by ErikRobles** [comment]
I know this is closed but I am having the same issue. I have 'path' => env('NOVA_PATH', ''), set to an emply string as well and it helps with my addresses not showing nova and everything internally is working as expected. The problem comes when I want to logout, it gives a 404 error. Any help appreciated. Thank you.

**Comment by jbrooksuk** [comment]
@ErikRobles this issue specifically refers to 1.x of Nova. Can you please open a new issue with the extra details about your version etc.

**Comment by ErikRobles** [comment]
> @ErikRobles this issue specifically refers to 1.x of Nova. Can you please open a new issue with the extra details about your version etc.

Will Do. Thank you
