### ISSUE TITLE
You are not authorized to preform this action!

### ISSUE THREAD

**Issue by 3adeling** [laravel/nova-issues#542]
I created an Action which does nothing. it should just returns a success alert.

```
public function handle(ActionFields $fields, Collection $models)
    {
        return Action::message('It worked!');
    }
```

then I put it in all of my resources.

some of them shows error:
Sorry! You are not authorized to perform this action

and some shows the success message

I am trying to understand why it fails but without success. I tried to use action authorization, canSee & canRun, no difference!

Are there any hidden requirements for Actions?

**Comment by rdrnnr87** [comment]
It appears that actions are only allowed against resources which the user has update ability on.  Without any further information my best guess is that your policies prohibit update.

**Comment by arall** [comment]
I think those should be different policies, as we might want to forbid manual modifications in a resource, but allow automated ones performed by actions (where the user has no control).

**Comment by katieben** [comment]
Any movement on this? I agree these should be different policies. Here's my use case: I had to custom write a page for updating a model, since Nova wasn't quite flexible enough for what I needed. So, I want the edit button to be hidden - and I replace it with my own edit link in a field. (It would also be sufficient to redirect the edit link, but that doesn't seem easily doable, unless I'm missing something). But, I have an action admins need to perform using that model - so if I use a policy to remove their editing capability (in order to remove that edit button), they can't perform that action. Any ideas?

**Comment by shingsoso** [comment]
Any idea ? I faced the same situation with you . I have my custom permission to the specific Resource , but 'You are not authorized to preform this action!' even when I have the permission to do every action of the resource . Weird

**Comment by amosmos** [comment]
I believe this has to do with the fact that my nova resource\model has a `HasMany` fields, because I see in telescope that when I run the action, it runs few requests to the related models as well - can that be?

**Comment by amosmos** [comment]
Ok sorry, my issue was that the action was "destructive" and it seems to only allow destructive actions if the deletion policy is allowed (weird)

**Comment by tumainimosha** [comment]
@briandotdev @arall I had similar issue occur because my resource did not allow updates in its policy.

I managed to get the action authorized by calling `canRun` method on the action (see below), without adding update permission on the overall resource.

```php
/**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [
            (new Resend)->canRun(function(NovaRequest $request) {
                return $request->user()->can('manage messages');
            }),
        ];
    }
```

### before: 
<img width="439" alt="Screenshot 2019-09-11 at 12 50 05" src="https://user-images.githubusercontent.com/7481490/64687223-c2cc6680-d492-11e9-947c-a993800c8184.png">

### after:
<img width="384" alt="Screenshot 2019-09-11 at 12 49 01" src="https://user-images.githubusercontent.com/7481490/64687241-ccee6500-d492-11e9-9bce-bfc6847d25b8.png">

**Comment by vincenzoraco** [comment]
I had the same problem, I was using this package https://novapackages.com/packages/anaseqal/nova-import which helps me to import resources. The error occurs when you don't have any resource saved on the database.

So for those who is facing this issue, create a dummy record on the table, then import, and then delete the dummy row.

It seems that Nova is checking if there are any saved resourced, is it the right behaviour? It does make sense to me, but it stops us to import the initial data, if any.

**Comment by tungvn** [comment]
> 
> 
> I had the same problem, I was using this package https://novapackages.com/packages/anaseqal/nova-import which helps me to import resources. The error occurs when you don't have any resource saved on the database.
> 
> So for those who is facing this issue, create a dummy record on the table, then import, and then delete the dummy row.
> 
> It seems that Nova is checking if there are any saved resourced, is it the right behaviour? It does make sense to me, but it stops us to import the initial data, if any.

I also got this error when I was using this package.
I read the package documentation again and see this line
`Please note that it extends Anaseqal\NovaImport\Actions\Action not normal Nova Actions because it doesn't applies on models!`

When change from `Laravel\Nova\Actions\Action` to `Anaseqal\NovaImport\Actions\Action`, it's fixed

**Comment by michalisantoniou6** [comment]
I was getting this issue because I used 2 ID fields on a resource like so.

**Comment by michalisantoniou6** [comment]
@davidhemphill Thank you Laravel team for this great addition to the Laravel Ecosystem! I haven't seen my case mentioned in this thread so I'm adding my team's feedback here for your consideration.

We were getting this issue because we used 2 ID fields on a resource like so.

```
ID::make('provider_id'),
ID::make('record_id'),
```

- [Here](https://github.com/laravel/nova/blob/46e5ebbb36e56de0a0b4d87b9db63b1083da3365/src/Actions/Action.php#L264) Nova returns 'Sorry! You are not authorized to perform this action.' which confusing in my case, as I had the right permissions.
- Since Nova treats ID field as special, maybe Nova should throw an exception if you have more than one ID field defined?

Thanks.

**Comment by madshox** [comment]
> У меня была та же проблема, я использовал этот пакет https://novapackages.com/packages/anaseqal/nova-import что помогает мне импортировать ресурсы. Ошибка возникает, когда у вас нет никаких ресурсов, сохраненных в базе данных.
> 
> Поэтому для тех, кто сталкивается с этой проблемой, создайте фиктивную запись в таблице, затем импортируйте, а затем удалите фиктивную строку.
> 
> Похоже, что Нова проверяет, есть ли какие-то сохраненные ресурсы, правильно ли это поведение? Это имеет смысл для меня, но это останавливает нас, чтобы импортировать исходные данные, если таковые имеются.

it helped me, thank you

**Comment by Lapinskas** [comment]
The issue is in the following check in Laravel\Nova\Actions\Action class handleRequest method

```
                if (count($models) > 0) {
                    $wasExecuted = true;
                }
```

That check forbids an Action execution if there is no models, i.e. run an Action on new/empty resource table, even if the Action is set for the entire resource.

The solution proposed by @vincenzoraco : to insert a dummy record and delete it after action execution works as a hack, but I do not like the idea, as it could potentially left over some garbage in the database.

I have created another solution - a trait that overrides handleRequest method of Laravel\Nova\Actions\Action.
Note: this trait should be used ONLY if your action works with entire resource and need NO models.

<?php
namespace App\Nova\Actions;

use Laravel\Nova\Nova;
use Laravel\Nova\Actions\Transaction;
use Laravel\Nova\Http\Requests\ActionRequest;

```
trait ActionForEmptyResourceTrait
{
    // Needed to avoid "You are not authorized to preform this action"
    // That error occurs when an action is set for the entire resource
    // but resource table is new / empty
    public function handleRequest(ActionRequest $request)
    {
        return Transaction::run(function ($batchId) use ($request) {
            return $this
                ->withBatchId($batchId)
                ->handle(
                    $request->resolveFields(),
                    collect([])
                );
        }, function ($batchId) {
            Nova::actionEvent()->markBatchAsFinished($batchId);
        });
    }
}
```

Now I can simply use that trait in all Actions that are set for entire resource.

**Comment by curtisblackwell** [comment]
When extending `Anaseqal\NovaImport\Actions\Action`, I run into other issues since it doesn't implement all the same methods as `Laravel\Nova\Actions\Action`. To fix this, I use Laravel's `ForwardsCalls` trait.

```php
<?php

namespace App\Nova\Actions;

use Anaseqal\NovaImport\Actions\Action as NovaImportAction;
use Illuminate\Support\Traits\ForwardsCalls;
use Laravel\Nova\Actions\Action;

class ImportAction extends NovaImportAction
{
    use ForwardsCalls;

    public function __call($method, $parameters)
    {
        return $this->forwardCallTo(new Action, $method, $parameters);
    }
}
```

The whole class actually looks like this:

```php
<?php

namespace App\Nova\Actions;

use Anaseqal\NovaImport\Actions\Action as NovaImportAction;
use Illuminate\Bus\Queueable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Collection;
use Illuminate\Support\Traits\ForwardsCalls;
use Laravel\Nova\Actions\Action;
use Laravel\Nova\Fields\ActionFields;
use Laravel\Nova\Fields\File;
use Maatwebsite\Excel\Facades\Excel;

class ImportAction extends NovaImportAction
{
    use ForwardsCalls;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    public $onlyOnIndex = true;

    public function __call($method, $parameters)
    {
        return $this->forwardCallTo(new Action, $method, $parameters);
    }

    /**
     * Perform the action on the given models.
     *
     * @param  \Laravel\Nova\Fields\ActionFields  $fields
     * @param  \Illuminate\Support\Collection  $models
     * @return mixed
     */
    public function handle(ActionFields $fields, Collection $models)
    {
        Excel::import(new $this->importFQCN, $fields->file);

        return Action::message('Import complete.');
    }

    /**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields()
    {
        return [File::make('File')->rules('required')];
    }
}
```

This greatly simplifies setting up new import actions since I can just extend this class with a pretty barebones class:

```php
<?php

namespace App\Nova\Actions;

class ImportUsers extends ImportAction
{
    public $importFQCN = '\App\Imports\UsersImport';
}
```

**Comment by Abdukhaligov** [comment]
Check [this](https://github.com/laravel/nova-issues/issues/114#issuecomment-1075052018)

**Comment by pppdns** [comment]
If your Nova action is destructive, it needs delete permission on the resource:
```
public function authorizedToDelete(Request $request): bool
{
    return true;
}
```

**Comment by SeyamMs** [comment]
this worked in index and details views nova 4

```
(new \App\Nova\Actions\Project\Approve)
    ->canSee(function ($request) {
        if ($request->findModelQuery($request->resources)->count() !== 1) {
            return false;
        }
        $project = $request->findModelQuery($request->resources)->first();
        return $project->status() == 'review';
    }),
```
