### ISSUE TITLE
No euros for value sum

### ISSUE THREAD

**Issue by OpenHaus** [laravel/nova-issues#548]
Using the **sum** method on the **Value** class only offers _dollars_ but not _euros_ as elsewhere.

**Comment by bernhardh** [comment]
Then, the method should be called currency or money or something and not dollars.

**Comment by alexbowers** [comment]
Agree it should be called currency. There should probably be a way to handle it too, since different locales handle currency differently.

For example,

In a lot of europe, the format is €1.200.000,00
In the UK it's £1,200,000.00
In (some parts of?) india it is Rs 12,00,000.00

And there are probably other variations that happen.

**Comment by davidhemphill** [comment]
I've added the `currency` method which works the same as the `dollars` method. On formatting, it's a tough little problem to make it for everyone and still have smart shortening for larger numbers like we want. Will have to think on that one more.

**Comment by luislpv22** [comment]
@davidhemphill I think it should allow us placing it after or before the price if it doesn't yet, as Euros are usually placed on the right.

**Comment by davidhemphill** [comment]
@alexbowers Windows doesn't have `money_format` by default.

**Comment by alexbowers** [comment]
Weird. Typical windows. Fair enough, at least the default works for GBP :D

**Comment by luislpv22** [comment]
> @luislpv22 We have the suffix command for this. Will that not work?

It works but its displayed in a different way, too small

**Comment by dillingham** [comment]
Css
