### ISSUE TITLE
Weird behavior when clicking on rows on the index page

### ISSUE THREAD

**Issue by Hannoma** [laravel/nova-issues#5693]
- Laravel Version: 9.52.9
- Nova Version: 4.25.1
- PHP Version: 8.1.3
- Browser: Google Chrome 114.0.5735.199 (64-Bit) Windows 11

### Description:
"Open in a new tab" on the index page by holding the CTRL button down while clicking on a row does not work. Although one holds the CTRL button, and the resource detail page should open in a new tab, it redirects you to the detail page in the current tab. When locking the computer and unlocking it again, it now works. After reloading the page, the previous behavior occurs again.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by pavol-revive** [comment]
I suspect this is a problem with how the `commandPressed` is being handled in `app/vendor/laravel/nova/resources/js/components/GlobalSearch.vue` (probably introduced in https://nova.laravel.com/releases/4.21.0)

The `goToSelectedResource()` doesn't check the state of "command key being pressed" at the moment of the click, it checks it against stored `this.commandPressed` value.

The problem with this approach is when the "keyUp" event happens in a separate tab. In that case `this.commandPressed` value stays `true` even though no command key is pressed (anymore).

### Steps to reproduce
- use https://github.com/nova-issues/issue-h85209
- install, migrate, seed, login
- activate (click into) global search and type "Nova"
- "Laravel Nova" user is found
- hold command key (in my case "CTRL") and click on the found user
- it's correctly opened in new tab, so far so good
- now switch back to the original tab
- activate the global search again (it should still have "Nova" written down)
- make sure you are ***not*** holding down the command key
- click on the "Laravel Nova" user result
- it's opened in new tab, even though it shouldn't

If you now press and release the command key, the state is "reset" and correct behavior returns (until next "release in a different tab" event happens of course)

Btw. the same thing happens when you use "ctrl+tab" / "cmd+tab" to navigate the tabs in the browser (and you don't return to Nova right away), since the "command key release event" happens outside of Nova.


### Possible fix

Use [Vue's modifier keys](https://vuejs.org/guide/essentials/event-handling.html#system-modifier-keys) for the correct behavior in GlobalSearch results

```
<button
    :dusk="item.resourceName + ' ' + item.index"
    @click.exact="novaVisitSelectedResource(item)"
    @click.ctrl="openSelectedResourceInNewTab(item)"
    @click.meta="openSelectedResourceInNewTab(item)"
    ...
>

```
