### ISSUE TITLE
Change Resource name away from soft-reserved name

### ISSUE THREAD

**Issue by 907544030** [laravel/nova-issues#578]
Considering the `App\Nova\Resource` rename to another name because of **Resource** is a soft-reserved by PHP.
https://github.com/laravel/framework/pull/22969

**Comment by davidhemphill** [comment]
We may do this in a future version, but right now it's not a problem.

**Comment by korridor** [comment]
@davidhemphill  Problem is that other libraries like php-cs-fixer now correct `Resource` to `resource`, because they assume that using `Resource` as a class name must be a typo: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/8095#issuecomment-2636288783

Please reconsider renaming `Resource` in future releases.
