### ISSUE TITLE
Navigating throws js error

### ISSUE THREAD

**Issue by zeshan77** [laravel/nova-issues#5816]
- Laravel Version: 10.19.0
- Nova Version: 4.27.12
- PHP Version: 8.2.6
- Browser type and version: Safari / Version 16.6 (18615.3.12.11.2)
- Browser type and version: Chrome / Version 115.0.5790.170 (Official Build) (arm64)
- Browser type and version: Firefox / 116.0.3 (64-bit)

### Description:
Any navigation/link inside nova stopped working. It basically changes the URL in browser's address bar but doesn't load the page. In console it throws a js error (See attached screenshot).

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Log into Nova
- Click on any menu in the side bar (it works for the first click but stopped working on any subsequent links)
- Click on any other link (either menu or a link inside the page), you'll be able to notice that it doesn't show corresponding page.
- You'll also be to see js error in console of the browser's dev tool.

It used to be working until I upgraded to **NOVA 4.27.12**
<img width="1492" alt="261537423-d046f8ef-1c45-4bab-9ad5-9282460a5271" src="https://github.com/laravel/nova-issues/assets/2544017/9e42e59f-166f-4ca0-8b8d-0a9401f0ca3a">

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by ramonfeleus** [comment]
Laravel Version: 9.52.15
Nova Version: 4.27.12
PHP Version: 8.1.3
Browser type and version: Chrome / Version 115.0.5790.170 (Official Build) (arm64)
Versie 114.0.5735.198 (Officiële build) (x86_64)

I am having similar issues. The following happens when I save a resource.
<img width="712" alt="Scherm­afbeelding 2023-08-18 om 13 22 09" src="https://github.com/laravel/nova-issues/assets/73035608/cbf06171-c473-476a-8f59-bbfb1b8525d2">
Sometime I seemed to be able to get rid of similar errors when I ran nova:install and nova:publish commands (this might refresh compiled frontend assets). But on save I still get the notices in the screenshot.
Maybe this only happens on an existing checkout of a project, and not on a new fresh project.
But as this would also affect live sites when rolling out updates (instead of clean install) this would cause issues for customers.

Composer.json includes the following requires:
`
"require": {
        "php": "^8.1",
...##private packages with our resources & tools##...
        "bakerkretzmar/nova-settings-tool": "dev-main",
        "guzzlehttp/guzzle": "^7.5",
        "itsgoingd/clockwork": "^5.0",
        "laravel/framework": "^9.32",
        "laravel/nova": "^4.27.12",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.5",
        "league/flysystem-aws-s3-v3": "^3.0",
        "livewire/livewire": "^2.6",
        "spatie/laravel-honeypot": "^4.0",
        "spatie/laravel-medialibrary-pro": "^2.7.3",
        "spatie/yaml-front-matter": "^2.0",
        "titasgailius/search-relations": "^1.0",
        "whitecube/nova-flexible-content": "dev-master",
        "wikimedia/composer-merge-plugin": "^2.0"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/breeze": "^1.9",
        "laravel/sail": "^1.16.1",
        "mockery/mockery": "^1.5.1",
        "nunomaduro/collision": "^6.1",
        "nwidart/laravel-modules": "^9.0",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
`

**Comment by crynobone** [comment]
> Maybe this only happens on an existing checkout of a project, and not on a new fresh project.

This can be caused by 3rd party package and it's something that is out of our control and support as the fix need to be done on the packages themselves.

We have intensive dusk tests to cover the usage and none is failing on our side.

**Comment by ramonfeleus** [comment]
When set the version fixed to `"laravel/nova": "4.25.1",` it does not happen. It does however when I upgrade it to something above 4.26 however, and it's the only package updated.
Maybe it's something the tests just don't cover as it happens more on a page/inertia request.
The most frontend code heavy of the packages I'm including is `whitecube/nova-flexible-content` @zeshan77 are you using that as well by any chance?

**Comment by adamyulian** [comment]
> When set the version fixed to `"laravel/nova": "4.25.1",` it does not happen. It does however when I upgrade it to something above 4.26 however, and it's the only package updated. Maybe it's something the tests just don't cover as it happens more on a page/inertia request. The most frontend code heavy of the packages I'm including is `whitecube/nova-flexible-content` @zeshan77 are you using that as well by any chance?

you save my life 💯 🥇 :)

**Comment by crynobone** [comment]
> Maybe it's something the tests just don't cover as it happens more on a page/inertia request.

Unlikely, but you can submit a reproducing repository as requested above to get things going. Our dusk tests have already cover the use case as described without issue.

**Comment by parth-ka-patel** [comment]
I am also facing the same issue but after applying [this solution ](https://github.com/laravel/nova-issues/issues/5816#issuecomment-1683852217)and downgrading my nova version it works now

**Comment by ramonfeleus** [comment]
Seems that it happens for more people. Good to see that the downgrade helps, at least that is something consistent. Could those for who this worked also post a list of their composer requires? @adamyulian @parth-ka-patel  Maybe there's a common external package that causes it. Otherwise it really is likely to be Nova itself despite tests aren't failing.

**Comment by crynobone** [comment]
> Otherwise it really is likely to be Nova itself despite tests aren't failing.

More people would already be in this discussion if it was widespread. The only way to move forward is for someone to send in a reproducing repository as requested.

**Comment by ramonfeleus** [comment]
I think I've found what the issue was: As @crynobone requested I was making a project to reproduce the issue this morning. At first I wasn't able to reproduce it. So I went back to existing projects and upgraded them to nova 4.27.12. Strangely the issues were gone, where I still had them yesterday.
But while composer upgrading those projects I also noticed that an update of ebess/advanced-nova-media-library would come along with it.
In the past 24 hours 2 new tags were released (4.1.3 and 4.1.4) and I suspect this js change fixed the issue:
https://github.com/ebess/advanced-nova-media-library/commit/b8f70e6e5b48f04ff838e657909a47a28ddb928e
Because when I went back to my clean new project to reproduce the issue I added this uploader linked to the 4.1.2 version: "ebess/advanced-nova-media-library": "4.1.2",
and by adding an Image uploader from that plugin to my page resource I was able to reproduce it on that repository.
You can find my project repo here: https://github.com/ramonfeleus/novaissues/tree/navigationjs_5816 
the latest commit adds the breaking field.

So I would recommend others to upgrade to the latest version of  `ebess/advanced-nova-media-library` if they are using it. Or use a different uploader, I myself am in the process of integrating a new custom built one in our projects...

**Comment by crynobone** [comment]
@ramonfeleus It seem your assets match Laravel Nova `4.25.1` here: https://github.com/ramonfeleus/novaissues/blob/navigationjs_5816/public/vendor/nova/mix-manifest.json

![CleanShot 2023-08-24 at 12 31 06](https://github.com/laravel/nova-issues/assets/172966/2d402a64-2a41-4492-beaa-7bcf45b966d0)

Did you forget to run `php artisan nova:publish`?

**Comment by ramonfeleus** [comment]
@crynobone It appears so yeah. Strange, as I was constantly running that with the other projects :-) I've updated the repo, but the errors are gone now. So then it wasn't the ebess plugin either it seems.
