### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot destructure property 'status' of 't' as it is undefined. (axios)

### ISSUE THREAD

**Issue by AbdallahAli912** [laravel/nova-issues#6052]
- Laravel Version: 9.19
- Nova Version: 4.21
- PHP Version: 8.0.2

### Description:
<img width="490" alt="Screenshot 2023-11-20 at 5 41 37 PM" src="https://github.com/laravel/nova-issues/assets/54299150/2034e6f0-7156-41ff-b1c2-926a0d5d682a">

can't made any request or open any resource in nova.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by wamesro** [comment]
I have the same error when updating from 4.29.5 to 4.32.1
The problem is already in 4.29.6 because it doesn't work there either

I'm using the package https://github.com/stepanenko3/nova-boolean-group-field

The problem is when I want to get the value from another Field via `depedsOn()`
I don't know if it's a Laravel Nova bug or if it's a new feature that other packages are supposed to use

I described more in the Issue to the author 
https://github.com/stepanenko3/nova-boolean-group-field/issues/4

**Comment by andypooletrioteca** [comment]
Had the same issue and solved it by overriding the axios package in the custom components that used the package form-backend-validation. Saw it here https://github.com/spatie/form-backend-validation/issues/98

**Comment by davidhemphill** [comment]
To diagnose and fix issues, we need to be able to reproduce them. Having detailed bug reports, and ideally, a reproduction repository is the best way to help us.

When you can provide a reproducible example on a fresh instance of Nova, we'd love to take a look and work towards a resolution!

**Comment by Bibesko** [comment]
I solve this problem by run `npm update & npm run prod` in my custom field folder. If u can't run this commands first try to run this `cd vendor/laravel/nova && npm install` in root of app folder.

**Comment by salmanhijazi** [comment]
> Had the same issue and solved it by overriding the axios package in the custom components that used the package form-backend-validation. Saw it here [spatie/form-backend-validation#98](https://github.com/spatie/form-backend-validation/issues/98)

Can you explain how you did this?
