### ISSUE TITLE
Issue with Nova Forms containing `overflow-hidden`

### ISSUE THREAD

**Issue by robmellett** [laravel/nova-issues#6096]
## Nova Version: #.#.#

```code
laravel/nova  4.32.6 
```

### Description:
Nova Forms contain a `overflow-hidden` css class that breaks overflowing content from select drop down menus. 

This issue appears to be different from the following issues.
- https://github.com/laravel/nova-issues/issues/5874
- https://github.com/laravel/nova-issues/issues/6040

### Detailed steps to reproduce the issue on a fresh Nova installation:

<img width="1512" alt="Screenshot 2023-12-11 at 07 51 06" src="https://github.com/laravel/nova-issues/assets/26024074/61371a1d-6465-4374-b2ac-fb97d52ad838">

The Nova container containing the line `class="relative overflow-hidden bg-white dark:bg-gray-800 rounded-lg shadow divide-y divide-gray-100 dark:divide-gray-700"`.

When it has the class `overflow-hidden` it causes problems for one of our drop down components. Is there a way to revert or remove this class from nova please?

## Example with the issue
<img width="1512" alt="Screenshot 2023-12-11 at 08 02 33" src="https://github.com/laravel/nova-issues/assets/26024074/99717b10-f3e2-4c26-93d2-789d074d9ac2">

## Example when the `overflow-hidden` is removed

<img width="1512" alt="Screenshot 2023-12-11 at 08 03 45" src="https://github.com/laravel/nova-issues/assets/26024074/445b65ae-c260-4d2c-bad9-86b349c93795">

**Comment by ralphschindler** [comment]
I can confirm this is also an issue when using `nova-flexible-content` when you attempt to bring up a dev based select near the bottom of the form.

**Comment by ralphschindler** [comment]
@davidhemphill regarding the built-in fields, is your solution to teleport the overlay div outside of the `<div class="relative overflow-hidden ..">` node?  If so, it is going to be hard to replicate that kind of solution in 3rd party Nova Fields that use 3rd party Vue component since typically you may not be able to get ahold of all the div/nodes that need to be teleported.

In the case above (and also my library `nova-select-plus`), I leverage `vue-select` https://vue-select.org/api/slots.html to produce a specialized kind of select field. As you can imagine, I won't be able to teleport the vue-select overlay because I don't have control over its rendering of the overlay, and the whole input can't be teleported.

Out of curiosity, what value is `overflow-hidden` providing in that Card? Does making that div overflow visible break anything in Nova?

**Comment by emarshall87** [comment]
This issue is also affecting the use of `position: sticky` on any children elements within the `overflow: hidden` container. It's quite difficult to replicate the smooth native css ability of `sticky`. An `overflow: clip` instead would solve my particular issue with `sticky`.

**Comment by olieady** [comment]
Can confirm our WYSIWYG editor's toolbar is no longer sticking to the top of the page for ease-of-use because of this update. 

Not sure why overflow-hidden is used here?
