### ISSUE TITLE
Show / hide content length determination

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#649]
![hide-content](https://user-images.githubusercontent.com/29180903/45923099-9fd42b80-beaa-11e8-8684-5783d13f3629.png)

When the length of the content is shorter than the button text, doesn't make sense to hide content
Furthermore, would be lovely to set a numerical length to which content is hidden.
Furrrrrthermore, would be great to not hide at all in some cases.

**Comment by davidhemphill** [comment]
Added `alwaysShow` which will always show the content. Will be included in an upcoming release. 👍 

On the length-aware thing, it presents a little bit more of a problem because it stores the raw markdown so the character count isn't a reliable indicator. Would rather just have it work the current way because of that.

**Comment by alexbowers** [comment]
@davidhemphill Thoughts on a `shouldShow` function that accepts a callback that will be either true or false?

**Comment by dillingham** [comment]
@davidhemphill Ah didn't consider the markdown! Thanks for including that method

**Comment by davidhemphill** [comment]
@alexbowers Seems a little much, but I added it. 💃
