### ISSUE TITLE
[Bug] View/Edit/Delete actions are displayed on lens without 'id' column

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#655]
When the query of a lens does not select an `id` column, the view/edit/delete actions are still displayed on every row. Obviously, the buttons don't work anymore because there is no unique identifier for the row. The`href` attribute just points to `/nova/`.

**Comment by chescos** [comment]
@alexbowers yes, I would expect that the buttons would not show up if there is no `id` column. Currently, the buttons are just useless because they don't do anything. In fact, if you click on them, an exception is thrown.

If there is no `id` column, it's most likely because the query retrieves aggregated data. It makes no sense to have those buttons there because the rows don't relate to actual database rows.

**Comment by ppisecky** [comment]
I agree with @chescos. A use case has emerged for displaying aggregates over time periods for example. In cases like these it makes no sense to include the control buttons as they have nothing to attach to because the rows do not correspond to records but rather to aggregates of those records.

While I don't think this is a great solution I managed to find a work-around. `Lens` classes seem to delegate some of their responsibilities to corresponding `Resource` (in order to display the index, implement filtering and so on).  So at the moment you can use a hacky method to get rid of those pesky buttons by exploiting authorization implementation within your Resource class.

As part of its routing structure, Nova lens routes include a lens parameter that contains the URI key of your lens. You can explicitly define it using the `uriKey` method within your lens class (e.g. `OrdersPerformanceLens`):

```php
/**
 * Get the URI key for the lens.
 *
 * @return string
 */
public function uriKey()
{
    return 'orders-performance-lens';
}

```
 
Using this key you can then override the `serializeForIndex` method on the corresponding resource class to detect routes that lead to your aggregating lens and then use authorization to disable those options:

```php
/**
 * Prepare the resource for JSON serialization.
 *
 * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
 * @param  \Illuminate\Support\Collection  $fields
 * @return array
 */
public function serializeForIndex(NovaRequest $request, $fields = null)
{
    // Get proper response
    $serialized = parent::serializeForIndex($request, $fields);

    if ($request->lens && $request->lens == 'orders-performance-lens') {
        // If a lens is being viewed 
        $serialized = array_merge($serialized, [
            'authorizedToView' => false,
            'authorizedToUpdate' => false,
            'authorizedToDelete' => false,
            'authorizedToRestore' => false,
            'authorizedToForceDelete' => false,
        ]);
    }

    return $serialized;
}
```

I haven't had to go too much in-depth on this so use at your own risk. There seem to be multiple routes defined that use the `lens` parameter and I haven't had time to look how they are used.

**Comment by dillingham** [comment]
Related https://github.com/laravel/nova-issues/issues/766

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by chescos** [comment]
@davidhemphill this is a bug, not a feature requests. An exception is thrown when you click on the buttons.

**Comment by RCJYLMS** [comment]
@ppisecky the solution not working for me,
is there another solution ?

**Comment by crynobone** [comment]
@RCJYLMS This is a 2 year old issue and any suggestion may no longer be relevant at the moment. Please create new issue describing in full the problem you're having if you found a bug or you could try to ask on our alternative support channels described in https://nova.laravel.com/docs/3.0/support.html#support-questions
