### ISSUE TITLE
[Request] Value Metric: don't add the plural 's' if the suffix isn't a word

### ISSUE THREAD

**Issue by wfeller** [laravel/nova-issues#696]
I'd like a display a percentage, so I added a `->suffix('%')` to my result and had an unexpected result. I'd like it to show 67% instead of 67%s...

![image](https://user-images.githubusercontent.com/21337627/46111330-e0071700-c1e6-11e8-94bd-a43b6edc8ff9.png)

**Comment by alexbowers** [comment]
Rather than using suffix for this, I think a better use would be a format function that if provided, would receive the value, and its response will be the format of the output.

Example:

```

public function format($value) 
{
    return number_format($value, 2) . "%";
}
```

to create your example.

This will allow people to determine whether or not things like memory usage should display Mb, Gb, Tb etc.

Related to https://github.com/laravel/nova-issues/issues/620

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
