### ISSUE TITLE
Filter by multiple values in the same field

### ISSUE THREAD

**Issue by alexbowers** [laravel/nova-issues#706]
The ability to choose multiple filters from the same "dropdown" on the Resource index page.

For example, `account_type` is `1 or 2`.

Perhaps it could be done with a `public static $multiple = true` which converts it to a list of checkboxes?

**Comment by ragingdave** [comment]
I would think it might be easier to just assume that the value could be an array and handle it appropriately rather than having to opt in to it. In any case I can think of it's easier to convert to assuming an array anyways.

`where -> whereIn` for simple filters, and just a simple loop of the exact logic already in place (for those upgrading)

**Comment by dillingham** [comment]
I added this as a nova package idea https://github.com/tightenco/nova-package-development/issues/53

![filter-select](https://user-images.githubusercontent.com/29180903/46161330-46c21a00-c253-11e8-873d-e54c6575701a.png)

**Comment by davidhemphill** [comment]
This should be accomplishable by using the new boolean filter and implementing the logic in your apply method 👍
