### ISSUE TITLE
[FR, Patch] Need to add custom filter identifier.

### ISSUE THREAD

**Issue by dkulyk** [laravel/nova-issues#788]
Laravel: 5.7
Nova: 1.1.4
PHP: 7.2.10

If you used more than one filter with one class then second filter doesn't work because a filter is identified by class name.

Need to add method to the Filter for generate filter's id and compare the id instead the class name.
This add ability to make custom filter's id and make it shorter(Ex: `manager` instead `DtKt\Dealers\Nova\Filters\ManagerFilter`).

https://gist.github.com/dkulyk/c33671f4924e19d1c0e53e8930e7d5a9

**Comment by DavidNgugi** [comment]
I don't understand what you're doing here, which file are you referring to in the gist?  I've also experienced an issue in Laravel Nova where I'm using my own Custom Filter that displays a range slider and a Date Filter. The problem is, only one can be displayed at a time it seems due to conflicting component names I guess but the problem is that Nova renders only one custom `filter-selector` component. How can this be addressed @themsaid ?

**Comment by dkulyk** [comment]
When you use one filter for a few filter you can extend base filter or pass field name to the constructor.
In second way will works only first filter because the filter identified by the class name. For fix this behavior need to add filter identifier, which may differ from the class name.
This does not affect the implementation of the filters.

**Comment by davidhemphill** [comment]
A reworking of filters is coming and this patch will no longer be relevant by then.

**Comment by batFormat** [comment]
> A reworking of filters is coming and this patch will no longer be relevant by then.

Hi, Has anything changed? The code is still tied to the class...

**Comment by dkulyk** [comment]
It default behaviour. You can override key() method.
