### ISSUE TITLE
Console error occurs when applying a filter.

### ISSUE THREAD

**Issue by phoenixg** [laravel/nova-issues#898]
- Laravel Version: 5.7
- Nova Version:  v1.1.7
- PHP Version: PHP 7.2.7

### Description:

Error occurs when applying a filter.

![image](https://user-images.githubusercontent.com/990040/47563387-400eeb80-d954-11e8-8037-a8b18bef84f0.png)

### Steps To Reproduce:

Just apply a filter, no filter works now. I've done below steps, still not work:

```
change to the vendor/laravel/nova directory
rename webpack.mix.js.dist to webpack.mix.js
run npm install
run npm run dev
change back to the project root directory and delete the public/nova-assets directory.
run php artisan nova:publish
```

After I checkout to an older version of Nova(v1.1.4) without recompiling the frontend stuff, the problem disappears, so it must be the PHP logic change which triggerred this error, and it's probably related to the Filter stuff.

**Comment by davidhemphill** [comment]
Needs more info about your code setup.

**Comment by Grayda** [comment]
I've got the same issue. I suspect I had done something while trying to make some tweaks to the CSS (e.g. the `webpack.min.js.dist` thing).

I wasn't too far into my project, so I just started again, but try using the `--force` flag for things like `nova:publish` which will **overwrite files** and get you back to square one in terms of Nova's core files. 

After I started again, filters worked perfectly (and the whole thing loaded MUCH quicker than before). I'm not sure why, because all I did was create one CSS class (`width: 100%` for `.CodeMirror`), but forcing a publish may work for you.

Make sure you back up your project first!
