### ISSUE TITLE
Route Naming

### ISSUE THREAD

**Issue by aios** [laravel/nova-issues#94]
![image](https://user-images.githubusercontent.com/737550/44561629-56cf7100-a75e-11e8-8de3-109d29be440c.png)

Same for /nova/{view}

`|        | GET|HEAD | nova/{view}                                                                                | nova.                               | Laravel\Nova\Http\Controllers\RouterController@show`

**Comment by davidhemphill** [comment]
What is your issue?

**Comment by aios** [comment]
i need to use route('nova.api.somealias', [//...someparams]) for make route-link for nova-api/{resouce}/count

How i can make that?

**Comment by arnordhaenens** [comment]
@aios You can do this using `action` instead of `route`. 

```php

<?php

// ...

action('\Laravel\Nova\Http\Controllers\ResourceCountController@show', ['resource'=>'test-resource']);

// ...

```

**Comment by aios** [comment]
@arnordhaenens yes - but `route('nova.api.resource.count', ['resource' => 'test-resource'])` don't looks fine instead of your action?

**Comment by arnordhaenens** [comment]
@aios, If I understand correctly. 

Your above solution will not work untill the routes are actually named. 
In the current version, calling your above snippet throws an `InvalidArgumentException` because the route with that name doesn't exist. 

The solution I posted enables you to access the desired URL untill the names are actually provided on the routes.

**Comment by aios** [comment]
@arnordhaenens yes your understand right. I think its not issue - more then feature request

**Comment by davidhemphill** [comment]
I don't see why you'd need to add a route in Nova's api namespace. Just create a new route.

**Comment by ragingdave** [comment]
@davidhemphill I know this is an old issue, but rather than create a new one, I figured I would add it here. I think that perhaps the issue was that the named routes are incomplete, so creating a deep link to a nova route is very cumbersome with having to use the controller@method syntax rather than just something like `nova.api.resource.view` with the resource and resourceId params instead. While yes currently the controller@method syntax works, it's not as good as it could be
