### ISSUE TITLE
Delete all selected resources

### ISSUE THREAD

**Issue by gindra** [laravel/nova-issues#993]
Hi all,

Just found strange thing. 

I have resource with 750 records.

Then I selected All matching records (750) and then tried deleting all of them, the action delete (default nova delete button on the right side) only 300 of them. 

How to delete all selected resources?

**Comment by crnkovic** [comment]
This seems like a performance issue in `ResourceDestroyController`. In the controller method, you can see it chunk the resources by 150 records and execute 3 queries per model in each chunk. If you have let's say 1000 models, it will run 450 queries per chunk. Which is **a lot**. If you remove all that logic from the callback in the said controller, it actually runs the loop 1000 (in your case 750) times, meaning it manages to query all model records from the database, however as soon as you start putting DELETE queries, Laravel can't handle that.

One way of perhaps fixing it is doing some performance changes. Such as running DELETE query for a batch of models (you can pass WHERE IN constraint to the DELETE query), instead of looping through each model in a chunk and calling `delete` method, and doing batch insert of the Actions. Since all resources are tied to the same model, calling `in_array(Actionable::class, class_uses_recursive($model))` in every iteration of the loop is pretty expensive and can be extracted

**Comment by dillingham** [comment]
Related https://github.com/laravel/nova-issues/issues/326

**Comment by davidhemphill** [comment]
Batching deletions doesn't allow for model events to be fired. There's definitely an issue here, but not sure what the fix is *just* yet.

**Comment by dillingham** [comment]
@davidhemphill maybe if shouldQueue it uses eloquent on each model? Or a config setting for those of us ok with the performance hit

**Comment by dkulyk** [comment]
For deleting you need to use reverse chunks. From last page to first.
I'll try to prepare PR soon.
